### ISSUE TITLE
Add inputAccessoryView to textInputView issue

### ISSUE THREAD

**Issue by chlebta** [layerhq/Atlas-iOS#1000]
Hi,
I'm trying to add an accessoryView to messageInputToolbar in this way (Example ) : 
```
UISegmentedControl *segmentedControl = [[UISegmentedControl alloc] initWithItems:@[@"keyboard", @"sticker", @"photo"]];

    
    [self.messageInputToolbar.textInputView setInputAccessoryView:segmentedControl];
```

But when I click on textField the keyboard is not appearing : 
![sans titre](https://cloud.githubusercontent.com/assets/1204608/10389260/e1466740-6e67-11e5-8a65-98aa645daaea.png)

**Comment by kmahal** [comment]
@chlebta this goes beyond Atlas implementation, and is an iOS development question, as there are no Atlas specific constraints preventing this behavior (since our `ATLMessageInputToolbar` is just set as the view's `inputAccessoryView`.  I'm going to closes this out, but if it's on the simulator then click "toggle software keyboard" and that should show the literal keyboard.

**Comment by chlebta** [comment]
No, it's an issue with atlas implementation just try to add
inputAccessoryView to the atlas sample project and check if it work ?
I'm using device not simulator.

**Comment by chlebta** [comment]
After digging into code , I found the function at **ATLBaseConversationViewController** which maybe the responsable of that inappropriate behavior : 
```

- (void)updateBottomCollectionViewInset
{
    [self.messageInputToolbar layoutIfNeeded];
    
    UIEdgeInsets insets = self.collectionView.contentInset;
    CGFloat keyboardHeight = MAX(self.keyboardHeight, CGRectGetHeight(self.messageInputToolbar.frame));
    
    insets.bottom = keyboardHeight + self.typingIndicatorInset;
    self.collectionView.scrollIndicatorInsets = insets;
    self.collectionView.contentInset = insets;
    self.typingIndicatorViewBottomConstraint.constant = -keyboardHeight;
}
```

So commenting, or removing, the code inside this function will allow keyBoard to appear with the inputAccessoryView but the messageToolbar will not scroll up when keyboard appear. 

![sans titre](https://cloud.githubusercontent.com/assets/1204608/10424140/71febbda-70c4-11e5-8813-169cfb706707.png)

**Comment by kmahal** [comment]
@chlebta That method is important to keep Atlas functional with the keyboard up, but your example is helpful to debug :).  If you use the default implementation, check the frame of your segmented control, as it may be on the same height as where the message input toolbar is, as they are both owned by the keyboard's window.  Either the OS should handle 2 input accessory views (one for the view, one for the textview) which it doesn't seem to do, or the application should handle it.  Your own subclass can handle the frame, or feel free to submit a pull request to allow Atlas to configure the `ATLMessageComposeTextView`'s input accessory view frame when the `ATLMessageInputToolbar` is on screen.

**Comment by chlebta** [comment]
I'm not very sure about that but this problem is caused by **    self.typingIndicatorViewBottomConstraint.constant = -keyboardHeight;
** line there's some sort of conflict between inputAccessoryView and typingIndicator. 
Could you change this issue to bug to get some help :)

**Comment by chlebta** [comment]
@kmahal Any update about this issue ?

**Comment by kmahal** [comment]
@chlebta feel free to submit a pull request with any improved functionality you'd like to see.  We haven't been able to look into it too deeply but I can update you when we do.

**Comment by kmahal** [comment]
@chlebta any update on this one?  If not I'll close it out.
