### ISSUE TITLE
Images not being shown to the recipient when sent

### ISSUE THREAD

**Issue by UNLUCKYME** [layerhq/Atlas-iOS#1005]
So when a user sends an image, the user can see the image they uploaded and subsequently sent, however the recipient CANNOT see the image, it's simply a grey box.

I've read about this issue elsewhere but I can't remember where. Any help?

**Comment by kwkhaw** [comment]
I guess u are referring to this issue. https://github.com/layerhq/Layer-Parse-iOS-Example/issues/15, related to auto-download size.

**Comment by UNLUCKYME** [comment]
I believe so, where exactly do I add that code, I'm assuming in the objective c files but not sure where.

**Comment by kmahal** [comment]
Hi @UNLUCKYME when initializing your `LYRClient`, add the following autodownload mime types:
```objc
    client.autodownloadMIMETypes = [NSSet setWithObjects:ATLMIMETypeTextPlain, ATLMIMETypeImageJPEGPreview, nil];
```
