### ISSUE TITLE
Slowness while scrolling

### ISSUE THREAD

**Issue by koptan** [layerhq/Atlas-iOS#1006]
Hi ,

 I am testing my App in iPhone 6 , but i am facing some slowness while scrolling especially when Text Cell will appearing even after latest update for "Cell Height Cashing"  .

So my question is there any trick I can do to speedup ??

**Comment by kmahal** [comment]
@koptan We're still investigating ways of upgrading scroll performance.  A lot of main thread time is spent in updating constraints on ios9, and we're working on a solution for it.  We'll post an update here when we have more news.

**Comment by koptan** [comment]
Hi , @kmahal  , 

Any update on this topic ?

Thank you.

**Comment by JRam13** [comment]
You can add
```
    cell.layer.shouldRasterize = YES;
    cell.layer.rasterizationScale = [UIScreen mainScreen].scale;
```
To ``` - (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath``` for a slight performance improvement. Just be careful when implementing this.

**Comment by kmahal** [comment]
@koptan we had performance improvements here: https://github.com/layerhq/Atlas-iOS/pull/1036.  Please test again and let me know how it feels, and we can re-open this issue.
