### ISSUE TITLE
Cocoapods installation fails with Realm together

### ISSUE THREAD

**Issue by mladjan** [layerhq/Atlas-iOS#1012]
When you try to build last cocoapods version with Realm together, public headers for Atlas can't be found. When you remove realm, it works.
Realm itself, works fine.

After that, I installed only LayerKit using cocoapods, and installed manually Atlas, and project builds fine right now.

**Comment by maju6406** [comment]
We made a small tweak to the LayerKit cocoapod. Can you try removing the Podfile.lock and Pods folder and try running 'pod install' again?

**Comment by mladjan** [comment]
Tried, the same :|
Using Realm (0.93.2)
Using Atlas (1.0.12)

**Comment by kmahal** [comment]
@mladjan we just released a new Atlas `1.0.13`, let me know how it works now.

**Comment by mladjan** [comment]
Still the same problem with 1.0.13 :(

**Comment by love4soul** [comment]
I have the same problem

**Comment by blakewatters** [comment]
Fixed in Atlas v1.0.14

Verified with: Xcode 7.1, CocoaPods 0.39.0, LayerKit 0.17.0, Atlas 1.0.14, Realm 0.96.2 in a Swift 2 project
