### ISSUE TITLE
ATLAddressBarViewController.h not found after latest pod update

### ISSUE THREAD

**Issue by jantos** [layerhq/Atlas-iOS#1014]
After running pod update this morning, I suddenly got the following error: ATLAddressBarViewController.h not found after latest pod update. Afterwards I deleted the podfile.lock file, the Pods folder and ran pod install:
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Installing Atlas (1.0.12)
Installing Bolts (1.3.0)
Installing FBSDKCoreKit (4.7.0)
Installing FBSDKLoginKit (4.7.0)
Installing FBSDKShareKit (4.7.0)
Installing LayerKit (0.17.0)
Installing Parse (1.9.0)
Installing ParseFacebookUtilsV4 (1.9.0)
Installing ParseTwitterUtils (1.9.0)
Installing ParseUI (1.1.6)
Installing SVProgressHUD (1.1.3)

But still getting the same error.

When I add "${PODS_ROOT}/" recursive to the Header Search Paths the error goes away and the project compiles for the simulator, but it immediately crashes with the following error:
dyld: Library not loaded: @rpath/LayerKit.framework/LayerKit
  Referenced from: /Users/abcdefgh/Library/Developer/CoreSimulator/Devices/347C7B10-E788-4F75-9169-B34BCEA2D707/data/Containers/Bundle/Application/12071E3D-B21F-4226-89C3-B227301B32E6/abcdefgh.app/ABCDEFGH
  Reason: image not found

I am using Xcode 7.0.1, deployment target ios sdk 8, simulator iPhone 6 (9.0)

**Comment by DevMoz** [comment]
+1

**Comment by kmahal** [comment]
we'll be releasing `1.0.13` shortly with a fix for this.

**Comment by maju6406** [comment]
@DevMoz @jantos 1.0.13 has been released.

**Comment by kmahal** [comment]
@jantos @DevMoz how is `1.0.13` looking?

**Comment by DevMoz** [comment]
@kmahal Yep, I got it working! Thank you!

**Comment by cashmash** [comment]
1) I cloned the iOS-Parse-Example project
2) I removed pods, lock, pods folder
3) i added back podfile and did pod install with the newest Atlas and Layer releases
4) getting ATLAddressBarViewController.h file not found error

Any suggestion?

**Comment by cashmash** [comment]
even with the newest Atlas 1.0.13 + Layer 0.17.0 I had the same problem.
I also had to add "${PODS_ROOT}/" recursive to the Header Search Paths.

**Comment by lossefanya** [comment]
I'm using Layer 0.17.0 without Atlas. And I have same problem. So I suppose this  is a problem of LayerKit. Any help please?

**Comment by bradytate** [comment]
@lossefanya I believe it could not be the same issue as ATLAddressBarViewController.h is a class that is specific to Atlas (hence the 'ATL' pre-fix). If you are not using Atlas you shouldn't get any errors about a missing Atlas class.

**Comment by emkman** [comment]
I am still having this issue with Atlas 1.0.13 + Layer 0.17.0 + CocoaPods 0.39.0 after cleaning and building.
Happy to post my Podfile.lock if that helps.

**Comment by emkman** [comment]
Temporary fix was similar to @cashmash 's suggestion. I went to Header Search Paths in Build Settings. An entry for `"${PODS_ROOT}/Headers/Public/Atlas"` already existed, and I had to switch it from non-recursive to recursive. This is the only Pod that I had to do this for.

**Comment by lossefanya** [comment]
I found solution for my problem. it was putting "use_frameworks!" in podfile. I learned that I shouldn't miss your changelog https://developer.layer.com/docs/ios/changelog

**Comment by bharv410** [comment]
@emkman 's solution fixed the problem for me

**Comment by emkman** [comment]
@bharv410 glad to here.

In my case, we are not using Swift and not using the "use_frameworks!" directive. I have had to make this same recursive paths change to the LayerKit pod as well. Seems like there is still an outstanding problem here. cc @kmahal

**Comment by williamtwilson** [comment]
I'm still seeing this in 1.0.19. The solution was similar to those above, adding `$(PODS_ROOT)/Atlas/**` to the Header Search Paths

**Comment by AdamBCo** [comment]
I'm running into the same issue. +1

**Comment by kylebshr** [comment]
Seeing this with Cocoapods 1.0 and Atlas 1.0.22, neither of the fixes above are working.

**Comment by janweinkauff** [comment]
Same issue here with Atlas 1.0.22 and Cocoapods 1.0.1.

**Comment by emkman** [comment]
@janweinkauff and others, you may need to delete your DerivedData folder for the project after doing `pod install`, epecially after upgrading Cocoapods versions. It is found at `~/Library/Developer/Xcode/DerivedData/`. This resolved my errors with missing .h files.

**Comment by JoeFerrucci** [comment]
Just updated Cocoapods from `0.39.0` to `1.0.1` and now Atlas is breaking.

`Could not build Objective-C module 'Atlas'`
*and*
`ATLAddressBarViewController.h` *file not found*

LayerKit is at `0.17.7`
Atlast is at `1.10.15`

**Comment by petec029** [comment]
I am running into the same problem of ATLAddressBarViewController.h file not found after upgrading to XCode 8and doing a pod update to update to 
LayerKit 0.23.1
Atlas 1.0.27

**Comment by Gman9855** [comment]
Having same problem, Xcode 8, Layerkit 0.17.2, Atlas 1.0.15, none of the fixes above worked for me.  Anyone have any other suggestions??
