### ISSUE TITLE
Keyboard Unexpected Behavior  

### ISSUE THREAD

**Issue by koptan** [layerhq/Atlas-iOS#1017]
Hi , 

I am using ATLConversationViewController with NavigationViewController and if every thing look fine .

But when i am trying to close the ATLConversationViewController by sliding from left to right i am seeing a copy of keyboard is moving by him self to the right !!! .

If i am closing the ATLConversationViewController from "Back" button in NavigationViewController bar every think look fine .

I am using Ios9 - iPhone 6 .

Thank you

**Comment by kmahal** [comment]
Hi @koptan a fix was merged here: https://github.com/layerhq/Atlas-iOS/pull/1018

**Comment by koptan** [comment]
@kmahal  thank you .
