### ISSUE TITLE
show image in fullscreen

### ISSUE THREAD

**Issue by haemi** [layerhq/Atlas-iOS#1021]
is it possible to tap on a sent/received image to display it in fullscreen mode?

**Comment by maju6406** [comment]
Atlas lets you know if the image/cell was selected. It's then up to you to show the fullscreen dialog. Check out the `ATLMMediaViewController` used by Atlas-Messenger
https://github.com/layerhq/Atlas-Messenger-iOS/blob/master/Code/Controllers/ATLMConversationViewController.m#L225
