### ISSUE TITLE
Build Error: LayerKit 0.17.0 Atlas 1.0.13 Xode 7

### ISSUE THREAD

**Issue by cashmash** [layerhq/Atlas-iOS#1023]
Getting this error since update:
- LayerKit 0.17.0
- Atlas 1.0.13
- integrated manually (not pods)
- XCode 7

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ATLPlayView", referenced from:
      objc-class-ref in ATLMessageBubbleView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any suggestions?
reinstalled, cleaned, rebuild -> doesn't seem to solve.

**Comment by maju6406** [comment]
We might need to take a look at your project. Can you email it to support@layer.com? Reference this github issue.

**Comment by cashmash** [comment]
my mistake, sorry, somehow the ATLPlayView.h and ATLPlayView.m where not added to the project while copying the folder -> no issue
