### ISSUE TITLE
ATLConversationViewController doesn't show the messageInputToolbar

### ISSUE THREAD

**Issue by MrMonkeyBrains** [layerhq/Atlas-iOS#1024]
I can't seem to get ATLConversationViewController to work. I've subclassed it myself and also tried the SampleConversationViewController with the same results.

Problem #1: When the view loads, the messageInputToolbar isn't displayed unless user scrolls up. After the user scrolls up, the messageInputToolbar is docked to the bottom of the view as expected.

~~Problem #2: User taps into field, keyboard and messageInputToolbar slide up as expected... swipe down to hide keyboard. The messageInputToolbar docks to the bottom of the view again (as expected) briefly then animates up about 50-60 pixels from the bottom of the view.~~ **Fixed by disabling IQKeyboardManager via:**

```[[IQKeyboardManager sharedManager] disableInViewControllerClass:[ConversationViewController class]];```

![out](https://cloud.githubusercontent.com/assets/15152228/10533809/4259e7c6-7383-11e5-90ee-d2b41a475b4d.gif)

Any advice/suggestions/help is appreciated.

**Comment by kmahal** [comment]
@MrMonkeyBrains is this occurring in the sample app in the Atlas project?   We are unable to reproduce.  Check your project for configuration issues.  Are you using an external keyboard?  As Atlas is open sourced, dig into the code and see what is setting the frame incorrectly, and feel free to submit a PR.

**Comment by MrMonkeyBrains** [comment]
Been trying to figure it out... I'm not an Obj-C expert.

Not using an external keyboard. Same result in the simulator and device. 

Any chance you can point me to the right place in the code where I might start digging regarding where the initial location of the messageInputToolbar frame is located -- I couldn't find that in the code?

**Comment by MrMonkeyBrains** [comment]
@kmahal the sample app in the other repo doesn't work -- https://github.com/layerhq/Atlas-Messenger-iOS/issues/199 (few folks having trouble)

**Comment by MrMonkeyBrains** [comment]
May be related to https://github.com/layerhq/Atlas-iOS/issues/912 as there are some errie similarities and I'm also using a UITabBarController with the conversation view as the first tab

**Comment by MrMonkeyBrains** [comment]
Problem #2 - the bouncing on keyboard dismiss - is solved by this: https://github.com/layerhq/Atlas-iOS/issues/1020


Still fighting through Problem #1

**Comment by MrMonkeyBrains** [comment]
Appears to be an issue with UIPageViewController. Replaced with this drop-in replacement and things seem to be working: https://gist.github.com/paul-delange/5582394
