### ISSUE TITLE
App crash because failed to locate resources.bundle

### ISSUE THREAD

**Issue by cashmash** [layerhq/Atlas-iOS#1026]
Hi,

so Layer + Atlas worked fine (iOS8+9, XCode 7, installed manually, not as a pod).
I updated to the newest Atlas + Layer versions.
When I switch from the ConversationListView to the ConversationView I get the following error:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to locate `resources.bundle` in (null)'

crashing at:
ATLMessagingUtilities.m 318
if (!resourcesBundle) [NSException raise:NSInternalInconsistencyException format:@"Failed to locate `resources.bundle` in %@", resourcesBundle];

Did I miss something with updating?

**Comment by maju6406** [comment]
Are you using the latest Atlas code? It looks like files are missing.

**Comment by cashmash** [comment]
using the latest, and copied the "Code" and "Resources" folder

**Comment by JeanLebrument** [comment]
Same problem here. @cashmash @maju6406

**Comment by yuanjinhai** [comment]
Same problem here, how can I fix it???

**Comment by immexerxez** [comment]
Also have this problem, I`m assuming it just can`t find the resources folder in the project ?

**Comment by immexerxez** [comment]
I wouldn`t recommend this but If you just remove ATLMessagingUtilities.m 318, it works just fine. just did it built and ran perfect

**Comment by alhill10** [comment]
having the same issue here, any fixes?

**Comment by wzfcooler** [comment]
any proper fix??

**Comment by Mortenest** [comment]
Same here, @maju6406 please reopen this issue

**Comment by mike-companyons** [comment]
This still happens on the latest build, why was it closed?

**Comment by mike-maws** [comment]
Why is this closed?, app still fails on the latest code.

**Comment by mike-maws** [comment]
A way to fix it is to create a folder, name it AtlasResource.bundle, copy atlas resources folder contents into it, and add the bundle to your app. Atlas runs apparently fine afterwards.

**Comment by petec029** [comment]
I just did a pod update and now I am running into this same error message when on my ConversationListView

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to locate resources.bundle in (null)'

**Comment by charleswlee** [comment]
I also had to create and copy AtlasResource.bundle into the app bundle
