### ISSUE TITLE
dyld: Library not loaded: @rpath/LayerKit.framework/LayerKit

### ISSUE THREAD

**Issue by jantos** [layerhq/Atlas-iOS#1030]
After running pod update the following error occurs when I run the app in the 6s simulator:

dyld: Library not loaded: @rpath/LayerKit.framework/LayerKit
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/4A0F5D59-E165-4258-AD9A-3B45B63660F9/data/Containers/Bundle/Application/BE97F76D-67A8-45AC-B668-51C40D5B5B6E/Layer-Parse-iOS-Example.app/Layer-Parse-iOS-Example
  Reason: image not found

pod update command:
Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Downloading dependencies
Using Atlas (1.0.13)
Using Bolts (1.3.0)
Using LayerKit (0.17.0)
Using Parse (1.9.0)
Using ParseUI (1.1.6)
Using SVProgressHUD (1.1.3)
Generating Pods project
Integrating client project
Sending stats
Sending stats

I am using xcode 7, ios sdk 9, deployment target 8.0.

If I change the deployment target to 7.0 and run pod update which changes to Layerkit 0.16.0 and Atlas 1.0.11 the app works fine. As soon as I change it back to deployment target 8.0, run pod update which installs latest Layerkit 0.17.0 and Atlas 1.0.13 the above (Image not found) error occurs and the app crashes on launch.

**Comment by MatthewAnthonyBordas** [comment]
I faced this problem to. I fixed it with a combination of:
1) Target -> Build Settings -> Search Paths: Add "@executable_path/Frameworks"
2) Target -> Build Settings -> User Header Search Paths: Add "Pods/** - recursive"

**Comment by hschmied** [comment]
Same problem here. Happened after updating...
- LayerKit from 0.16.0 > 0.17.0
- Atlas from 1.0.11 > 1.0.13

Matthew's fix didn't work for me.

**Comment by hoan** [comment]
I have the same issue, even with Matthew's fix, using the latest Atlas & LayerKit, targeting 8.0

**Comment by EvgenKor** [comment]
+1

Same issue. LayerKit was installed manually (without CocoaPods).
xCode 7.0.1, iOS SDK 9.0, deployment target 8.0 (was 7.0, but LayerKit require 8.0)

**Comment by EvgenKor** [comment]
Hey, I found solution for my issue! Try to add "@executable_path/Frameworks" to the "Runpath Search Path" property at Build settings.

Sorry for my bad English :)

**Comment by hoan** [comment]
I already have that in my "Runpath Search Path", still not working :(

I'm also using Xcode 7.0.1, iOS SDK 9.0, deploying to iOS 8.0

:(

**Comment by kmahal** [comment]
@hoan what version of cocoapods are you using?  You must be on `0.39.0` or newer.

**Comment by maju6406** [comment]
This may help:
https://support.layer.com/hc/en-us/articles/206166713-I-m-getting-a-Reason-image-not-found-error-when-I-run-my-app-What-s-happening-

Long story short, if you're running cocoapods, you need to make sure you're running v0.39 or higher. If you're not running cocoapods, there's a new build "Copy File Phase to Build Phases" step described here

https://support.layer.com/hc/en-us/articles/204256740-Can-I-use-LayerKit-without-Cocoapods-

**Comment by hoan** [comment]
I'm on 0.38.2. When I upgrade to 0.39.0, it fucks up the AWS pod :(

I will try the other method you have linked! Thanks!

**Comment by hoan** [comment]
It has worked so far where the dydl doesn't fail

However having an issue with the resources when I try to load a conversation view controller:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to locate `resources.bundle` in (null)'

Almost there, thanks for the help

**Comment by hoan** [comment]
Ok that resources.bundle was because I was adding Atlas manually..

**Comment by jantos** [comment]
After upgrading cocoapods to 0.39.0 I am still encountering the same issue. I also added the other suggestions from above, but no luck so far.

**Comment by jantos** [comment]
The only way how everything works for me at the end is if I follow the last step (Add Copy File Phase to Build Phases) from this link https://support.layer.com/hc/en-us/articles/204256740-Can-I-use-LayerKit-without-Cocoapods-.
