### ISSUE TITLE
Placeholder label being removed on presentation ios 9: ConversationViewController

### ISSUE THREAD

**Issue by MatthewAnthonyBordas** [layerhq/Atlas-iOS#1031]
![atlaserror](https://cloud.githubusercontent.com/assets/7369954/10567224/4a5aba14-75b2-11e5-99ea-14b374d1e89b.gif)

The first time the ConversationViewController is presented the UI looks perfect, then from the second time that view controlled is presented and onwards the placeholder label, that is a subview of ATLComposeTextView, that says "Enter Message" keeps disappearing and reappearing on presentation. This only started happening on ios 9. I dug deep into the source code but was unsuccessful in pin pointing the bug. Thank you

**Comment by kmahal** [comment]
@MatthewAnthonyBordas we've seen this issue in ios8 and before as well.  Thanks for noting.

**Comment by MatthewAnthonyBordas** [comment]
Where can I override that functionality to allow the label to be drawn sooner?

**Comment by kcoleman731** [comment]
@MatthewAnthonyBordas You can't. The message composer is set as the `inputAccessoryView` for the controller's view. It has some very strange undocumented behavior is iOS8 which we have tried to deal with a few times. The toolbar gets set as the view in `viewDidLoad` and the text is set in the toolbars `init` method. 

If you want to try tackling this yourself, feel free have a look at the `ATLMessageInputToolbar`.

**Comment by MatthewAnthonyBordas** [comment]
Dang ok thank you! I will try haha
