### ISSUE TITLE
Include of non-modular header inside framework module 'Atlas.ATLConversationViewController'

### ISSUE THREAD

**Issue by KristopherGBaker** [layerhq/Atlas-iOS#1037]
I'm getting the following error:
.../Pods/Atlas/Code/Controllers/ATLConversationListViewController.h:23:9: Include of non-modular header inside framework module 'Atlas.ATLConversationListViewController'

I'm using Xcode 7.1, CocoaPods 0.39 with frameworks enabled (use_frameworks!), and it's a Swift iOS project.

This is the Podfile:
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'LayerKit'
pod 'Atlas'

I fixed it in my project by modifying ATLConversationListViewController.h so it includes Layer with
```objectivec
@import LayerKit; // replaces #import <LayerKit/LayerKit.h>
```

I tried changing the "Allow Non-modular Includes In Framework Modules" setting to Yes, but that didn't fix the error (only changing the import fixed the error).

**Comment by haemi** [comment]
do you have a bridging header file as well? If yes, how does it look like?

**Comment by KristopherGBaker** [comment]
No bridging header.  I first ran into this issue yesterday after upgrading to Xcode 7.1 and trying to run my main project (which does have a bridging header along with other pods).  To try and pinpoint the issue, I created a new Xcode project with only LayerKit, Atlas, and Realm in my Podfile (and no bridging header).  In the default ViewController that was created with the new project, I added
```swift
import LayerKit
import Realm
import Atlas
```
I continued to get errors until I added the import in ATLConversationListViewController.h.  I created an example project at https://github.com/KristopherGBaker/LayerTest that reproduces the error if you follow the instructions in the readme.  

Also, unlike my previous comment, it appears that the ```@import LayerKit;``` is needed in just one of the header files (doesn't have to be ATLConversationListViewController.h specifically, and ```#import <LayerKit/LayerKit.h>``` doesn't need to be removed).

**Comment by chenyuan** [comment]
same issue here. i created a simple project with Xcode 7.1 https://github.com/layerhq/Atlas-iOS. Bridging header file is included, but doesn't help.

Using same Podfile in a objc project has no issue though.

**Comment by KristopherGBaker** [comment]
This issue may be related to https://github.com/CocoaPods/CocoaPods/issues/4420

**Comment by kmahal** [comment]
@KristopherGBaker try taking `LayerKit` out of your Podfile.  `Atlas` has a `LayerKit` dependency and installs it directly.  Additionally, with the `0.17.0` `LayerKit` release on Atlas `1.0.13` the libraries are built as dynamic frameworks, no longer static which can cause some of these issues.  Try a fresh pod file install and let us know how it goes.

**Comment by chenyuan** [comment]
@kmahal thanks for pointing out some advices, I tried what you said (https://github.com/chenyuan/AtlasSwift), but I'm still getting errors like: 
Include of non-modular header inside framework  module 'Atlas.ATLConversationListViewController'...

@KristopherGBaker how did you go with your fixing? i know it's open sourced we can't ask too much, but it's just a bit frustrating

**Comment by KristopherGBaker** [comment]
@chenyuan I just modified the version of ATLConversationListViewController.h installed by cocoapods into my workspace/project so it includes ```@import LayerKit;``` (requires unlocking the file).  This works for me for now.  I think the underlying issue is with the CocoaPods issue I referenced earlier.

**Comment by KristopherGBaker** [comment]
@kmahal I still get the same issue after removing LayerKit from my Podfile and doing a fresh pod install.  My guess is that the issue will end up getting fixed with CocoaPods #4420.

@chenyuan I created a separate branch that shows what I'm doing to get around the issue for now.  https://github.com/KristopherGBaker/LayerTest/tree/working-import - in particular, see
https://github.com/KristopherGBaker/LayerTest/blob/working-import/Pods/Atlas/Code/Atlas.h#L27

**Comment by blakewatters** [comment]
@KristopherGBaker @chenyuan Can you try `pod ‘Atlas’, :head` in your Podfile? I have switch to `@import LayerKit;` statements on master and I’m no longer seeing build issues. If you can sanity check my work we’ll look at getting a tagged release pushed asap

**Comment by KristopherGBaker** [comment]
@blakewatters ```pod ‘Atlas’, :head``` works for me with no build issues.

**Comment by blakewatters** [comment]
:boom:

**Comment by blakewatters** [comment]
Fixed in Atlas v1.0.14

**Comment by chenyuan** [comment]
all good now, thanks a lot guys.

**Comment by bradytate** [comment]
1.0.14 Seems to cause build errors for me whereas 1.0.13 did not. Opposite of the problem described above. Does Layer/Atlas need to be included in the bridging header even if they are not used with any swift classes?
