### ISSUE TITLE
Error "Module LayerKit not found" after upgrading to Atlas 1.0.14 & LayerKit 0.17.0

### ISSUE THREAD

**Issue by dippigu** [layerhq/Atlas-iOS#1044]
After performing a pod update and updating to Atlas 1.0.14 & LayerKit 0.17.0, using Xcode 7.1, I am seeing error "Module LayerKit not found" on line 22 of ATLMessagingUtilities.h, <code>@import LayerKit;</code>

Same error in Xcode 6.4, and Xcode 7.2B.

**Comment by MatthewAnthonyBordas** [comment]
I am having the same issue!

**Comment by bradytate** [comment]
I am also having this issue. For the time being I have adjusted the podfile like this: 
`pod 'Atlas', '< 1.0.14'`
This is only temporary for now until I can figure out why v1.0.14 causes build errors.

**Comment by emkman** [comment]
Same problem. Possibly a continuation of https://github.com/layerhq/Atlas-iOS/issues/1014?

**Comment by piotrbernad** [comment]
+1

**Comment by DmitryBulaienko** [comment]
just put  **use_frameworks!** to the top of your podfile.
'LayerKit 0.17.0 introduces support for distributing LayerKit as a dynamic framework' - from here 
https://developer.layer.com/docs/ios/changelog

**Comment by DmitryBulaienko** [comment]
the one thing that's really frustrating me is that **use_frameworks!** can't be applied just for one concrete pod.

**Comment by bradytate** [comment]
`use_frameworks!` at the top of the podfile does not resolve this issue for us.

**Comment by dippigu** [comment]
use_frameworks! doesn't resolve for me, either.

I've had to roll back to 1.0.13 for now to continue development. 
@kmahal any comment or update on this issue, please?

**Comment by emkman** [comment]
is use_frameworks! even an appropriate option if we aren't using swift?

**Comment by kcoleman731** [comment]
@dippigu @bradytate adding `use_frameworks!` to your podfile should resolve this issue. 

Unfortunately, switching from static to dynamic frameworks with CocoaPods has created some issues projects. Would you mind doing a `pod deintegrate` ((info on adding this command here)[https://github.com/CocoaPods/cocoapods-deintegrate] ) and then `pod install` with `use_frameworks!`?

Let me know if that solves your issue.

**Comment by kcoleman731** [comment]
@emkman yes it is an appropriate option. It simply tells cocoapods that you want all of your deps to be built as dynamic frameworks.

**Comment by jeffdgr8** [comment]
@kcoleman731 Unfortunately `use_frameworks!` does not work in our case. It makes no difference. I tried `pod deintegrate` and then `pod install` and it made no difference. I don't know if it has anything to do with the fact that we have 14 other pods in our podfile. But clearly the issue is not resolvable with this workaround for everyone.

**Comment by nishantdongare** [comment]
+1

**Comment by kmahal** [comment]
HI @jeffdgr8 can you show us a copy of your `Podfile`?  With more information we can dig into this issue and get it resolved.

**Comment by blakewatters** [comment]
We believe that the problem here was addressed with LayerKit v0.17.1 but the Atlas podspec was not updated to depend on that specific version. Can you try updating to Atlas v1.0.15 (which I just pushed to CocoaPods to see if that straightens things out)?

**Comment by jeffdgr8** [comment]
@blakewatters v1.0.15 has the same issue. We are adding the LayerKit pod explicitly and had already been using v0.17.1.

@kmahal this is our Podfile:

```source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'AFNetworking', '< 2.0.0-RC1'
pod 'RMUniversalAlert'
pod 'MSCollectionViewCalendarLayout'
pod 'Masonry'
pod 'UIColor-HexString'
pod 'CHCSVParser', :git => 'https://github.com/davedelong/CHCSVParser.git', :inhibit_warnings => true
pod 'Fingertips'
pod 'LayerKit'
pod 'Atlas'
pod 'libPhoneNumber-iOS'
pod 'OCMock'
pod 'CupertinoYankee'
pod 'CustomBadge'
pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
```

**Comment by jeffdgr8** [comment]
Not sure if it matters, but our project consists of both Objective-C and Swift code.

**Comment by edwardmarks** [comment]
@jeffdgr8 @dippigu 

I ran into this issue and I solved it by updating Cocoapods (`gem update cocoapods`) and running `pod update`. I was on version 0.38.0 and the latest 0.39.0 fixed my issue.

**Comment by jeffdgr8** [comment]
@edwardmarks I'm on version 0.39.0 already. Thanks.

**Comment by immexerxez** [comment]
anything new about this? still having this issue tried all the work arounds so far but haven`t gotten a single one to work.

**Comment by cshah3** [comment]
Issue still exists on v1.0.15.

**Comment by EpicDraws** [comment]
Also blocked by this issue. Can't get LayerKit and Atlas to play nicely together.

**Comment by magneticorb** [comment]
Also having this issue after an update. Using Cocoapods 0.39.0, trying to get to the latest version of Atlas and LayerKit. Objective C project. Any progress on this one @blakewatters?

**Comment by jeffdgr8** [comment]
For those having this issue and using a mix of Objective-C and Swift code, the solution we discovered was to `#import <Atlas/Atlas.h>` at the top of your project-Bridging-Header.h. The issue stemmed from a problem with the build tools where swift code that referenced Objective-C code that imported the Atlas library causes this compilation error. So the Atlas library needs to be imported before the code that references the Objective-C code that references the Atlas code.

Also note, `#import <Atlas/Atlas.h>` resolves the issue, but `@import Atlas;` causes a "property has previous declaration" compilation error. Additionally adding `@import LayerKit;` resolves this issue. Otherwise using `#import` is needed.

**Comment by blakewatters** [comment]
Thanks @jeffdgr8. I'm going to close out this issue as there's not much more that we can do at the library level to handle this. Every instance of this has been solvable by messing around with the import order within the integrating project. This is just pain from the still immature tooling in the Swift world.

**Comment by emkman** [comment]
@blakewatters Just to be clear, I had this issue and am not using any Swift.

**Comment by magneticorb** [comment]
Also not using swift. I managed to get up and running by replacing the @import statements with #import statements (in the Atlas project itself!)

**Comment by williamtwilson** [comment]
@magneticorb's workaround was the only one that worked for me. Any updates incoming?

**Comment by nsantorello** [comment]
I was able to get it working by forking and making the changes suggested by @magneticorb: https://github.com/SeedDev/Atlas-iOS/commit/7125022f668a00bca49b8ec1e27dcf015d61e7b3

Then I edited my Podfile:
```
  pod 'LayerKit', '0.19.1'
  pod 'Atlas', :git => 'git@github.com:SeedDev/Atlas-iOS.git'
```
