### ISSUE TITLE
ATLParticipantTableViewController: Selected cells are gone after user utilizes search

### ISSUE THREAD

**Issue by Kfoury** [layerhq/Atlas-iOS#1045]
Hi,
I'm presenting ATLParticipantTableViewController for the user to pick participants to start a new conversation. I'm implementing the search and the didSelectParticipant delegate methods. Everything works fine.
The problem arises when the user selects one or more cells (cells become highlighted) after which the user utilized the ATLParticipantTableViewController search tool. Once the user exists the search mode, the tableViewController reloads and all the highlights are lost.

I've looked at the code of ATLParticipantTableViewController and it seems that the in the implementation  of the configureCellAtIndexPath method there is nothing that preserves the highlighting of the cells (i mean a check to see if the cell belongs to the selected stack).

I tried to sub class but the methods related to the issue are private so things become tricky.
Any help would be appreciated.

Thank You,
-Fadi

**Comment by kcoleman731** [comment]
Hi @Kfoury. I just tested this out myself. I can successfully select multiple cells, search, cancel, and cell selections remain in tact. 

Is there something else your code might be doing that could force a table view reload?

**Comment by kmahal** [comment]
@Kfoury any updates on this item?  If not I'll close this ticket out.

**Comment by Kfoury** [comment]
@kcoleman731 Thanks for your reply @kmahal Apologies of the late reply. I lost the files of the project involving the problem that i was working on. The problem might be that I wasn't using the latest repo. Since I'm busy now, it is gonna take me a while to re-construct the problem. Will update the post if the problem persisted.

**Comment by Kfoury** [comment]
@kcoleman731 it seems that the problem arises only after you search and select a user during search mode. I have attached a gif that shows the scenario that I'm talking about.
![bug_participant_view](https://cloud.githubusercontent.com/assets/8665414/11760818/54e42f1a-a05f-11e5-9609-80d4a799938d.gif)
