### ISSUE TITLE
Fast entry causes crash

### ISSUE THREAD

**Issue by Stakenborg** [layerhq/Atlas-iOS#1046]
ATLConversationViewController.m line 1200
    -[ATLConversationViewController queryControllerDidChangeContent:]

We're noticing in our app that fast data entry can cause crashes on Atlas.

Something similar to the following:

    Fatal Exception: NSInternalInconsistencyException
    Invalid update: invalid number of sections. The number of sections contained in the collection view    
    after the update (6) must be equal to the number of sections contained in the collection view before the
    update (6), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).

We're causing this via a button that generates and sends text. Pretty minor, but it should probably be known.

**Comment by cashmash** [comment]
same:
1) share location
2) type couple texts and click send 
3) send image

If you do it fast enough sometimes it crashes.

**Comment by kmahal** [comment]
@Stakenborg we're looking into this and will get back to you.

**Comment by DevMoz** [comment]
+1 Noticing this same crash immediately when app becomes active. Same line number.

**Comment by kmahal** [comment]
@Stakenborg we have a fix for this coming out in our next `LayerKit` point release.

**Comment by kmahal** [comment]
@Stakenborg Layerkit `0.17.2` has been released.  Please upgrade your `LayerKit` to this version and let me know if you are still running into this issue.

**Comment by Stakenborg** [comment]
Unfortunately I can't get the newest update to work for a variety of issues, one related to [#1014](https://github.com/layerhq/Atlas-iOS/issues/1044). Some of my pods don't support `use_frameworks!` properly, and if I don't use that, newer versions of Atlas won't build, so I'm just using an older version until I find a way to deal with it.

**Comment by DevMoz** [comment]
@kmahal this seems to have resolved the issue for my implementation at least. Thanks!!

**Comment by kmahal** [comment]
@Stakenborg you can also manually install `Atlas` by downloading the latest version from master and dragging the files into your project.  I'm going to close this issue out for now since it's improved for you @DevMoz thanks.
