### ISSUE TITLE
Video and Images: Issues and Featurerequests

### ISSUE THREAD

**Issue by cashmash** [layerhq/Atlas-iOS#1047]
Just to keep it on notice:

1) Issue: Videos can be sent but not played
2) Feature request: add option to choose between image support or video support or both (pull request?), right now it has both by default
3) Feature request: add imageviewer: image cannot be viewed right now (pull request?)

**Comment by kmahal** [comment]
@cashmash 1 and 3 are features your application should handle, not Atlas.  Look at the Atlas Messenger project for examples.  For 2, feel free to submit a pull request for this.

**Comment by cashmash** [comment]
ahh thx @kmahal
