### ISSUE TITLE
Add Gif sending support

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1048]
If I understand right, the service does not support it. Correct me if I'm worng.

For example, I tried to send a gif using the iOS keyboard PopKey + GIF Keyboard (https://itunes.apple.com/us/app/popkey-animated-gif-keyboard/id919359310), but if failed even to paste it in the input view.

GIF becomes more and more popular - I think it's very important to add this support.

**Comment by kmahal** [comment]
@oferRounds atlas supports sending GIFs by default already. https://github.com/layerhq/Atlas-iOS/blob/master/Code/Views/ATLMessageCollectionViewCell.m#L141

**Comment by oferRounds** [comment]
@kmahal thanks for your answer. Questions: have you tried to use one of the iOS GIF keyboard with Atlas? Because, as I said, it doesn't work (at least for me). Tested it with: iOS keyboard PopKey + GIF Keyboard.

**Comment by oferRounds** [comment]
@kmahal?

**Comment by kmahal** [comment]
@oferRounds we have not, internally.  The encoding and media type at hand is important.  Check out `ATLMediaAttachment` to see how we create a GIF (and how they are stored as UIImage references).  Feel free to submit a PR for a fix, but we wouldn't accept a 3rd party library specific implementation.  That would be best kept to your own fork.
