### ISSUE TITLE
refresh participants list in ATLParticipantTableViewController

### ISSUE THREAD

**Issue by sara-shokry** [layerhq/Atlas-iOS#1049]
I can't use refresh control to refresh participants list after view presented.
 reason: 'Cannot change participants after view has been presented'
So if user want to refresh or update his list should leave screen!!!!

**Comment by kmahal** [comment]
@sara-shokry Atlas is modeled after iMessage behavior.  The participant list must be known before presenting the controller, which the application can do by pre-fetching before presenting the controller.
