### ISSUE TITLE
Adding Activity indicator when pressed on location button

### ISSUE THREAD

**Issue by koptan** [layerhq/Atlas-iOS#1053]
it's taking around 5 sec to add location cell in Collection view .

So the user is thinking is not working so he is keep pressing, so kindly please can you add Activity Indicator when user pressed on location button .

**Comment by kmahal** [comment]
@koptan feel free to submit a pull request for a feature you'd like to see.  We wouldn't want to add an activity indicator to the right accessory button as it does not mimic iMessage functionality and feeling.  You can manually prevent messages from being sent by implementing the delegate `conversationViewController:messagesForMediaAttachments:` and checking for the case when someone is sending location messages repeatedly within an interval.  You can also subclass the `ATLMessageInputToolbar` to give the desired effect you'd like to see.

**Comment by JRam13** [comment]
To be fair, this functionality in no way mimics iMessage. In iMessage, you have to navigate out of chat, guaranteeing you only tap that button once. However, I understand this is low priority for you guys.

Should be reconsidered nonetheless.

**Comment by JRam13** [comment]
@koptan You can disable the button when first tapped, re-enabling it after the message is sent. Again, not ideal, but should work.
