### ISSUE TITLE
Line height is too short for emoji

### ISSUE THREAD

**Issue by marcshilling** [layerhq/Atlas-iOS#1058]
I noticed the tops of my emoji messages are getting cut off:

![Image](http://i.imgur.com/KRs5QQR.png)

--

I am setting a custom font for my messages using the appearance protocol, like so:

```objectivec
[[ATLOutgoingMessageCollectionViewCell appearance] setMessageTextFont:[UIFont fontWithName:@"ProximaNova-Regular" size:18]];
```

This is also an issue on the ConversationListViewController:
![Image2](http://i.imgur.com/akijWPY.png)

**Comment by kmahal** [comment]
@marcshilling let's run through a few possible issues here.

1. Confirm in this `ATLMessageCollectionViewCell` method that the correct font is being used for sizing from the ui appearance selector.
```objc
+ (CGSize)cellSizeForTextMessage:(LYRMessage *)message inView:(id)view
{
    if ([[self sharedHeightCache] objectForKey:message.identifier]) {
        return [[[self sharedHeightCache] objectForKey:message.identifier] CGSizeValue];
    }
    //  Adding  the view to the hierarchy so that UIAppearance property values will be set based on containment.
    ATLMessageCollectionViewCell *cell = [self sharedCell];
    if (![view viewWithTag:kATLSharedCellTag]) {
        [view addSubview:cell];
    }
    
    LYRMessagePart *part = message.parts.firstObject;
    NSString *text = [[NSString alloc] initWithData:part.data encoding:NSUTF8StringEncoding];
    UIFont *font = [[[self class] appearance] messageTextFont];
    if (!font) {
        font = cell.messageTextFont;
    }
    CGSize size = ATLTextPlainSize(text, font);
    size.width += ATLMessageBubbleLabelHorizontalPadding * 2 + ATLMessageBubbleLabelWidthMargin;
    size.height += ATLMessageBubbleLabelVerticalPadding * 2;
    if (![[self sharedHeightCache] objectForKey:message.identifier]) {
        [[self sharedHeightCache] setObject:[NSValue valueWithCGSize:size] forKey:message.identifier];
    }
    return size;
}
```
2. Confirm if it works for you correctly with default font type.
3. Look into this article: http://www.andyyardley.com/2012/04/24/custom-ios-fonts-and-how-to-fix-the-vertical-position-problem/.  (Another way to verify this is to see if a non-custom but different default font has this problem.  If a non-custom default font works fine then it could be the specific font used).

**Comment by marcshilling** [comment]
You're right, appears to just be a problem with my specific font (ProximaNova). Default typeface does not cut them off.

**Comment by abhinavsingi** [comment]
@marcshilling How did you fix your specific font( ProximaNova ) issue? Did you change the font or just used some other font?

**Comment by marcshilling** [comment]
@abhinavsingi never fixed...ended up just using the default font
