### ISSUE TITLE
Timestamp formatting

### ISSUE THREAD

**Issue by deepakbharanikana** [layerhq/Atlas-iOS#1059]
"We are using query controller to display messages. Following is the code:

    LYRQuery *query = [LYRQuery queryWithQueryableClass:[LYRMessage class]];

    query.predicate = [LYRPredicate predicateWithProperty:@"conversation" 
                       predicateOperator:LYRPredicateOperatorIsEqualTo            
                       value:self.conversation];

    query.sortDescriptors = @[ [NSSortDescriptor sortDescriptorWithKey:@"position" 
                                ascending:YES]];
    LYRQuery *query = [LYRQuery queryWithQueryableClass:[LYRMessage class]];
    query.predicate = [LYRPredicate predicateWithProperty:@"conversation" 
                       predicateOperator:LYRPredicateOperatorIsEqualTo            
                       value:self.conversation];
    query.sortDescriptors = @[ [NSSortDescriptor sortDescriptorWithKey:@"position" 
                                ascending:YES]];
 We need to display a section in tableview using queryController which is used to  display dates(We want to create a new section for each date). To achieve this, may be section wise data will be helpful then. Could you please help us fix this? Is it possible to get data in "group by date" using LYRQueryController?"

**Comment by kmahal** [comment]
@deepakbharanikana did you accidentally paste the same code twice?

Regardless, our timestamps are grouped by setting the property:
```objc
/**
 @abstract The time interval at which message dates should be displayed in seconds. Default is 60 minutes meaning that
 dates will appear centered above a message only if the previous message was sent over 60 minutes ago.
 */
@property (nonatomic) NSTimeInterval dateDisplayTimeInterval;
```
which currently is defaulted to 60 minutes.  If you would like the functionality to ONLY display a timestamp on each new day then feel free to submit a pull request for this feature.
