### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by DevMoz** [layerhq/Atlas-iOS#1061]
When testing my app, I'll receive a push notification to my device for a new message. I then open the app (which was either running in the background or in suspended state) but the new message does not synchronize and is not visible in the conversation. The only way to view the new message is to force kill the app then launch it again. I've noticed this on my own device and so has one of my test users. I'm using the latest versions of both LayerKit and Atlas.

**Comment by DevMoz** [comment]
Probably worth mentioning I only seem to notice this behaviour in a conversation that has quite a large number of messages associated with it. For smaller conversations, the message takes a few seconds to appear but it eventually does. For the larger conversations, I can't get some messages to appear unless I force quit / re-launch.

**Comment by JRam13** [comment]
@DevMoz I noticed the same thing with older versions of LayerKit, it has since improved. 

One thing that I do (might or might not help you) is check if the layerclient is connected. Sometimes, for some reason, it automatically disconnects. You should check like so:

```
if (![LayerHandler sharedInstance].layerClient.isConnected) { 
     //connect
}
```
Connection is not the same as authorized. A user can be authorized, but not connected (won't receive chat messages). I don't know if Atlas has a built in mechanism for this, but I put this code whenever I present my chatview (viewWill/DidAppear).

**Comment by DevMoz** [comment]
Thanks for the tip @JRam13 .  I'm using the latest LayerKit and I did try this exact solution (except I checked the connection in applicationDidBecomeActive). It didn't really solve the problem for me though. I'll admit, this issue doesn't show up very often. 

What is a bit more frustrating (and frequent) is what I can only assume has to do with the sync speed. I can be on good wifi and if I receive a push notification letting me know about a new message, I'll open up the app and it usually takes several seconds for the message to appear on screen. It makes the app feel very laggy and unresponsive. Have you experienced anything similar?

**Comment by JRam13** [comment]
@DevMoz I have noticed the delay. However, I mitigate it by showing my notification screen when the app is opened from a push, that gives Layer enough time to synchronize. Sometimes if I click on the chat fast enough, I'll have to wait a second or two in order for the new messages to appear.

**Comment by kmahal** [comment]
@DevMoz you must call `- (BOOL)synchronizeWithRemoteNotification:(NSDictionary *)userInfo completion:(void(^)(NSArray *changes, NSError *error))completion;` to let the client synchronize with the remote notification and that will give you the changes on completion that can guarantee everything is up to date.  This is not an Atlas problem but a `LayerKit` question so I will be closing this.
