### ISSUE TITLE
ATLMediaInputStream.m Memory Leak warnings

### ISSUE THREAD

**Issue by lkraider** [layerhq/Atlas-iOS#1062]
Running clang static analyzer on commit  ae57367 (master HEAD as of today), 5 potential leaks are signaled in `ATLMediaInputStream.m`. Below are links to the reports

1. [report-354f84](https://cdn.rawgit.com/lkraider/6246a5b8359dd89e027d/raw/e4c42783c401e3b676a41cf578a854b8f6e22a7f/report-354f84.html#EndPath) - Potential leak of an object
1. [report-b8a95f](https://cdn.rawgit.com/lkraider/6246a5b8359dd89e027d/raw/e4c42783c401e3b676a41cf578a854b8f6e22a7f/report-b8a95f.html#EndPath) - Potential leak of an object stored into 'fileUTI'
1. [report-0ed362](https://cdn.rawgit.com/lkraider/6246a5b8359dd89e027d/raw/e4c42783c401e3b676a41cf578a854b8f6e22a7f/report-0ed362.html#EndPath) - Potential leak of an object stored into 'fileUTI'
1. [report-484857](https://cdn.rawgit.com/lkraider/6246a5b8359dd89e027d/raw/e4c42783c401e3b676a41cf578a854b8f6e22a7f/report-484857.html#EndPath) - Potential leak of an object
1. [report-9660a2](https://cdn.rawgit.com/lkraider/6246a5b8359dd89e027d/raw/e4c42783c401e3b676a41cf578a854b8f6e22a7f/report-9660a2.html#EndPath) - Potential leak of memory pointed to by 'buffer'

**Comment by kmahal** [comment]
Thanks for these, we've had a look.

**Comment by lkraider** [comment]
Is it fixed on master?
