### ISSUE TITLE
Fetch all ID partecipants sender

### ISSUE THREAD

**Issue by devloopers** [layerhq/Atlas-iOS#1063]
Hi, 
how do i get all the id of the sender?
Thanks

**Comment by kmahal** [comment]
@devloopers It's unclear what you are requesting but this is not an Atlas specific question.  Every `LYRMessage` object has an `LYRActor *` sender object which signifies the `userID` of the sender.  Atlas requests `conversationViewController:participantForIdentifier` which asks for an object that implements the `ATLParticipant` protocol for a specific `userID`.
