### ISSUE TITLE
Problem with setting displaysRightAccessoryImage false

### ISSUE THREAD

**Issue by troypayne** [layerhq/Atlas-iOS#1065]
I think there's a bug with the flag:
ATLMessageInputToolbar.appearance().displaysRightAccessoryImage = false

When I set it to false, the initial state still shows the default Map location button. After typing a message, and then deleting that message, it shows a disabled Send button as I expect.

I'm calling the above piece of code inside of my viewDidLoad (after super.viewDidLoad) of my ATLConversationViewController subclass.

**Comment by kmahal** [comment]
```objc
/**
 @abstract Determines whether or not the right accessory button displays an icon. 
 @disucssion If NO, the right accessory button will display the text `SEND` at all times.
 @default YES
 */
@property(nonatomic) BOOL displaysRightAccessoryImage;
```
This property does not adhere to `UI_Appearance` selector.  Try setting it directly before the view's have laid out.

**Comment by troypayne** [comment]
This no longer happens.
