### ISSUE TITLE
Losing style if I reload my ATLConversationViewController subclass

### ISSUE THREAD

**Issue by troypayne** [layerhq/Atlas-iOS#1066]
Inside of the viewDidLoad of my ATLConversationViewController subclass, I'm specifying my custom attributes like:

ATLConversationCollectionView.appearance().backgroundColor = UIColorFromRGB(0xF0EFF5)
ATLMessageInputToolbar.appearance().leftAccessoryButton = nil

and everything works as expected the first time I load it.

However, when I dismiss the modal, and call it again (which does call viewDidLoad again) it no longer respects these properties and uses the defaults instead.  It's extremely strange.

Any help would be greatly appreciated. Thanks!

**Comment by kmahal** [comment]
@troypayne these properties do not adhere to `UI_Appearance`.  Set them directly.
