### ISSUE TITLE
Timestamp appears ontop of message bubble

### ISSUE THREAD

**Issue by JRam13** [layerhq/Atlas-iOS#1067]
I only notice this when the chat controller gets updated with multiple messages. For example, coming in and out of network and you have queued messages to be displayed. Happens on the update. 

![photo](https://cloud.githubusercontent.com/assets/3259292/11875650/b2ea7f3a-a4b3-11e5-9aa8-8c8036b72f2b.png)

**Comment by JRam13** [comment]
This happens to sender names as well, and I found the culprit code.

```objc
- (void)configureHeader:(ATLConversationCollectionViewHeader *)header atIndexPath:(NSIndexPath *)indexPath
{
    LYRMessage *message = [self.conversationDataSource messageAtCollectionViewIndexPath:indexPath];
    header.message = message;
    if ([self shouldDisplayDateLabelForSection:indexPath.section]) {
        [header updateWithAttributedStringForDate:[self attributedStringForMessageDate:message]];
    }
    if ([self shouldDisplaySenderLabelForSection:indexPath.section]) {
        [header updateWithParticipantName:[self participantNameForMessage:message]];
    }
}
```

should be:
```objc
- (void)configureHeader:(ATLConversationCollectionViewHeader *)header atIndexPath:(NSIndexPath *)indexPath
{
    LYRMessage *message = [self.conversationDataSource messageAtCollectionViewIndexPath:indexPath];
    header.message = message;
    if ([self shouldDisplayDateLabelForSection:indexPath.section]) {
        [header updateWithAttributedStringForDate:[self attributedStringForMessageDate:message]];
    }
    else{
        [header updateWithAttributedStringForDate:[[NSAttributedString alloc] initWithString:@"" attributes:nil]];
    }
    if ([self shouldDisplaySenderLabelForSection:indexPath.section]) {
        [header updateWithParticipantName:[self participantNameForMessage:message]];
    }
    else{
        [header updateWithParticipantName:@""];
    }
}

**Comment by JRam13** [comment]
Although the above fix adds a performance hit to an already laggy chat (scrolling). 

¯\_(ツ)_/¯

**Comment by feifanzhou** [comment]
@JRam13 can you verify the value that is returned from `collectionView:layout:referenceSizeForHeaderInSection:` when you are able to repro?

**Comment by JRam13** [comment]
@feifanzhou This is really hard to reproduce since it doesn't happen all the time and appears to "fix itself" once you scroll past it or leave the chat screen. I've also never seen this happen since i've implemented this fix above. 

If you'd like to reproduce, you should probably make the datestamp appear more often. Put your app on airplane mode and send a bunch of messages. Then re-establish connection and see the chat screen update. If you're lucky, you'll the the misplaced datestamp. Like I said before, this also happens with the  username label.
