### ISSUE TITLE
Can I create a custom ATLConversationTableViewCell?

### ISSUE THREAD

**Issue by astanton** [layerhq/Atlas-iOS#1068]
I'm looking to create a cell that I can use in a class that extends ATLConversationListViewController.  I want all of the functionality of the default ATLConversationTableViewCell and ATLConversationListViewController where it will use conversations as the datasource, auto-update the list based on the order of last message, show the last message on the cell, etc.  However I also want to make it so there is more information in the cell and also have a different layout.

I also would like to make it so that when you only click on a certain part of the cell it opens up the actual conversation with that person, because I want other actions to happen when they click on other parts of the cell.

Is this possible through subclassing?  If not, is this pretty simple to do by modifying the Atlas code?

I currently have my own ConversationListViewController for this purpose that is not extending the ATLConversationListViewController, however I am missing a lot of the default behavior that you get from extending the class, such as being "real time" with updates coming in if you are in the list view.  Before I dig further into this method, I was wondering if there was a better way by subclassing.

**Comment by kmahal** [comment]
Hey @astanton you can create your own cell that implements the `ATLConversationPresenting` protocol and registering it through:
```objc
/**
 @abstract The `UITableViewCell` subclass for customizing the display of the conversations.
 @discussion If you wish to provide your own custom class, your class must conform to the `ATLConversationPresenting` protocol.
 @default `ATLConversationTableViewCell`
 @raises NSInternalInconsistencyException Raised if the value is mutated after the receiver has been presented.
 */
@property (nonatomic) Class<ATLConversationPresenting> cellClass;
```
This will let you present the cell you want with the layout and properties you expect.
