### ISSUE TITLE
Stopping animations

### ISSUE THREAD

**Issue by troypayne** [layerhq/Atlas-iOS#1071]
When I load my custom ATLConversationViewController, it seems to be animating a few elements. Like the ATLMessageInputToolbar, and a few other random things.

Is this intentionally? If so how can I turn it off

**Comment by kmahal** [comment]
@troypayne are you presenting the controller with or without animation?

**Comment by troypayne** [comment]
@kmahal it's inside of a ContainerView, so i guess that means without...

**Comment by kmahal** [comment]
is the containerview presented on screen without animation?

**Comment by kmahal** [comment]
be sure to also embed your controller in a navigation controller before putting it inside a container view.

**Comment by troypayne** [comment]
@kmahal this is how i'm calling the VC that has a container view that embeds the ATLConversationViewController

        let storyboard = UIStoryboard(name: "STAN", bundle: nil)
        let chatViewController = storyboard.instantiateViewControllerWithIdentifier("ChatViewController") as! ChatViewController
        let navigationController = AbstractModalNavigationViewController(rootViewController: chatViewController)
        navigationController.setNavigationBarHidden(true, animated: false)
        navigationController.modalTransitionStyle = .CrossDissolve
        self.presentViewController(navigationController, animated: true, completion: nil)

**Comment by troypayne** [comment]
@kmahal 

And this is how i'm embedding it in a container view:

                                        let stayfulConversationViewController = StayfulConversationViewController(layerClient: self.layerClient)
                                        stayfulConversationViewController.conversation = conversation
                                        let navigationController = UINavigationController(rootViewController: stayfulConversationViewController)
                                        navigationController.setNavigationBarHidden(true, animated: false)
                                        navigationController.view.frame = self.containerView.bounds
                                        self.addChildViewController(navigationController)
                                        self.containerView.addSubview(navigationController.view)
                                        navigationController.didMoveToParentViewController(self)

and StayfulConversationViewController is a subclass of ATLConversationViewController

**Comment by troypayne** [comment]
Closing this. It no longer happens now that I push the VC instead of popping up a modal
