### ISSUE TITLE
Atlas cocoapod module problem

### ISSUE THREAD

**Issue by luka1995** [layerhq/Atlas-iOS#1079]
I have Atlas 1.0.16, but always problem with "Could not build module "Atlas"".

<img width="323" alt="screen shot 2016-01-06 at 22 43 22" src="https://cloud.githubusercontent.com/assets/3648001/12155724/1157f49e-b4c7-11e5-88ff-db4ed8beee66.png">
<img width="269" alt="screen shot 2016-01-06 at 22 43 16" src="https://cloud.githubusercontent.com/assets/3648001/12155729/13ad6012-b4c7-11e5-88ba-9fc5cde1b3d7.png">

**Comment by kmahal** [comment]
@luka1995 are you still having this issue?
