### ISSUE TITLE
Any guidelines on integrating the UI with UITabBarController setup?

### ISSUE THREAD

**Issue by jessearmand** [layerhq/Atlas-iOS#1081]
Any guidelines on integrating the Atlas conversation UI with UITabBarController setup?

Anyone has tried this before? Is there any problems or workaround?

I've noticed that the "typing indicator" may not be positioned properly (it's a bit covered by the message input toolbar) and UI glitches could appear such the tab bar appearing behind the message input toolbar, while I assume the tab bar should be covered by the whole ATLConversationViewController.

**Comment by kmahal** [comment]
@jessearmand best practice of Atlas has the application hiding the `UITabBar` at the bottom when presenting the `ATLConversationViewController`.  Look into the `ATLMessageInputToolbar` `layoutSubviews` to see how to set the input bar based on it's container view.  This will require application level configuration that can't be defaulted by Atlas.

**Comment by jessearmand** [comment]
Hiding it works fine. Thanks
