### ISSUE TITLE
UIAlertController causes messageInputToolbar to disappear

### ISSUE THREAD

**Issue by aenhsaihan** [layerhq/Atlas-iOS#1082]
When a UIAlertController is displayed to the user, the messageInputToolbar disappears completely.

The user has to scroll up to bring back the messageInputToolbar so that it can be tapped to become first responder.

Rather than simulating this user action, is there a better way to bring back the messageInputToolbar after receiving a UIAlertController?

**Comment by kmahal** [comment]
@aenhsaihan you can call `[self.view becomeFirstResponder]` in the `ATLConversationViewController subclass to make the input toolbar come back on screen.  Let me know if this works and we can close this out.

**Comment by aenhsaihan** [comment]
@kmahal yes, that does bring the message input toolbar back to the forefront, allowing me to call ```becomeFirstResponder``` on it, although there is a substantial delay in bringing back the keyboard this way.

My original solution of simulating the user action brought the keyboard back more quickly, but was more hacky as well.

**Comment by aenhsaihan** [comment]
Meh, seems to vary, keyboard can come back quickly or slowly.

**Comment by kmahal** [comment]
@aenhsaihan unfortunately that is then a system issue and not an Atlas one.  I'm going to close this ticket out as the system decides how quickly to show the keyboard.
