### ISSUE TITLE
editable ATLAddressBarViewController and how to self resize?

### ISSUE THREAD

**Issue by jessearmand** [layerhq/Atlas-iOS#1083]
After using it for a while in a group conversation, I've noticed that:

1. Once a conversation is created, the address bar is disabled by default, even though it's possible to add new participant to a conversation?

2. The address bar refused to display all participants name if they don't fit a specific size **when** it's in a disabled state. But, it can display all participants and self-resize, if I manually set `selectedParticipants` after a conversation is created. 

    However, once I do this, the address bar automatically becomes the default first responder, and I can't find any way to resign the address bar text view from first responder status. I suppose the address bar is not editable by default once a conversation is created? Which leads to my next question.

3. There are few situations where the address bar becomes disabled, is it possible to override this, and make it remain editable? What was the reason for disabling it?

4. The `disabledStringForParticipants:` will fallback to displaying the number of participants, if their names don't fit the size of the address bar. But, this is misleading to users, as it display participants count **minus** the first participant.

**Comment by kmahal** [comment]
@jessearmand :
1. This is just like the iMessage experience.  Look at Atlas Messenger (https://github.com/layerhq/Atlas-Messenger-iOS) for how we add or remove participants.
2. The address bar is not editable directly after a conversation is created, just like iMessage.
3. See point 1, it is after the iMessage aesthetic.
4. What do you mean first participant?

**Comment by jessearmand** [comment]
Take a look at this from `ATLAddressBarViewController.m`:

```objc
- (NSString *)disabledStringForParticipants:(NSOrderedSet *)participants
{
    [self.addressBarView.addressBarTextView layoutIfNeeded]; // Layout text view so we can have an accurate width.
    
    // First participant is removed
    __block NSString *disabledString = [participants.firstObject firstName];
    NSMutableOrderedSet *mutableParticipants = [participants mutableCopy];
    [mutableParticipants removeObject:participants.firstObject];
    
    __block NSUInteger remainingParticipants = mutableParticipants.count;
    [mutableParticipants enumerateObjectsUsingBlock:^(id<ATLParticipant> participant, NSUInteger idx, BOOL *stop) {
        NSString *othersString = [self otherStringWithRemainingParticipants:remainingParticipants];
        NSString *truncatedString = [NSString stringWithFormat:@"%@ %@", disabledString, othersString];
        // Could we just display all of them and resize, just when we set the participants in editable mode?
        if ([self textViewHasSpaceForParticipantString:truncatedString]) {
            remainingParticipants -= 1;
            othersString = [self otherStringWithRemainingParticipants:remainingParticipants];
            NSString *expandedString = [NSString stringWithFormat:@"%@, %@ %@", disabledString, participant.firstName, othersString];
            if ([self textViewHasSpaceForParticipantString:expandedString]) {
                disabledString = [NSString stringWithFormat:@"%@, %@", disabledString, participant.firstName];
            } else {
                disabledString = truncatedString;
                *stop = YES;
            }
        } else {
            // What's the rule in determining count?
            disabledString = [NSString stringWithFormat:@"%lu participants", (unsigned long)remainingParticipants];
            *stop = YES;
        }
    }];
    return disabledString;
}
```

I've added some comments in the snippet above, regarding my question. I could of course try to do something about this in a fork of the repo and make a pull request, but I would like to know how to best approach this problem.

**Comment by kmahal** [comment]
Hey @jessearmand revisiting this.  Is this still an open issue for you?  We wouldn't change this behavior as it matches iMessage.  Let me know what your thoughts are and we can close this out or discuss further.

**Comment by jessearmand** [comment]
@kmahal Yes the address bar is disabled once I sent a message. But, the participants listed are everyone who participated. Regardless of who is the sender. While from the snippet above, the sender is filtered. 

Thereby causing a misleading "(number) participants" when the participants data are incomplete.

I would separate the self-sizing and editable as a feature request, but the participants data are a bit invalid.

**Comment by jessearmand** [comment]
Ok, I understood these three lines

    __block NSString *disabledString = [participants.firstObject firstName];
    NSMutableOrderedSet *mutableParticipants = [participants mutableCopy];
    [mutableParticipants removeObject:participants.firstObject];

Just an issue of participants count and how to best fit them all.
