### ISSUE TITLE
Question: setting badge which combined from unread message & other app aspects

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1085]
I'm now in the process of setting up Push notifications, and I have 3 questions please:

A) **Setting badge which combined from unread message & other app aspects:**
I'm building a dating app, and I'd like the app badge to be set as the user's new matches count + unread messages.
Obviously, the first aspect is not available to Layer, so I'm not sure how to do it.

B) **I'm getting a push of new message with null instead of the user name ((null): test)...**

C) **When in foregorund, I'd like to present my own custom banner, instead of the default alert which is currently shown.** Does this can be done?

**Comment by kmahal** [comment]
Hi @oferRounds 

A) Layer does not currently support arbitrary badge count setting.  New match count infers conversation creation, probably from the Platform API.  If that's the case you could send a message with a `MIMEType` that the client hides and marks as read when it's first opened, which would technically be considered an unread message from Layer's perspective.
B) If you look at the Atlas code, push notification payloads are set from the `displayName` of the object that adheres to the `ATLParticipant`.  Check your delegate `conversationViewController:participantForIdentifier:` and that all objects have fully hydrated properties.
C) What default alert are you talking about?  Please send a screenshot.  Atlas is open sourced and so you can always make a fork or customize the behavior you want as you see fit.

**Comment by oferRounds** [comment]
Hi @kmahal 
Thanks for your detailed answer!

Regarding (B) & (C) - these were my mistakes - both fixed!

So I'm left with (A). Could you elaborate a bit more on this? Maybe I'd be able to understand if I understand what you mean by: "New match count infers conversation creation, probably from the Platform API."

Thanks again!
Ofer.

**Comment by kmahal** [comment]
HI @oferRounds you can create a match via Platform API and send a message with a `MIMEType` that you do NOT want to show up in the conversation on the client.  The badge count here will then reflect the unread message count + new match count (as the new match count is actually just the unread message count but the user won't see it).  When the user enters the conversation for the first time you can then mark that message they don't see as read, which would update the badge count as you'd expect.
