### ISSUE TITLE
The LayerKit Module is found in ATLUIMessagingUtilities.h

### ISSUE THREAD

**Issue by CodeBoffin** [layerhq/Atlas-iOS#1088]
The module @import LayerKit is showing not found in ATLUIMessagingUtilities.h even after the updating the cocoa pods successfully.

**Comment by AndrewSB** [comment]
having this issue using Carthage too, 

```
/Users/asb/Developer/Real/Carthage/Checkouts/Atlas-iOS/Code/Utilities/ATLMessagingUtilities.h:22:9: fatal error: module 'LayerKit' not found
/Users/asb/Developer/Real/Carthage/Checkouts/Atlas-iOS/Code/Utilities/ATLMessagingUtilities.h:22:9: fatal error: module 'LayerKit' not found
```

**Comment by LukeDurrant** [comment]
@CodeBoffin or @AndrewSB Did you find a solution to this?

**Comment by AndrewSB** [comment]
I've emailed into support, I think they're looking into it.

Would recommend targeting the HEAD of master when you build with Carthage, to include their hotfixes

**Comment by mogui** [comment]
Not working for me either

**Comment by maju6406** [comment]
We believe this issue should now be resolved if you're using Atlas 1.0.19 and LayerKit 0.19.1. Please try again.

**Comment by AndrewSB** [comment]
@maju6406 got your response that you make have spoken too soon. What is this looking like?

It would also be cool to be able to build both atlas and layer with `carthage update --no-use-binaries`, I don't think that no-build-binaries works yet

**Comment by mogui** [comment]
@maju6406 in my experience (two different machines) the only way to make it build (with some changes too, Atlas looks for a Resource.bundle that I have to make in my own) is by integrating Atlas and layer by including directly the source code manually, both Carthage and Cocoapods integration doesn't work out of the box.
It's a pity because the work done with these libs is amazing, but I expect them to just build when you say they can be integrated with such tools

**Comment by AndrewSB** [comment]
@maju6406 here's the current build log 

```
*** Fetching Atlas-iOS
*** Fetching releases-ios
*** Checking out releases-ios at "v0.19.1"
*** Checking out Atlas-iOS at "v1.0.19"
*** xcodebuild output can be found in /var/folders/gw/cg3k4_8j28v5ckmvf2bp7dl40000gn/T/carthage-xcodebuild.QqZOXQ.log
*** Building scheme "Atlas" in Atlas.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/asb/Library/Developer/Xcode/DerivedData/Atlas-erzwbtppfnttfhhbglggwwoaxskp/Build/Intermediates/Atlas.build/Release-iphoneos/Atlas.build/Objects-normal/armv7/ATLBaseCollectionViewCell.o Code/Views/ATLBaseCollectionViewCell.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/asb/Developer/LayerTest/Carthage/Checkouts/Atlas-iOS/Code/Protocols/ATLMessagePresenting.h:23:9: fatal error: module 'LayerKit' not found
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/asb/Library/Developer/Xcode/DerivedData/Atlas-erzwbtppfnttfhhbglggwwoaxskp/Build/Intermediates/Atlas.build/Release-iphoneos/Atlas.build/Objects-normal/armv7/ATLBaseCollectionViewCell.o Code/Views/ATLBaseCollectionViewCell.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by blakewatters** [comment]
I have found our attempt to support Carthage to be a huge pain in the ass. I don't see how it is possible for us to support `carthage update --no-use-binaries` given that we are distributing a binary framework. The assets get placed in a different place on the filesystem, so I don't see how you can configure a project that works with and without the option. The Atlas-iOS project is set up to assume that you are just doing a vanilla `carthage update` and using the release asset vs. cloning the releases-ios repository, which incidentally just gets you another copy of that same binary framework.

On my Atlas + Carthage test project the problem I haven't been able to solve is that Carthage builds are producing an Atlas.framework that is missing architectures and therefore won't link into the app target.

For all its purported simplicity I've found Carthage to be way less flexible and difficult to work with than CocoaPods.

**Comment by blakewatters** [comment]
@mogui I'm not sure what you mean -- I just did a clean pull of Atlas-Messenger-iOS and Atlas-iOS and they both build. What's your issue?

**Comment by AdamBCo** [comment]
I just used Cocoapods to install Atlas (1.0.19), and I'm running into the same issue.

`Module` 'LayerKit' not found'

What is the recommended fix? I can't get the sample project running either.

**Comment by AndrewSB** [comment]
@blakewaters let's forget the `--no-use-binaries` then, can we just get the library to work with a vanilla `carthage update`?

**Comment by mixmastertube** [comment]
Cocoapods installation didn't work for:
Module 'LayerKit' not found' error

Carthage didn't work too..

Hoping the manual integration will..

**Comment by CodeBoffin** [comment]
Please can any of moderators look into this matter.It's been out for more than 40 days since it came into my attention.

**Comment by AdamBCo** [comment]
@CodeBoffin If you are using Objective-C and cocoapods, I've found the solution!

At the moment the Atlas documentation on Github states you need to just to add pod 'Atlas' to your pod file and run pod install.

You actually have to add the following as well:

    use_frameworks!

It also doesn't mention that Atlas installs LayerKit for you, so there is no need to have pod 'LayerKit' and pod 'Atlas' in the same pod file.
