### ISSUE TITLE
NSInternalConsistencyException when loading ATLConversationListViewController

### ISSUE THREAD

**Issue by JGagnon91** [layerhq/Atlas-iOS#1092]
This only happens for a subset of our users. Some users are unnafected but those who have the issue get the crash consistently every time they try to enter the Conversation controller. I've tried to isolate it to a specific version of iOS or a specific iPhone model, but it seems to affect users indiscrimately.

Here's the stacktrace taken from Fabric:

Fatal Exception: NSInternalInconsistencyException
unable to dequeue a cell with identifier ATLConversationCellReuseIdentifier - must register a nib or a class for the identifier or connect a prototype cell in a storyboard

Atlas	
ATLConversationListViewController.m line 264
-[ATLConversationListViewController tableView:cellForRowAtIndexPath:]

**Comment by JGagnon91** [comment]
I've discovered that by changing the code from:
`UITableViewCell<ATLConversationPresenting> *conversationCell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier forIndexPath:indexPath];`

to:

`UITableViewCell<ATLConversationPresenting> *conversationCell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if(conversationCell == nil)
    {
        conversationCell = [[ATLConversationTableViewCell alloc] init];
    }`

My users now don't crash any longer, but the cells all load without the imageview for partipant photos visible. Once the cells have been reloaded by scrolling down the list of conversations, cells that are reloaded then have the imageview visible.

I'm wondering if this is somehow related to the initialization of the list view controller.

**Comment by kmahal** [comment]
@JGagnon91 Has this occurred in every version of `Atlas`?  There were a few changes made during initialization of the controller recently would affect that.  See this commit: https://github.com/layerhq/Atlas-iOS/commit/ad06f3c0f722820f3ffe07dd7af0833845e105bb If you revert this change do the crashes still occur? 

If a cell class is registered before the table view delegates are fired then you don't need a `nil` check, but if it's not then you would need a `nil` check (thus why your change would fix it).  I suspect this is related to the issue but can dig in further.

**Comment by JGagnon91** [comment]
It hasn't occurred in every version of Atlas, and in fact we only started seeing it a few days ago after updating our pods. Before we updated I believe we were on 1.0.11. 

Reverting the commit you linked does seem to have fixed the issue for my test devices, though I haven't sent it out to our testers yet, but I suspect it has fixed the issue. It looks like you're right about cell registration, but i'll update once i've had a chance for other users to see if this fixes it!

**Comment by JGagnon91** [comment]
I've not seen any more crashes since going back to that commit, it looks like it fixed the issue. What are the next steps?

**Comment by kmahal** [comment]
@JGagnon91 I will have a PR fixing this issue forthcoming shortly.

**Comment by kmahal** [comment]
PR here: https://github.com/layerhq/Atlas-iOS/pull/1093

**Comment by kmahal** [comment]
released in `1.0.19`
