### ISSUE TITLE
Incorrect Content Type in Message Cells

### ISSUE THREAD

**Issue by DevMoz** [layerhq/Atlas-iOS#1101]
I noticed when upgrading from 1.0.16 to 1.0.17 that I would have images in a conversation show up in message cells that were supposed to be text, as shown below:

![img_0361](https://cloud.githubusercontent.com/assets/6776567/13024359/398b882e-d1a8-11e5-8a0c-d6678902600d.png)

This would correct itself as soon as you started scrolling. 

For version 1.0.17, in `- (void)configureBubbleViewForImageContent` in `ATLMessageCollectionViewCell.m`, the call to `dispatch_async(dispatch_get_main_queue()` was moved to only encompass the following:

```
dispatch_async(dispatch_get_main_queue(), ^{
    [weakSelf.bubbleView updateWithImage:displayingImage width:size.width];
});
```

As soon as I moved it back to where it was in version 1.0.16 (as below), the problem went away and it now works perfectly again:

```
dispatch_async(dispatch_get_main_queue(), ^{
    // Fall-back to programatically requesting for a content download of single message part messages (Android compatibillity).
    if ([[weakSelf.message valueForKeyPath:@"parts.MIMEType"] isEqual:@[ATLMIMETypeImageJPEG]]) {
        if (fullResImagePart && (fullResImagePart.transferStatus == LYRContentTransferReadyForDownload)) {
            NSError *error;
            LYRProgress *progress = [fullResImagePart downloadContent:&error];
            if (!progress) {
                NSLog(@"failed to request for a content download from the UI with error=%@", error);
            }
            [weakSelf.bubbleView updateProgressIndicatorWithProgress:0.0 visible:NO animated:NO];
        } else if (fullResImagePart && (fullResImagePart.transferStatus == LYRContentTransferDownloading)) {
            [self updateCellWithProgress:fullResImagePart.progress];
        } else {
            [weakSelf.bubbleView updateProgressIndicatorWithProgress:1.0 visible:NO animated:YES];
        }
    }
    if (weakSelf.message != previousMessage) {
        return;
    }
    
    [weakSelf.bubbleView updateWithImage:displayingImage width:size.width];
});
```

Not totally sure if there is a reason not to revert back but it works for me. Hope it helps someone else.

**Comment by kmahal** [comment]
@DevMoz I don't think the issue is in the wrong cells updating, but rather in cell size.  Can you log what value `size.width` is in both versions?  We made a change a while ago to allow small images to be sent and that could be what you are seeing here.

**Comment by Moonko** [comment]
@kmahal I have the same issue after updating to the new version of Atlas. The cell's size is correct, but there's an image above the cell's text.

**Comment by charlespsdowd** [comment]
I have the same issue.

**Comment by charlespsdowd** [comment]
I think that the test for message being different needs to move inside the main thread block?
              
        dispatch_async(dispatch_get_main_queue(), ^{

            if (weakSelf.message != previousMessage) {
                return;
            }

            [weakSelf.bubbleView updateWithImage:displayingImage width:size.width];
        });

**Comment by sebyddd** [comment]
Encountering the same issue: 
<img width="222" alt="screen shot 2016-03-21 at 12 52 25" src="https://cloud.githubusercontent.com/assets/5271150/13916511/ca3ff7c8-ef63-11e5-84a9-5da9e35363ca.png">


@charlespsdowd's change fixed the problem. Can we please move the if statement to the main queue on main branch and include it in the next update?

**Comment by JRam13** [comment]
I've noticed this issue too. Won't @charlespsdowd fix cause more lag/ frame drops?

**Comment by kcoleman731** [comment]
@JRam13 @sebyddd @DevMoz is this still happening on the current Atlas version? If so, I will investigate.

**Comment by DevMoz** [comment]
@kcoleman731 I'm still using 1.0.20. It was happening until I made the change I noted above and then it works fine. Thanks for the follow up!

I'll update Atlas this weekend and will report back.

**Comment by kcoleman731** [comment]
@DevMoz the fix above from @charlespsdowd  went out in the latest release. https://github.com/layerhq/Atlas-iOS/blob/master/Code/Views/ATLMessageCollectionViewCell.m#L197

cc @sebyddd
