### ISSUE TITLE
Comparison conversation in subclass ATLConversationViewController

### ISSUE THREAD

**Issue by willyanto** [layerhq/Atlas-iOS#1105]
Why I can put this code in subclass ATLConversationViewController. I working in swift project. I see the example working on Objective-C

```
if (self.conversation) {    // error => Type 'LYRConversation' does not conform to protocol 'BooleanType'
            
}
```

**Comment by kmahal** [comment]
Closing this as it is a programming question, not an Atlas question.  Look at optional binding in Swift to see how to check for `nil` values.
