### ISSUE TITLE
Automatically Conversation Appeared After creating New Use

### ISSUE THREAD

**Issue by rishi-lambe** [layerhq/Atlas-iOS#1109]
Hi,

When I am creating new user,
Default conversation is appeared on chat screen, But I didn't started the conversation.
So, how I restrict this ?

**Comment by kmahal** [comment]
@rishi-lambe please explain further what you mean.  Do you mean when running the app?  That's a sample conversation.

**Comment by kmahal** [comment]
This was resolved as an onboarding confusion.

**Comment by rishi-lambe** [comment]
@kmahal  - When new user login in to app - A group conversation is appeared on screen. That I want to say
