### ISSUE TITLE
ATLConversationListViewController not refreshed if displayed too early

### ISSUE THREAD

**Issue by jfradj** [layerhq/Atlas-iOS#1110]
If the ATLConversationListViewController's view is loaded before the LYRClient is connected AND the user is authenticated, the view won't show anything (which is normal) but won't refresh itself when anything is setup.

The view should either observer the did connect and did user authenticate notifications to setup its query controller OR you should publicly expose the method - (void)setupConversationDataSource; so we can call it when the client is connected and the user authenticated.

**Comment by kmahal** [comment]
@jfradj `Atlas` is designed with the idea that the client is already authenticated when running ,and the UI should be configured as such.  If you'd like to see a change for this, feel free to submit a pull request.
