### ISSUE TITLE
Cannot set UIAppearance value for ATLMessageCollectionViewCell messageTextCheckingTypes

### ISSUE THREAD

**Issue by s73v3r** [layerhq/Atlas-iOS#1111]
I'm trying to get the message cells to recognize Phone Numbers, so that when they are tapped on, the user can do things with them (make calls, add contact, etc). I've tried setting the UIAppearance value on messageTextCheckingTypes as such:

``` Swift
ATLMessageCollectionViewCell.appearance().messageTextCheckingTypes = NSTextCheckingType.PhoneNumber //.PhoneNumber //[.Link, .PhoneNumber]
```
but it always crashes for me, saying:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Illegal property type, Q for appearance setter, setMessageTextCheckingTypes:'
```

What is the appropriate way to enable the setting of data detectors, so that I can do this?

**Comment by s73v3r** [comment]
So doing a little research, it looks like you never should have been able to set the UI_APPERANCE_SELECTOR macro on this property. According to the docs (https://developer.apple.com/library/ios/recipes/UIAppearanceContainer_Protocol/index.html#//apple_ref/occ/intf/UIAppearanceContainer), NSTextCheckingType, which is uint64_t, is not an allowed value.

**Comment by kmahal** [comment]
Good catch, thanks @s73v3r.  This can instead be configured via `configureCell:forMessage:`, and we'll remove that selector.

**Comment by kmahal** [comment]
merged in: https://github.com/layerhq/Atlas-iOS/pull/1157
