### ISSUE TITLE
Crash related to Layer, LYRBlockListRepository

### ISSUE THREAD

**Issue by nucauthu** [layerhq/Atlas-iOS#1115]
Hi team,

I'm not sure I should ask about this issue in this repo or document layer repo. This is a crash cause by layer. This crash a lot and effect user experience too much so we need to try to prevent or solve it. Please read the crash log of from crashlytic: http://crashes.to/s/26392113da2
I'm really appreciate if team can help me to clear this crash. Thanks a lot.

**Comment by kmahal** [comment]
Hi @nucauthu as this is a `LayerKit` crash, please contact Layer support directly as it's not Atlas specific.
