### ISSUE TITLE
Native Typing Indicator (3 dots)

### ISSUE THREAD

**Issue by jyounus** [layerhq/Atlas-iOS#1121]
Hey there,

Is it currently possible to show the three animated dots like in the native Apple Messaging app? If not, is that something you guys are planning to add?

Thanks

**Comment by kmahal** [comment]
@jyounus it is something that is in our backlog though not a high priority currently.  We have our own typing indicator implementation as you've surely seen.  Feel free to open a PR if you have a working implementation.
