### ISSUE TITLE
Retrieving deleted messages

### ISSUE THREAD

**Issue by facing-n** [layerhq/Atlas-iOS#1125]
Now that LYRDeletionModeLocal has been deprecated, is there anyway to retrieve deleted messages.

case:

1. User A and User B are in a chat
2. User A deletes chat on their devices
3. User B sends User A a new message

Can User A retrieve the previous messages that were deleted from their devices in 2?  They are still in user B's chat

**Comment by kmahal** [comment]
@facing-n this is a `LayerKit` question, but the user will no longer have access to the messages when deleting the conversation.
