### ISSUE TITLE
Infinite loading on top of the ATLConversationViewController

### ISSUE THREAD

**Issue by mvalti** [layerhq/Atlas-iOS#1126]
Hi!

Since I've upgraded the LayerKit to v0.19.3 the more message loading indicator appears on top of the conversation screen after sending the first message to a user.

(UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath; 
method was called with indexpath(row = 0, section = 0) and the ATLMoreMessagesSection didn't dissapear. 

With v0.19.1 this method was called with  indexpath(row = 0, section = 1) and the more message section with loading indicator didn't appear after the first message was sent.

How can I fix this issue?

Thanks, Valti!

**Comment by thomasgpeng** [comment]
I'm having a similar issue with LayerKit 0.19.3.  When I scroll to the top of a long conversation in `ATLConversationViewController`, the loading indicator for more messages seems to "get stuck" and instead of loading only the next page of messages, the view loads the entire message history.

**Comment by nullcode000** [comment]
same issue here. Is there a quick fix until next version? We're stuck on production with this bug.

**Comment by sebyddd** [comment]
+1

Also having the same issue. Started noticing it after upgrading to 1.0.19.

**Comment by thomasgpeng** [comment]
@kmahal little help please?!

**Comment by fstege** [comment]
Same issue here! Product heavily relies on layer. Would really appreciate a quick fix!

**Comment by kmahal** [comment]
Hi everyone.  A fix for this has been merged into master https://github.com/layerhq/Atlas-iOS/commit/0119489c13f6d878fb8e0493f7c2210d454faa34.  If you point your podfile to master on github you should be able to see the fix.  We'll be releasing a new official version soon that has this fix and a few others.
