### ISSUE TITLE
How to change push notification sound?

### ISSUE THREAD

**Issue by ricardorover** [layerhq/Atlas-iOS#1129]
Is there a way to change the default push notification sound ("layerbell.caf" in ATLPushNotificationSoundName) to a custom sound?
The only way I found to do this is changing ATLPushNotificationSoundName value in ATLConversationViewController, but i found no 'atlas framework' way to do that.

Thanks

**Comment by feifanzhou** [comment]
`APTLPushNotificationSoundName` is only [used when sending a message](https://github.com/layerhq/Atlas-iOS/blob/master/Code/Controllers/ATLConversationViewController.m#L637) — you specify the alert sound you want played on the receiving device when you send the message. 

The "Atlas framework" way to change the push notification sound, therefore, is to specify the sound you want to use when you send the message. You can do this in your subclass of `ATLConversationViewController`, or what code ultimately generates the `LYRMessage` object that gets sent.

**Comment by Vaberer** [comment]
Can you please provide an example how to change push notification sound in ```ATLConversationViewController``` subclass?

**Comment by feifanzhou** [comment]
@Vaberer Set `LYRMessageOptionsPushNotificationSoundNameKey` when you [create a message](https://developer.layer.com/docs/ios/integration#lyrmessage).
