### ISSUE TITLE
Usernames are not hiding. 

### ISSUE THREAD

**Issue by sebyddd** [layerhq/Atlas-iOS#1131]
Since upgrading the the latest pod version, I can no longer hide the usernames in conversations. 

```
    self.shouldDisplayAvatarItemForAuthenticatedUser = NO;
    self.shouldDisplayAvatarItemForOneOtherParticipant = NO;
```

Both are set, but still 'Unknown User' is being displayed: 

<img width="170" alt="screen shot 2016-03-21 at 12 34 02" src="https://cloud.githubusercontent.com/assets/5271150/13916094/38f27f22-ef61-11e5-8168-6d2b0880808e.png">

Any fixes ? 
Thanks in advance!

**Comment by mihaitrandafir1** [comment]
We are experiencing the same issue using the latest version of the SDK when trying to hide the sender label.

**Comment by victorcazacu** [comment]
same problem. Problem just showed up, didn't have this in previous versions.

**Comment by kmahal** [comment]
@sebyddd we haven't gotten any reports of this, but since Atlas is open sourced, set a break point in
```objc
- (BOOL)shouldDisplaySenderLabelForSection:(NSUInteger)section
```
and see why it may be returning `YES`.  Are these 1:1 conversations, or group conversations?

**Comment by kcoleman731** [comment]
@sebyddd any updates here?

**Comment by kcoleman731** [comment]
@sebyddd closing this issue due to no response. Please let me know if you would like me to reopen.
