### ISSUE TITLE
Question: how can we tell when conversation's data was loaded

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1137]
Specifically, I'd like to find out when the data was loaded, but there are 0 conversations to present (I'd like to show a placeholder).

**Comment by kmahal** [comment]
@oferRounds you can do this yourself by running a simple query:
```objc
NSError *error;
LYRQuery *query = [LYRQuery queryWithQueryableClass:[LYRConversation class]];
NSInteger count = [self.layerClient countForQuery:query error:&error];
```
Then you can know if there are any or not.  You can also put the above in a query controller, so if a conversation does appear you can get rid of the placeholder.

**Comment by oferRounds** [comment]
@kmahal - thanks for your response!

Question: as I understand, this query relates to the present local data, right?

The thing is that I would like to address the following scenario:
Let's say we have a new user, and his device's reachability is not that good, so it takes some more time to fetch the remote data. So in the mean time, I would like to present an `Activity Indicator`.

Then, when getting the response, I would like to address all 3 possible scenarious:
1. **No Conversations** - Removing the `Activity Indicator` + presenting no-conversations placeholder 
2. **Error** - Removing the `Activity Indicator` + presenting error placeholder 
3. **1+ Conversations** - Removing the `Activity Indicator` + showing the conversations list

So my question: how do I address cases #1 and #2?

**Comment by oferRounds** [comment]
Ok, I think I got it: I observe the `LYRClientDidFinishSynchronizationNotification`.

**Comment by oferRounds** [comment]
Except maybe for the Error handling.
