### ISSUE TITLE
Bug: when sending the first message in a conversation, activity indicator is shown and not removed

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1138]
- Seeing it above the date label
- when restarting the app it's gone
- Happens only on new conversation 
- Saw it only now, after upgrading Layer to v0.19.4

**Comment by mvalti** [comment]
It happened to me as well with v0.19.4.

**Comment by mailyan** [comment]
+1

**Comment by alexandrwang** [comment]
Also seeing this, even after updating to 0.20.0

**Comment by alexandrwang** [comment]
This fixed it for me https://github.com/layerhq/Atlas-iOS/pull/1148

**Comment by kmahal** [comment]
This has been fixed on master and the most recent release.
