### ISSUE TITLE
Inconsistent message cell spacing

### ISSUE THREAD

**Issue by sebyddd** [layerhq/Atlas-iOS#1143]
We are encountering a weird vertical spacing issues between text cells. As you can see below, the spacing is inconsistent. Also, is there any available way to manually adjust the vertical spacing between cells ?

<img width="520" alt="screen shot 2016-03-29 at 19 04 15" src="https://cloud.githubusercontent.com/assets/5271150/14114787/2311c650-f5e1-11e5-931e-54dbff93981e.png">
 
Thanks!

**Comment by kmahal** [comment]
@sebyddd we currently space out cells based on how long the message has been sent since the last message was sent:
```
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section
{
    if (section == ATLMoreMessagesSection) return CGSizeZero;
    NSAttributedString *readReceipt;
    if ([self shouldDisplayReadReceiptForSection:section]) {
        readReceipt = [self attributedStringForRecipientStatusOfMessage:[self.conversationDataSource messageAtCollectionViewSection:section]];
    }
    BOOL shouldClusterMessage = [self shouldClusterMessageAtSection:section];
    CGFloat height = [ATLConversationCollectionViewFooter footerHeightWithRecipientStatus:readReceipt clustered:shouldClusterMessage];
    return CGSizeMake(0, height);
}
```
Feel free to fire up a PR if you'd like to see this property.
