### ISSUE TITLE
Unable to submit to App Store: ERROR ITMS-90535

### ISSUE THREAD

**Issue by JJGEight** [layerhq/Atlas-iOS#1145]
I have updated Atlas to 1.0.20 and I have tried submitting a new version of my app to the App Store. Having when submitting an Archive it fails without an error and through the application loader it gives an ERROR ITMS-90535 error.

I updated through Cocoapods without any problems. I also tried finding the Info.plist in question but when I chose the Atlas-AtlasResource target and selecting Info I was greeted by the message 'Information from info.plist not available. File may not exist at specified path."

> ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/AppName.app/Frameworks/Atlas.framework/AtlasResource.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by rajavikram** [comment]
+1

**Comment by ejazAlgotrek** [comment]
Any update on this ?

**Comment by JJGEight** [comment]
A temporary fix that I am using is setting LayerKit and and Atlas to an older version. My podfile is set as:

`pod 'Atlas', '1.0.19'
pod 'LayerKit', '0.19.4'`

**Comment by ejazAlgotrek** [comment]
Can't try that one... already done a lot of work with 0.21 of layer

**Comment by DevMoz** [comment]
I had the same issue. Just remove the `CFBundleExecutable` key from `info.plist` (in resources folder) and it will work fine.

https://github.com/layerhq/Atlas-iOS/commit/3cef0fe4fc44a9efa906f2b512c26fe555f98c79

**Comment by feifanzhou** [comment]
Sorry about this issue — should be fixed here https://github.com/layerhq/Atlas-iOS/pull/1144
