### ISSUE TITLE
Conversation list controller with tab bar

### ISSUE THREAD

**Issue by Jutteren** [layerhq/Atlas-iOS#1146]
When I'm combining a tab bar with the Layer conversation list control, the conversation list control moves up  too far and the search bar gets lost. Any help?
![img_1726](https://cloud.githubusercontent.com/assets/16014847/14145104/d35cab9a-f692-11e5-8e61-2cb904cbbb30.PNG)

**Comment by JRam13** [comment]
You need to embed a navigation controller on your ConversationListController.

<img width="1727" alt="screen shot 2016-03-30 at 3 02 00 pm" src="https://cloud.githubusercontent.com/assets/3259292/14154016/66fd1fca-f688-11e5-903a-3a3c6e082866.png">

**Comment by kmahal** [comment]
@Jutteren @JRam13 is correct.  The controller is designed to work with a navigation controller.
