### ISSUE TITLE
Typo in ATLConversationListViewController results in build error

### ISSUE THREAD

**Issue by cwalo** [layerhq/Atlas-iOS#1149]
Changing the following method declaration in `ATLConversationListViewController` build is successful. Note `UITableViewRowAction` becomes `NSNumber`, which appears may have just been a typo to begin with.

`- (NSArray *)conversationListViewController:(ATLConversationListViewController *)conversationListViewController rowActionsForDeletionModes:(NSArray < UITableViewRowAction *> *)deletionModes;`

to:

`- (NSArray *)conversationListViewController:(ATLConversationListViewController *)conversationListViewController rowActionsForDeletionModes:(NSArray < NSNumber *> *)deletionModes;`

Note: Using Xcode 7.3 & Swift 2.2

**Comment by kcoleman731** [comment]
@cwalo can you send me the build error? Not sure why you are getting it, but we definitely not want to change the param type.

**Comment by kcoleman731** [comment]
@cwalo would love to see the build error. Otherwise will close due to no response.

**Comment by cwalo** [comment]
Apologies for the delay. I haven't done any work with Layer since, so I'm unable to replicate at the moment. I'll re-open if I revisit this.
