### ISSUE TITLE
Bug where ATLConversationView jumps to top of conversation when message sent

### ISSUE THREAD

**Issue by alexandrwang** [layerhq/Atlas-iOS#1153]
About 1/3 of the time when sending a message, the conversation view jumps to the top of the view and causes a huge disruption in user flow.

Any ideas what might be causing it? 

I tried forcibly calling `scrollToBottomAnimated` when a message was sent, but that didn't seem to fix the issue.

**Comment by kmahal** [comment]
@alexandrwang can this be reproduced?  We haven't seen any reports of this.  Are you embedding the controller in a navigation controller or changing the view logic at all?

**Comment by kcoleman731** [comment]
@alexandrwang any updates here? Otherwise we will close the ticket. Thanks.

**Comment by kcoleman731** [comment]
@alexandrwang closing the ticket due to no response. Please let me know if it pops up again.

**Comment by alexandrwang** [comment]
Sorry about the late response!

It happens consistently on our app, and is consistently reproducible. For me to reproduce:
* Load conversation, and scroll conversation view to middle of conversation
* Send a message from other use in conversation.
* The view will scroll to the bottom, and then jump abruptly to the top.

We aren't embedding it in a navigation controller, but I couldn't find any places where that could have caused this to occur, unless there was something more obscure I'm missing.
