### ISSUE TITLE
Uneven bottom spacing inside chat bubbles for text messages!

### ISSUE THREAD

**Issue by Ashif22khan** [layerhq/Atlas-iOS#1158]
I am facing a strange issue with message bubble height for text messages.
I have overridden cellHeightForTextMessage and using boundingRectWithSize to calculate the desired length. But bubble height is not accurate for example if I have a message "Hello how are you?" twice in my message view, the bubble that is being generated will have different paddings for both appearances of the same messages.
![problem](https://cloud.githubusercontent.com/assets/11173960/14458022/2808575a-00cc-11e6-8e9d-abc365f52129.png)

**Comment by kmahal** [comment]
@Ashif22khan as you are overriding `cellHeightForTextMessage`, that's an implementation issue for your code, as it is not using default Atlas behavior.

**Comment by Ashif22khan** [comment]
@kmahal even if i try it without overriding height is not correct, I just tried it with the default Atlas implementation of cellHeightForTextMessage.
Please suggest.....
