### ISSUE TITLE
*** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:]

### ISSUE THREAD

**Issue by Ashif22khan** [layerhq/Atlas-iOS#1159]
I am facing this strange crash whenever two participants are messaging and sending messages at a higher rate (like one message per 3 to 5 seconds), this crash happens, here is the detail of the crash message.

*** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:]
*** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.7/UICollectionView.m:4609
2016-04-13 14:29:35.941 Ishqr[228:6729] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (68) must be equal to the number of sections contained in the collection view before the update (67), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'
*** First throw call stack:
(0x23caf98b 0x2344ae17 0x23caf861 0x24493509 0x28a1bd79 0x28a1ee09 0x28a1ec95 0x28405881 0x1a75e7 0x122ba57 0x26f4b7f 0x26f4b6b 0x26f9655 0x23c71bdd 0x23c700d7 0x23bbf2e9 0x23bbf0d5 0x251afac9 0x282840b9 0xd2edd 0x23867873)
libc++abi.dylib: terminating with uncaught exception of type NSException

I checked self.collectionView is not nil...
Here is the crash log,

Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Filtered syslog:
None found

Last Exception Backtrace:
0   CoreFoundation                	0x23b73986 __exceptionPreprocess + 122
1   libobjc.A.dylib               	0x2330ee12 objc_exception_throw + 34
2   CoreFoundation                	0x23b7385c +[NSException raise:format:arguments:] + 100
3   Foundation                    	0x24357504 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 88
4   UIKit                         	0x288dfd74 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:] + 9572
5   UIKit                         	0x288e2e04 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 348
6   UIKit                         	0x288e2c90 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 52
7   UIKit                         	0x282c987c -[UICollectionView performBatchUpdates:completion:] + 40
8   Ishqr                         	0x001da72a 0xe0000 + 1025834
9   LayerKit                      	0x00ff0a52 0xf2c000 + 805458
10  libdispatch.dylib             	0x236e181e _dispatch_call_block_and_release + 6
11  libdispatch.dylib             	0x236e180a _dispatch_client_callout + 18
12  libdispatch.dylib             	0x236efba4 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1520
13  CoreFoundation                	0x23b35bd8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 4
14  CoreFoundation                	0x23b340d2 __CFRunLoopRun + 1570
15  CoreFoundation                	0x23a832e4 CFRunLoopRunSpecific + 516
16  CoreFoundation                	0x23a830d0 CFRunLoopRunInMode + 104
17  GraphicsServices              	0x25073ac4 GSEventRunModal + 156
18  UIKit                         	0x281480b4 UIApplicationMain + 140
19  Ishqr                         	0x00105e78 0xe0000 + 155256
20  libdyld.dylib                 	0x2372b86e tlv_get_addr + 42

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x237fec5c __pthread_kill + 8
1   libsystem_pthread.dylib       	0x238a8732 pthread_kill + 62
2   libsystem_c.dylib             	0x23793126 __abort + 110
3   libsystem_c.dylib             	0x237930b8 __abort + 0
4   libc++abi.dylib               	0x232eaae4 __cxa_bad_cast + 0
5   libc++abi.dylib               	0x2330369e default_terminate_handler() + 266
6   libobjc.A.dylib               	0x2330f0b0 _objc_terminate() + 192
7   Ishqr                         	0x004aade4 0xe0000 + 3976676
8   libc++abi.dylib               	0x23300e16 std::__terminate(void (*)()) + 78
9   libc++abi.dylib               	0x233005f4 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 0
10  libobjc.A.dylib               	0x2330eeea objc_exception_throw + 250
11  CoreFoundation                	0x23b73860 +[NSException raise:format:] + 0
12  Foundation                    	0x24357508 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 92
13  UIKit                         	0x288dfd78 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:] + 9576
14  UIKit                         	0x288e2e08 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 352
15  UIKit                         	0x288e2c94 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 56
16  UIKit                         	0x282c9880 -[UICollectionView performBatchUpdates:completion:] + 44
17  Ishqr                         	0x001da72e 0xe0000 + 1025838
18  LayerKit                      	0x00ff0a56 0xf2c000 + 805462
19  libdispatch.dylib             	0x236e1822 _dispatch_call_block_and_release + 10
20  libdispatch.dylib             	0x236e180e _dispatch_client_callout + 22
21  libdispatch.dylib             	0x236efba8 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1524
22  CoreFoundation                	0x23b35bdc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
23  CoreFoundation                	0x23b340d6 __CFRunLoopRun + 1574
24  CoreFoundation                	0x23a832e8 CFRunLoopRunSpecific + 520
25  CoreFoundation                	0x23a830d4 CFRunLoopRunInMode + 108
26  GraphicsServices              	0x25073ac8 GSEventRunModal + 160
27  UIKit                         	0x281480b8 UIApplicationMain + 144
28  Ishqr                         	0x00105e7c 0xe0000 + 155260
29  libdyld.dylib                 	0x2372b872 start + 2

Any suggestions please?

**Comment by kcoleman731** [comment]
@Ashif22khan looks like this is the same as https://github.com/layerhq/Atlas-iOS/issues/1164. As we have the discussion going on over there, I'll close this ticket.

**Comment by smileEvday** [comment]
It looks like the IndexPath's row Or Section out of bound of array
