### ISSUE TITLE
Copy AtlasResource.bundle: No such file or directory

### ISSUE THREAD

**Issue by davideme** [layerhq/Atlas-iOS#1160]
I cloned https://github.com/layerhq/Layer-Parse-iOS-Example
```
$ pod install
$ open Layer-Parse-iOS-Example.xcworkspace
```
I build and I get the following error
error: .../Build/Products/Debug-iphonesimulator/Atlas/AtlasResource.bundle: No such file or directory

My setup:
XCode 7.3
cocoapods 1.0.0.beta.6
Atlas (1.0.22)
LayerKit (0.20.2)

**Comment by davideme** [comment]
The same configuration with cocoapods 0.39.0 is working.

**Comment by sebyddd** [comment]
Same issue. This most likely causes the issue below too. It might be an incompatibility between the new version of Atlas and LayerKit.

![screen shot 2016-04-14 at 08 37 48](https://cloud.githubusercontent.com/assets/5271150/14534032/4ada01f6-021c-11e6-9b84-67b1bafba30f.png)

**Comment by kcoleman731** [comment]
Hi @sebyddd and @davideme, we are not compatible with Cocoapods 1.0 betas yet.
