### ISSUE TITLE
Duplicate interface definition after update

### ISSUE THREAD

**Issue by sara-shokry** [layerhq/Atlas-iOS#1162]
i  can't build my project after update to latest release Atlas (1.0.22) Using LayerKit (0.20.2)
"Duplicate interface definition for class ATLConversationViewController" and many other classes

**Comment by kcoleman731** [comment]
Hi @sara-shokry can you tell how you are brining LayerKit and Atlas into your project? I am assuming cocoapods and if so, can you tell me the version?

**Comment by kcoleman731** [comment]
@sara-shokry This issue should be resolved as of `Atlas 1.0.23`. Please let me know if you are still seeing this issue.
