### ISSUE TITLE
UISearchDisplayController deprecation warning ATLParticipantTableViewController

### ISSUE THREAD

**Issue by dsieczko** [layerhq/Atlas-iOS#1163]
I was trying to set hidesNavigationBarDuringPresentation

**Comment by kcoleman731** [comment]
Hi @dsieczko the `UISearchDisplayController` has indeed been deprecated. We have not yet switched Atlas over to using the new `UISearchController` yet. To silence the deprecation warning in your code you can do the following 

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
// Code goes here. 
#pragma GCC diagnostic pop
```

**Comment by dsieczko** [comment]
Thanks @kcoleman731
