### ISSUE TITLE
Image Cells are showing up blank

### ISSUE THREAD

**Issue by AdamBCo** [layerhq/Atlas-iOS#1166]
Whenever I am sending an image message, I see empty grey message cells with no image. 

Any idea what's going on?

![img_0054](https://cloud.githubusercontent.com/assets/4572275/14575167/fadc8cc4-0314-11e6-89f5-c17c2877fd77.PNG)

**Comment by logicsb** [comment]
The same problem here.

**Comment by AdamBCo** [comment]
@logicsb I looked into the SDK and it looks like the previewImagePart has no data, nor url. Were you able to fix it?

**Comment by AdamBCo** [comment]
@logicsb  

@maju6406 helped me find the solution by adding the following to your LayerClient:

    // Download all JPEG's, PNG's, GIF's automatically 
    self.layerClient.autodownloadMIMETypes = [NSSet setWithObjects:@"image/jpeg", @"image/png",@"image/gif",nil];

    // Download content that's up to 100 KB automatically
    self.layerClient.autodownloadMaximumContentSize = 1024 * 100;

You can find more here:
https://support.layer.com/hc/en-us/articles/204380184-I-try-to-send-an-image-using-Atlas-but-the-receiver-is-only-seeing-a-gray-square-

**Comment by logicsb** [comment]
@AdamBCo thanks very much :)
