### ISSUE TITLE
Atlas without Layer

### ISSUE THREAD

**Issue by Mrostgaard** [layerhq/Atlas-iOS#1176]
Hey. This is not an issue. 
i just want to know if i'm able to use the Atlas components with my own chat or do i need to use layerkit?

**Comment by JRam13** [comment]
Atlas is so tightly bound to Layer, it'll be a major doing, but it's possible. Remember, Atlas is open source.

**Comment by kcoleman731** [comment]
@Mrostgaard as @JRam13 pointed out, Atlas is indeed fully integrated with LayerKit.
