### ISSUE TITLE
messageInputToolbar is not visible sometimes

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1177]
In my app, I use an `NSCache` to save each of my `Conversation controller` (a sub-class of `ATLConversationViewController`) that is shown, so when popped out, and then re-pushed again, it will save its current state (the input text, if the user started to write, but did not hit send; the scrolling point, etc.), so next time its shown, the user would be able to continue where he/she stopped.

I just updated `Atlas` from 1.0.19 to the latest version (1.0.22), and now when a `Conversation controller` is re-pushed, the `messageInputToolbar` becomes invisible. I suspect its frame is not right, but I was not able to verify it.

Any idea what might cause it?

**Comment by kcoleman731** [comment]
Hi @oferRounds. The messageInputToolbar is set as the `inputAccessoryView` for the `LYRConversationViewController`s view. This property has proven to have some very weird behavior in the past so this doesn't surprise me. 

Have you tried putting your app in the View Hierarchy Debugger and verifying if it exists? Additionally, not sure if you saw this but the `ATLConversationViewController` preserves text in the toolbar for you already. No need to cache the entire controller.

**Comment by oferRounds** [comment]
Hi @kcoleman731 
Thanks for your response :)

I'll follow your suggestion and debug it in the View Hierarchy Debugger, but for now - two points:

1. I see now that it preserves the text, but I also see a bug with it: if the user leaves the conversation with the keyboard being shown, then his text is not being presented. If he then would leave it once again and then return again (now the keyboard are not shown), then the preserved text will be shown.

2. I would like to preserve not only the text, but also the last scrolling point, the keyboard state (presented or not). Maybe I could also save each of these manually, but I think saving the ViewController itself might be a better solution instead of going through each one and save them individually (assuming I do release it in the case of a memory warning).

**Comment by oferRounds** [comment]
Oh, I remembered now that I did try to debug it using he View Hierarchy Debugger but from some reason it failed to present this screen (in oppose to any other screens in my app, which were shown up). 

I can try it again - maybe it a was temporary bug on Xcode - but this was the issue why it was hard for me to debug it.

**Comment by oferRounds** [comment]
But I can say that it did exist - this I was able to verify (it wasn't nil, and it did have a non-zero frame).

**Comment by oferRounds** [comment]
Hi @kcoleman731 
Question: If I may ask, why did you decide to use the `inputAccessoryView`to present the `messageInputToolBar`? What happens when `LYRConversationViewControllers`'s view isn't the first responder, but `messageInputToolBar` is? Maybe a `firstResponder` issue is what causing both of this bugs?

**Comment by kcoleman731** [comment]
Hi @oferRounds. Ok thank you very much for the info. Let me do a bit more digging. 

We used the `inputAccessoryView` because it provides for moving the toolbar up and down when a dragging motion occurs...like how the toolbar moves in imessage. Unfortunately, if you don't use the `inputAccessoryView`, the OS only provides notifications for when a drag starts and when a drag ends, but not the intermediate position of a drag. With the `inputAccessoryView` the animation is handled for you.

Unfortunately, it has proven to be a tricky property, especially across OS upgrades :(.

**Comment by kcoleman731** [comment]
Hi @oferRounds I have been able to repro your situation. This isn't so much a bug as it is a product of trying to cache view controllers and reuse them in an unexpected way. We setup the toolbar in init and then reposition it as needed in multiple places including viewWillAppear. Reuse of the controller and subsequent calls to viewWillAppear are pushing the toolbar off screen.

My suggestion is to implement functionality in your subclass that will inject the state your controller needs and update the controller manually. So your cache shouldn't cache the actual controller, but rather the state of each controller as needed. Each time a conversation is selected you should create a fresh controller. 

Let me know if you have any questions on this.

**Comment by oferRounds** [comment]
Hi @kcoleman731 
Great input regarding the reasoning for your implementation - good to know that!
And regarding your last comment - sounds good! Thanks for your digging into it - your suggestion sounds good!
