### ISSUE TITLE
Question: Can I run query, for conversations for example, over a local data store of Layer?

### ISSUE THREAD

**Issue by ernestopino** [layerhq/Atlas-iOS#1178]
Hi everybody, 

This is not an issue, is a question. In the environment of my app, my ideal situation would be:

1. Using mail framework (MailCore2) to interact with an email inbox, obtain emails and transform them into a messages in memory (via Layer classes).
2. Save those messages into a local storage.
3. Run queries (via Layer classes) over local storage.
4. Present conversations and messages for authenticated user (via Atlas UI).

**Is this possible?**

Thanks in advance.
Regards,

cc/ @kcoleman731, @chipxsd, @blakewatters 

PS: Sorry my English ;)

**Comment by kcoleman731** [comment]
@ernestopino please email support@layer.com with functionality questions.
