### ISSUE TITLE
Ability to see blocked user's messages in group chat

### ISSUE THREAD

**Issue by mvalti** [layerhq/Atlas-iOS#1179]
Hi Atlas-Team,

I've noticed a strange behaviour when the Blocker and the Blockee  are in the same conversation with a third user, which isn't blocked by anyone. Because of the Layer's block policy the Blocker user only see the third user's messages and after a period, the messages in the conversation will be confused for the Blocker. 

Is it possible somehow to show the Blockee's messages in the groupchat for the Blocker as well?

I really appreciate any help you can provide.

**Comment by kcoleman731** [comment]
@mvalti just to get everything straight...Lets say UserA blocks UserB. UserC is the third party and is not blocked by either. 

You are saying that after a time, UserA can only see UserC's messages? But Altas is showing the messages as being sent from UserB?

**Comment by mvalti** [comment]
No, Atlas don't show the messages from the UserB  and that's the problem. The userA don't understand what's going on between UserB and UserC because he isn't able to see messages from UserB. After a time, the whole conversation will be a mess for the UserA.

What do you think about removing the block policy from the users in a group chat?

**Comment by feifanzhou** [comment]
@mvalti that is how blocking is designed to work — if `A` has blocked `B`, `A` cannot see `B`'s message. If this leads to a poor user experience for end users, you can implement some sort of UI to manage this — for example, when both `A` and `B` are added to a conversation, you can check for a block between them, and prompt them to unblock. We provide you with the tools to do so.
