### ISSUE TITLE
Use displayName property instead of firstName property when computing the text to show in addressBarTextView

### ISSUE THREAD

**Issue by adina-abduraman** [layerhq/Atlas-iOS#1180]
Hi Guys,

Is there a way to customize the property used for displaying names in addressBarTextView("To:"). For the moment you use firstName property, but I would like to use the fullName. So, isn't it better to use the displayName property, so that everyone can configure either fullname, firstName or fullName to show?

Let me know what you think,
Thanks

**Comment by kcoleman731** [comment]
@adina-abduraman I think this is fair. I won't be able to get to it till next week, but would be happy to review a PR for you ;). Should be pretty straightforward.

**Comment by RDorange** [comment]
@kcoleman731  Hi, any update on that ?
Many thanks 
Romain

**Comment by kcoleman731** [comment]
@adina-abduraman @RDorange have a look https://github.com/layerhq/Atlas-iOS/pull/1199. Thats all you are looking for?

**Comment by kcoleman731** [comment]
@adina-abduraman @RDorange merged https://github.com/layerhq/Atlas-iOS/pull/1199
