### ISSUE TITLE
How to send image for creating a group conversation ?

### ISSUE THREAD

**Issue by tariq235** [layerhq/Atlas-iOS#1185]
In our custom UI we have an option to create a group conversation using title, participants and image which can be selected using camera roll or by capturing a picture.

To create a group conversation we have to call this -
`LYRConversation *conversation = [layerClient newConversationWithParticipants:[NSSet setWithObjects:@"USER-IDENTIFIER", nil] options:nil error:&error];
`
and pass metadata like 

```
NSDictionary *metadata = @{@"title" : @"My Conversation",
                           @"theme" : @{
                                @"background_color" : @"333333",
                                @"text_color" : @"F8F8EC",
                                @"link_color" : @"21AAE1"},
                           @"created_at" : @"Dec, 01, 2014",
                           @"img_url" : @"/path/to/img/url"};
[self.conversation setValuesForMetadataKeyPathsWithDictionary:metadata merge:YES];

```

I am not getting what do you mean by img_url ? Should I upload image first to somewhere and then pass that url here which doesn't make sense as per user experience ? Or I have to store the image on disk and provide disk image url ?

**Please guide me how can I create a group conversation with image and title ?**

**Comment by maju6406** [comment]
Check your email. I responded to your support ticket. Let's keep the conversation going there.

**Comment by feifanzhou** [comment]
For posterity:

It doesn't matter to Atlas or Layer how you do it. We only take care of syncing metadata; we don't look at or use its contents anywhere. As a result, it's up to you to decide how you want to send the image. Uploading it somewhere like S3 and passing the URL is certainly one valid option. Passing a disk URL likely wouldn't make sense, unless your app bundle includes certain images that the users can choose from. Conceivably, you could also inline the image via base64 encoding, but I wouldn't recommend that except for really small images.
