### ISSUE TITLE
Block policy issues

### ISSUE THREAD

**Issue by mvalti** [layerhq/Atlas-iOS#1189]
Hi, Atlas-Team!

I've noticed some issues when adding and removing **LYRPolicies**.

First of all, let's introduce some members: **UserA**, **UserB**, **UserC**, **UserD**, **UserE**, **UserF**
and two devices: **DeviceA**, **DeviceB**
and two chat type: - **1to1** : Conversation between **2** members
                              #- **Group** : Conversation between **3 or more** members 
I am the **UserA** and I authenticate only to the **DeviceA**.

I create 1to1 chats with every single user (with UserB, with UserC, with UserD, with UserE, with UserF) separately and I also create a Group with UserB, UserC, and UserD, on **DeviceA**. I send and receive a lot of messages in every conversation. 

Adding a BlockPolicy is only allowed in 1on1 chats. 
Here is the method to get a blockPolicy for a participant:
```objective-c
- (LYRPolicy *)blockPolicyForParticipant:(LYRIdentity *)participant {
    NSOrderedSet *policies = self.layerClient.policies;
    NSPredicate *policyPredicate = [NSPredicate predicateWithFormat:@"SELF.sentByUserID = %@ AND SELF.type = %d", participant.userID, LYRPolicyTypeBlock];
    LYRPolicy *policy = [policies filteredOrderedSetUsingPredicate:policyPredicate].set.allObjects.firstObject;
    return policy;
}
```
Removing BlockPolicies are allowed both 1on1 and group chats:
- in 1on1 chat for unblocking a user I call the following method:

```objective-c
- (void)unBlockParticipant:(LYRIdentity *)participant  { 
    LYRPolicy *policy = [self.layerSessionManager blockPolicyForParticipant:participant];
    if (policy) {
        NSError *error = nil;
        BOOL success = [self.layerClient removePolicy:policy error:&error];
        if (success) {
            NSLog(@"Participant successfully unblocked");
        } else {
            NSLog(@"Participant unblock failed with error: %@",error.description);
        }
    }
}
```
- in Group chat to remove BlockPolicies from the participants I call the following method:

```objective-c
- (void)unblockParticipants:(NSArray *)participants {
    for (LYRIdentity *participant in participants) {
        [self unBlockParticipant:participant];
    }
}
```

I block the UserB, UserC, and UserD in the corresponding 1on1 chat. 
In my group conversation is placed a button that should unblock all the blocked users.

The layerClient.policies.count before removing the policies is 3.

**Issue 1**
If I go into the Group chat and I hit the Unblock button I'll expect that all the participant will be unlocked, but when I'll return to this conversation only the first policy from the layerClient.policies were removed. If I kill my app and return to this group everything looks fine and everybody got unblocked.
Also, I've logged the layerClient.policies.count before and after deleting the block policies and the count it was correct, but when I popped and pushed again the chat screen this count was 2 instead of 0. And after the app launch, it was 0 what is the expected value.

I tried to use semaphores inside the for loop to wait until a block remove method finishes but it doesn't work. 

Then I've tried to use a little delay between unblocks. That worked when the internet was good and the amount of the blocked participant was few, but for example 10 participant with not good connection didn't work.

**Issue 2**
After blocking some users (UserB, UserC, UserD) I've logged in to the DeviceB and I'm noticed that the conversations form DeviceA which contains unblocked users didn't synchronize with layer and didn't appeared in my ConversationListViewController. 

I've tried to unblock the users on the DeviceA but this didn't change nothing on the DeviceB. The conversations remained dissapeared.

Can you make a documentation about the whole blocking feature? How does it work in different cases? How should I handle multiple blocking/unblocking actions? 

I've found [this](https://support.layer.com/hc/en-us/articles/204050814) but it seems it's outdated.

I appreciate any help that you can provide.

mvalti

**Comment by kcoleman731** [comment]
@mvalti Thanks for your report. As this is a `LayerKit` issue, please email support@layer.com and we will be able to help you out!
