### ISSUE TITLE
Receiving push notification when a message recipient reads the message

### ISSUE THREAD

**Issue by adina-abduraman** [layerhq/Atlas-iOS#1190]
Hi guys,

It seems that I am getting a push notification when a recipient of one of my messages reads the message.
The payload I get looks like that:
Printing description of userInfo:
{
    aps =     {
        "content-available" = 1;
    };
    layer =     {
        "conversation_identifier" = "layer:///conversations/cef516b4-b471-4484-9bf3-5c82e6d58f58";
        "message_identifier" = "layer:///messages/9c24546d-6192-45d2-ba89-fbe041f14a6e";
    };
}

So no alert, badge, category, sound fields.

What should I do so that I won't receive these kind of push notifs, and only receive push notifs for received messages?

Thanks!

**Comment by feifanzhou** [comment]
Hi @adina-abduraman,
This is functioning as designed. We use _silent push notifications_ to deliver read receipts and sync hints. By default, these notifications should not display alerts or any other user-visible effects. If you'd like to disable this particular type of notification, simply stop sending read receipts.

**Comment by adina-abduraman** [comment]
Thanks for the answer!
So I should take care of not displaying anything to the user when these kind of notifs are displayed. Should I count on the field "alert" that is missing from the notif payload , for these kind  of notifications, so I can decide whether to display it to the user or not?

**Comment by feifanzhou** [comment]
Yes — a "full" notification will contain [more fields](https://developer.layer.com/docs/ios/guides#receiving-pushes) under the `apns` key. You opened this issue on the Atlas repo, so I assume you're using Atlas — if so, we automatically take care of displaying the right types of notifications.
