### ISSUE TITLE
Does Atlas/Layer caches messages on the device?

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1212]
Not sure if that's a Layer or Atlas issues, but it appears to me as if there is no caching for the messages/conversation, as when the internet reception is not at its best, it takes a long time for the content to appear

**Comment by chenyuan** [comment]
https://developer.layer.com/docs/ios/guides mentions followings

> Disk Space Management
You have the option to determine how much disk space Layer can use on the local device. If locally cached content goes above this limit, then assets will be deleted, with the least recently accessed content deleted first.
> 

```
//Sets the local disk space Layer is allowed to use (in bytes). Passing in a value of 
// 0 will remove the limit (this is the default behavior)
self.layerClient.diskCapacity = 1024 * 1024 * 50; //Sets the limit to 50 MB

//Check Layer's actual usage (in bytes)
long usage = self.layerClient.currentDiskUtilization;

//You can always choose to delete a Message Part (locally only - the server is not affected) 
NSError *error = nil;
LYRProgress *progress = [messagePart purgeContent:&error];
```

**Comment by oferRounds** [comment]
@chenyuan got you. 
I actually did not override the default behaviour, so I guess that is not the problem of the conversations and messages not shown instantly.

What is the experience that you're having? Do you see them load instantly?

**Comment by chenyuan** [comment]
Yup, I put following line in my AppDelegate

```swift
        // Layer
        sharedLayerClient.autodownloadMIMETypes = NSSet(objects: ATLMIMETypeImagePNG, ATLMIMETypeImageJPEG, ATLMIMETypeImageJPEGPreview, ATLMIMETypeImageGIF, ATLMIMETypeImageGIFPreview, ATLMIMETypeLocation) as? Set<String>
        sharedLayerClient.backgroundContentTransferEnabled = true
        sharedLayerClient.diskCapacity = 1024 * 1024 * 100 //Sets the limit to 100 MB
```

Now my conversation messages are loaded as soon as I get in a conversation view controller. I also checked the sandbox folders in the simulator, I found message images are cached in /Library/Caches/com.layer.layerkit

**Comment by oferRounds** [comment]
@chenyuan - Thanks again, I'll try that. Although it says in the docmentation:

> A value of zero (the default) indicates that an unlimited amount of disk space may be utilized.
