### ISSUE TITLE
Bubble message sometimes get cut off

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1225]
See here - this is an example with a Hebrew content. Not sure if that's related specifically to Hebrew, or that happens in general.

Last time I saw it, it happened when the app was launched from a Push message, which then immediately segued to the conversation. Maybe that might be a lead to the reproducible scenario.

See image bellow, last bubble:

**Comment by oferRounds** [comment]
![text_cut_off](https://cloud.githubusercontent.com/assets/1477963/16337008/dba8a36e-3a1a-11e6-99fb-7ac184a2199f.jpg)

**Comment by oferRounds** [comment]
The original text was: "יכול להיות שהיום כן שווה את הציצים"

One important note: when segueing away from the conversation and the segueing back in - the problem get fixed.

**Comment by AndreasL** [comment]
We are also experiencing this issue with english text.

**Comment by feifanzhou** [comment]
@oferRounds @AndreasL thanks for the report. Have you changed the default font size on the cell?

**Comment by oferRounds** [comment]
Hi @feifanzhou
Thanks for replying. Yes, I am using a different font - "AvenirNext-Regular", size: 16.0.

**Comment by feifanzhou** [comment]
There is a bug with cell layout computation depending on how you set the font. We are tracking this internally as `APPS-2540`. The working code path is to to set `ATLMessageCollectionViewCell.appearance.messageTextFont` in `viewDidLoad` of the controller.

(cc @daniel-maness)

**Comment by oferRounds** [comment]
@feifanzhou - thanks!

**Comment by oferRounds** [comment]
@feifanzhou - sorry, but this bug got reproduced again now, even after moving `ATLMessageCollectionViewCell.appearance.messageTextFont` to `viewDidLoad`.

**Comment by daniel-maness** [comment]
Setting `messageTextFont` for both `ATLIncomingMessageCollectionViewCell` and `ATLOutgoingMessageCollectionViewCell` instead of just `ATLMessageCollectionViewCell` within the `viewDidLoad` method above will resolve this.
