### ISSUE TITLE
Build Error for LayerKit 0.22.0

### ISSUE THREAD

**Issue by wooyukit** [layerhq/Atlas-iOS#1227]
Build Error for LayerKit 0.22.0

**Comment by logicsb** [comment]
try this:
`pod 'Atlas', :git => 'https://github.com/layerhq/Atlas-iOS.git', :branch => 'master'`

**Comment by feifanzhou** [comment]
https://github.com/layerhq/Atlas-iOS/issues/1231#issuecomment-230120264
