### ISSUE TITLE
Changing the list of participants and sending a message at the same time crash the collectionView

### ISSUE THREAD

**Issue by davideme** [layerhq/Atlas-iOS#1230]
I'm sending a message when someone is added or removed from a conversation, and this crash the collection view.

The 2 following methods are trigger:
- configureControllerForChangedParticipants
- queryControllerDidChangeContent

configureControllerForChangedParticipants by calling `[self.collectionView reloadData];`
queryControllerDidChangeContent by calling `[self.collectionView performBatchUpdates:^{`

crash because `- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView`
Does not correspond to the one expected.

**Comment by fmecklen** [comment]
We have the same problem. We create a conversation via REST api and add/ remove multiple participants and send messages to this conversation. I can't replicate the exact case but it crashes also on the same point.
