### ISSUE TITLE
Can't build after Update

### ISSUE THREAD

**Issue by danielwmsun** [layerhq/Atlas-iOS#1231]
I just updated to LayerKit v0.22.0 and Atlas v1.0.23

I am seeing a build error, specifically regarding LYTypingIndicator and the changes made from LayerKit v0.21.0 regarding that enum. 

For example: Use of undeclared identifier 'LYRTypingDidBegin' or 'LYRTypingDidFinish' or 'LYRTypingIndicatorValueUserInfoKey'

I've tried deleting both pods, cleaning, and then reinstalling again, but I still get the build errors.
Am I supposed to fix this manually?

**Comment by wooyukit** [comment]
Same with me

**Comment by cashmash** [comment]
Atlas is currently not ready for LayerKit 0.22.0 yet. I am sure they are working hard to adjust Atlas. Should be out soon.

**Comment by logicsb** [comment]
Try this:
`pod 'Atlas', :git => 'https://github.com/layerhq/Atlas-iOS.git', :branch => 'master'`

**Comment by feifanzhou** [comment]
Thanks @cashmash and @logicsb — we updated Atlas to support LayerKit 0.22.0 on `master`, so @logicsb's suggestion is correct. We didn't get a chance to publish a new version to CocoaPods yet; I expect that to happen on Tuesday (Monday is a US holiday).

**Comment by jyounus** [comment]
Why doesn't LayerKit follow semantic versioning? If something breaks, at least devs will know instantly. Also, is there a known date when the SDK/API will become stable?

Another suggestion would be to "hardcode" the LayerKit version Atlas used and not the ~> way.
