### ISSUE TITLE
Using SlackTextViewController

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1239]
I think Atlas could benefit from using SlackTextViewController, as it includes many small features + it's maintained regularly by the Slack team.

https://github.com/slackhq/SlackTextViewController

**Comment by feifanzhou** [comment]
@oferRounds thanks for the suggestion! At the moment we haven't planned any big changes like this — would you be interested in working on a PR?

**Comment by oferRounds** [comment]
@feifanzhou thanks! But currently I'm by self and swamped up with the launch of my app, which is coming up this month. So it won't be possible for me - time wise - currently. Sorry...

**Comment by feifanzhou** [comment]
No worries — closing since this isn't actionable right now.

**Comment by oferRounds** [comment]
👍
