### ISSUE TITLE
ATLConversationViewController DataSource method not called - conversationViewController:participantForIdentity:

### ISSUE THREAD

**Issue by danielwmsun** [layerhq/Atlas-iOS#1240]
I have a subclass of ATLConversationViewController that is instantiated once a user clicks on a conversation cell in my ATLConversationListViewController subclass.

I've set the delegate and dataSource to be my subclasses conversationViewController. However, the dataSource method conversationViewController:participantForIdentity is not being called.

Why is this the case? I need this dataSource method to be called so that my participant information is synced with Layer's LYRIdentity so that the displayName is updated for push notifications

**Comment by stephencroberts** [comment]
What was your solution? I'm seeing this as well.
