### ISSUE TITLE
ATLAddressBarViewController.h file not found

### ISSUE THREAD

**Issue by JoeFerrucci** [layerhq/Atlas-iOS#1243]
I'm getting the following errors:

`ATLAddressBarViewController.h` **file not found**
**and**
`Could not build Objective-C module 'Atlas'`

Not sure why. I tried adding `${POD_ROOT}/**` to **User Header Search Paths** and that caused a bunch of other stuff to break, like Realm. 

@kmahal @maju6406 

**Cocoapods version 1.0.1**
**Atlas 1.0.15**
**LayerKit 0.17.7**

**Comment by feifanzhou** [comment]
The latest Atlas is [1.0.26](https://github.com/layerhq/Atlas-iOS/releases/tag/v1.0.26), which includes updates to support Cocoapods 1.0.1 (including fixes for this issue). Note that you'll also need to update to [LayerKit 0.22.0](https://github.com/layerhq/releases-ios/releases/tag/v0.22.0).
