### ISSUE TITLE
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: Alamofire, GooglePlaces, and ObjectMapper" while installing pod file in terminal"

### ISSUE THREAD

**Issue by anpuAnand** [layerhq/Atlas-iOS#1245]

**Comment by anpuAnand** [comment]
i got this when i use objective c in my project

**Comment by anpuAnand** [comment]
while installing pod file

**Comment by feifanzhou** [comment]
@anpuAnand it doesn't sound like you're actually having an issue with Atlas. You simply need to add the line `use_frameworks!` to your [Podfile](https://guides.cocoapods.org/using/the-podfile.html).
