### ISSUE TITLE
Entering a newline causes the text view to render an empty space at the top

### ISSUE THREAD

**Issue by elitalon** [layerhq/Atlas-iOS#1264]
It seems that a [workaround for iOS 7](https://github.com/layerhq/Atlas-iOS/blob/03dd9b03b326f89def93fdac6c8b8a8da475c063/Code/Views/ATLMessageInputToolbar.m#L309-L314) in `ATLMessageInputToolbar` is causing some rendering issues when dealing with newlines.

Entering a newline resizes the text view due to a change in the content offset, which adds an empty space above the text:

![extra_space](https://cloud.githubusercontent.com/assets/684464/18838850/264d8d16-8409-11e6-8fff-1cdd1286218a.png)

Typing another character sets the content offset again and everything gets back to normal:

![back_to_normal](https://cloud.githubusercontent.com/assets/684464/18838856/2b2ed240-8409-11e6-85ba-bcfa316b4b2b.png)

Removing that workaround fixes the issue, but I haven't tested if it breaks something else.

Tested with iOS 9.3.5, LayerKit 0.22.0 and Atlas 1.0.27.

**Comment by daniel-maness** [comment]
This has been resolved in v1.0.29
