### ISSUE TITLE
Flashing behaviour when popping conversation is still present on iOS 9

### ISSUE THREAD

**Issue by elitalon** [layerhq/Atlas-iOS#1266]
The [workaround for dismissing the keyboard](https://github.com/layerhq/Atlas-iOS/blob/03dd9b03b326f89def93fdac6c8b8a8da475c063/Code/Controllers/ATLBaseConversationViewController.m#L155-L160) in a conversation when popping back to the conversation list seems to be still needed in iOS 9. I am experiencing the same issue and increasing the number to 10 fixes the flashing also in iOS 9.

Tested with iOS 9.3.5, LayerKit 0.22.0 and Atlas 1.0.27 and also with [the demo app](https://github.com/layerhq/Atlas-Messenger-iOS).

**Comment by daniel-maness** [comment]
This has been merged and resolved in v1.0.29
