### ISSUE TITLE
Activity indicator does not appear in all cases when loading the conversation history

### ISSUE THREAD

**Issue by elitalon** [layerhq/Atlas-iOS#1267]
I have setup a client with the following history synchronisation settings:

```swift
let clientOptions = LYRClientOptions()
clientOptions.synchronizationPolicy = .PartialHistory;
clientOptions.partialHistoryMessageCount = 20;

let client = LYRClient(appID: layerApplicationURL, delegate: self, options: clientOptions)
```

Maybe I'm missing something else here, but the activity indicator doesn't appear in all cases when scrolling back in the conversation history.

In particular, I think it only appears if there are more than one pagination window and only from the second window on. However, I haven't been able to reproduce this scenario every time either.

Tested with iOS 9.3.5, LayerKit 0.22.0 and Atlas 1.0.27 and also with [the demo app](https://github.com/layerhq/Atlas-Messenger-iOS).

**Comment by markkrenek** [comment]
Fixed in cb496400ae1a43732b716b3a33b52b8c2f2e7b1f on master
