### ISSUE TITLE
Asserting for query controller being nil in -viewWillAppear conflicts with notification

### ISSUE THREAD

**Issue by elitalon** [layerhq/Atlas-iOS#1272]
In `ATLConversationListViewController`, there is [an assertion inside of `-setupConversationQueryController`](https://github.com/layerhq/Atlas-iOS/blob/bf51210750bf47c115aabd37b451e3bc4a614337/Code/Controllers/ATLConversationListViewController.m#L243) that checks the current value of `queryController` before initialising it.

However, `setupConversationQueryController` is [also called from `-layerClientDidAuthenticate:`](https://github.com/layerhq/Atlas-iOS/blob/bf51210750bf47c115aabd37b451e3bc4a614337/Code/Controllers/ATLConversationListViewController.m#L279-L284) in response to a notification whenever the client authenticates.

The problem with this logic is that if the view has not appeared yet but it's already loaded in memory, the view controller is observing those notifications. If a notification is posted and handled before the view appears, that assertion will always trigger.

Wouldn't be a better approach to start listening for notifications once the view has appeared or after `queryController` is set up the first time?

**Comment by daniel-maness** [comment]
Hey @elitalon I think you're absolutely correct here. I'm going to move it to the end of `viewWillAppear` after the queryController has already been set up. Thanks!
