### ISSUE TITLE
Generation of key pair failed with result code -34018

### ISSUE THREAD

**Issue by BeamerCola** [layerhq/Atlas-iOS#1276]
Running Swift 2 on Xcode 8 I'm getting this error on `connectWithCompletion`

Has anybody seen this?

**Comment by daniel-maness** [comment]
@BeamerCola We've had a couple reports of this and it seems to be an issue with Xcode 8. [Here is a solution](http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator) that has worked for others you may try. Let me know how it works out for you.

**Comment by BeamerCola** [comment]
Worked great
