### ISSUE TITLE
Custom left accessory button in ATLConversationViewController

### ISSUE THREAD

**Issue by peterklima** [layerhq/Atlas-iOS#1344]
Hi guys!
How can I modify the leftAccessoryButton? I’m currently replacing it with another UIButton in my subclassed ATLConversationViewController in the viewDidLoad method. Unfortunately the button is not displayed.

(void)viewDidLoad {
    [super viewDidLoad];
    UIAnimatedButton* button = [UIAnimatedButton buttonWithType:UIButtonTypeCustom];
    button.frame = CGRectMake(0, 0, 40, 40);
    [button.imageView setContentMode:UIViewContentModeScaleAspectFit];
    [button setImage:[UIImage imageNamed:@"ic_button"] forState:UIControlStateNormal];
    [button addTarget:self action:@selector(onButton) forControlEvents:UIControlEventTouchUpInside];
    self.messageInputToolbar.leftAccessoryButton = button;
}

![screen shot 2017-01-30 at 12 23 26](https://cloud.githubusercontent.com/assets/1203988/22421384/20c9f38e-e6e7-11e6-9b56-b16e39602324.png)

**Comment by peterklima** [comment]
Anybody?

**Comment by fmecklen** [comment]
Hey Peter, just use the property "leftAccessoryImage" of the "messageInputToolbar"

`self.messageInputToolbar.leftAccessoryImage = [UIImage imageNamed:@"plus_chat"];`

**Comment by peterklima** [comment]
Thanks for the quick response, but I also want a custom action. Do you know how I can add it?

**Comment by fmecklen** [comment]
When you add the delegate then you have a custom action. On the delegate you can do what ever you want. I show there a custom UIAlertController

**Comment by peterklima** [comment]
Ok, thanks a lot. 
Any explanation why the first approach was not successful?

**Comment by fmecklen** [comment]
You're welcome. There isn't any setter for the left button
