### ISSUE TITLE
Crash in ATLConversationListViewController in latest Atlas 

### ISSUE THREAD

**Issue by edwinruan** [layerhq/Atlas-iOS#1348]
I have an crash issue regarding to Altas 1.0.31 and cocoapod 1.2.0.

  When entering the conversation list page, the app will crash in Altas. The tableview updates with matching number of rows.

  When using old cocoapod 0.39.0. and Altas 1.0.30, it is working fine.

   Could you help me with that?  Thanks.

PS: attached is crash log.

    Class:

    `ATLConversationListViewController`

    Method name :

    `- (void)setupConversationQueryController`

   Line number:

   `BOOL success = [self.queryController execute:&error];`

   

> 2017-02-03 17:44:22.548[96897:560003] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UITableView.m:1610

> 2017-02-03 17:44:25.134[96897:560003] WARNING: GoogleAnalytics 3.17 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (16) must be equal to the number of rows contained in that section before the update (16), plus or minus the number of rows inserted or deleted from that section (16 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

> 2017-02-03 17:44:25.178[96897:560003] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
> 2017-02-03 17:44:30.168[96897:560003]

>  *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (16) must be equal to the number of rows contained in that section before the update (16), plus or minus the number of rows inserted or deleted from that section (16 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
> *** First throw call stack:
> (
>     0   CoreFoundation                      0x000000010d116d4b __exceptionPreprocess + 171
>     1   libobjc.A.dylib                     0x000000011183621e objc_exception_throw + 48
>     2   CoreFoundation                      0x000000010d11ae42 +[NSException raise:format:arguments:] + 98
>     3   Foundation                          0x000000010e2a066d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
>     4   UIKit                               0x000000010fa6c77d -[UITableView _endCellAnimationsWithContext:] + 17558
>     5   Atlas                               0x000000010c2bf6f8 -[ATLConversationListViewController queryControllerDidChangeContent:] + 88
>     6   LayerKit                            0x000000010e8a2081 __65-[LYRQueryController updateWithObjectIdentifiers:changedObjects:]_block_invoke.202 + 74
>     7   LayerKit                            0x000000010e8a060b -[LYRQueryController executeOnMainThread:] + 56
>     8   LayerKit                            0x000000010e8a1ef7 __65-[LYRQueryController updateWithObjectIdentifiers:changedObjects:]_block_invoke + 1015
>     9   LayerKit                            0x000000010e8a1a0a -[LYRQueryController inUpdateTransaction:] + 66
>     10  LayerKit                            0x000000010e8a1ac7 -[LYRQueryController updateWithObjectIdentifiers:changedObjects:] + 153
>     11  LayerKit                            0x000000010e8a168e -[LYRQueryController executeWithChangedObjects:error:] + 677
>     12  LayerKit                            0x000000010e8a1148 __30-[LYRQueryController execute:]_block_invoke + 32
>     13  libdispatch.dylib                   0x0000000112b960cd _dispatch_client_callout + 8
>     14  libdispatch.dylib                   0x0000000112b732b6 _dispatch_barrier_sync_f_invoke + 340
>     15  LayerKit                            0x000000010e8a10d8 -[LYRQueryController execute:] + 155
>     16  Atlas                               0x000000010c2bd01a -[ATLConversationListViewController setupConversationQueryController] + 1658
>     17  Atlas                               0x000000010c2bb7c7 -[ATLConversationListViewController viewWillAppear:] + 167
>     18  UIKit                               0x000000010fad596f -[UIViewController _setViewAppearState:isAnimating:] + 692
>     19  UIKit                               0x000000010fad607f -[UIViewController __viewWillAppear:] + 147
>     20  UIKit                               0x000000010fb10fb8 -[UINavigationController _startTransition:fromViewController:toViewController:] + 847
>     21  UIKit                               0x000000010fb11ef9 -[UINavigationController _startDeferredTransitionIfNeeded:] + 874
>     22  UIKit                               0x000000010fb12fdb -[UINavigationController __viewWillLayoutSubviews] + 58
>     23  UIKit                               0x000000010fd09dd7 -[UILayoutContainerView layoutSubviews] + 223
>     24  UIKit                               0x000000010f9f2ab8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1237
>     25  QuartzCore                          0x000000010f302bf8 -[CALayer layoutSublayers] + 146
>     26  QuartzCore                          0x000000010f2f6440 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
>     27  QuartzCore                          0x000000010f2f62be _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
>     28  QuartzCore                          0x000000010f284318 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 280
>     29  QuartzCore                          0x000000010f2b13ff _ZN2CA11Transaction6commitEv + 475
>     30  UIKit                               0x000000010f926d9b _UIApplicationFlushRunLoopCATransactionIfTooLate + 206
>     31  UIKit                               0x000000011013177c __handleEventQueue + 5672
>     32  CoreFoundation                      0x000000010d0bb761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
>     33  CoreFoundation                      0x000000010d0a098c __CFRunLoopDoSources0 + 556
>     34  CoreFoundation                      0x000000010d09fe76 __CFRunLoopRun + 918
>     35  CoreFoundation                      0x000000010d09f884 CFRunLoopRunSpecific + 420
>     36  GraphicsServices                    0x0000000113f57a6f GSEventRunModal + 161
>     37  UIKit                               0x000000010f92dc68 UIApplicationMain + 159
>     38  PSAdvisor                           0x000000010ae26e92 main + 114
>     39  libdyld.dylib                       0x0000000112be268d start + 1
> )

**Comment by rivera-ernesto** [comment]
Having the exact same issue. Reverting to `1.0.30`.

**Comment by edwinruan** [comment]
@rivera-ernesto Does reverting to 1.0.30 work for you?

**Comment by rivera-ernesto** [comment]
It still crashes. I had to add a flag in `queryControllerWill'/'DidChangeContent` to avoid doing anything in between them.

**Comment by edwinruan** [comment]
Just figured out a fix  for that. 
In `ATLConversationListViewController.m` class, method `viewDidLoad`,
add 
> self.tableView.tableFooterView = ATLMakeLoadingMoreConversationsIndicatorView();

before 

>  [self configureLoadingMoreConversationsIndicatorView];
 
The tableview footer does not have an IndicatorView instance initialized.

refer to this commit for more details:
[https://github.com/layerhq/Atlas-iOS/commit/133ca3e8b54898e4c943129d5d1142e72809df4f](url)

The file looks like this:

`- (void)viewDidLoad {`
  `  [super viewDidLoad];`
   ` self.title = ATLLocalizedString(@"atl.conversationlist.title.key",ATLConversationListViewControllerTitle, nil);`
   ` self.accessibilityLabel = ATLConversationListViewControllerTitle;`
  `  self.tableView.accessibilityLabel = ATLConversationTableViewAccessibilityLabel;
    self.tableView.accessibilityIdentifier = ATLConversationTableViewAccessibilityIdentifier;
    self.tableView.isAccessibilityElement = YES;`
   ` //tablefooterview initialization: create an IndicatorView instance `
    **self.tableView.tableFooterView = ATLMakeLoadingMoreConversationsIndicatorView();**
   ` [self configureLoadingMoreConversationsIndicatorView];
    [self.tableView registerClass:self.cellClass forCellReuseIdentifier:ATLConversationCellReuseIdentifier];`

**Comment by daniel-maness** [comment]
Thanks, I included this fix in Atlas 1.0.32

**Comment by toandk** [comment]
still happened in v1.1.1

`Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UITableView.m:1610
2017-07-28 17:55:42.259 TKN DevRelease[86839:1523042] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (28) must be equal to the number of rows contained in that section before the update (28), plus or minus the number of rows inserted or deleted from that section (3 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a907d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001105f421e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a90be42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010b91366d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   UIKit                               0x000000010e2a677d -[UITableView _endCellAnimationsWithContext:] + 17558
	5   Atlas                               0x00000001096e310a -[ATLConversationListViewController queryControllerDidChangeContent:] + 490
	6   LayerKit                            0x000000010c8a34e6 __76-[LYRQueryController updateWithObjectIdentifiers:changedObjectsIdentifiers:]_block_invoke.239 + 74
`
