### ISSUE TITLE
Wrong Header File

### ISSUE THREAD

**Issue by taimur** [layerhq/Atlas-iOS#1365]
Whenever we run command in pods to install the Atlas-iOS Framework. We get errors in all the files where the '_LayerKit_' is imported. There are around 8 files where we need to change this line.
This is how we do it. Can someone please look into this.

Original line after import _@import LayerKit;_

Had to change it to
_#import <LayerKit/LayerKit.h>_

**Comment by jpmcglone** [comment]
We should probably just use  `#import <LayerKit/LayerKit.h>` everywhere. I think this has to do with modules.

In your Podfile, are you using `use_frameworks!` or no? I think adding `use_frameworks` will make it Just Work™
