### ISSUE TITLE
EditButtonItem appears when there are no conversations

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#1372]
Hi, is there a way to make the `editButtonItem` — which shows up when `allowsEditing` is set to `true` — to not be there when there is nothing to edit, i.e., no conversations?

**Comment by daniel-maness** [comment]
@oferRounds By default we only setup the edit button when the view appears. You could check for the conversation count each time `ATLConversationListViewController:queryControllerDidChangeContent:queryController` fires and write some code to toggle the button based on the count. Feel free to submit a PR with your changes if you implement a good solution for this :)
