### ISSUE TITLE
Error installing Atlas via Carthage

### ISSUE THREAD

**Issue by jamiepinkham** [layerhq/Atlas-iOS#1384]
My Cartfile contains an entry for `Atlas-iOS`

```
github "layerhq/Atlas-iOS"
```

However, when attempting to build the dependency using `Carthage` the `Atlas-iOS` framework is skipped because the project does not have any shared framework schemes.

Output from `carthage update Atlas-iOS`

```
*** Skipped building Atlas-iOS due to the error:
Dependency "Atlas-iOS" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/layerhq/Atlas-iOS/issues/new
```

**Comment by feifanzhou** [comment]
Addressed in #1409
