### ISSUE TITLE
Feature Request: onMessageReceived listener?

### ISSUE THREAD

**Issue by acelix** [layerhq/Atlas-iOS#1389]
Is it possible to have an onMessageReceived(LYRMessage message) type listener?
How would we go about knowing that a message is received in a ATLConversationViewController subclass? I want to do some data arranging to a message before displaying it.

Well I guess I do it with the NSNotification handler on data changed

**Comment by daniel-maness** [comment]
@acelix You can add an observer to `LYRClientObjectsDidChangeNotification` and perform any new message operations there. For example, here is that function in `ATLConversationViewController` you can use as a reference:

https://github.com/layerhq/Atlas-iOS/blob/master/Code/Controllers/ATLConversationViewController.m#L830
