### ISSUE TITLE
SearchBar does not stick to top when cancelling search in ATLParticipantTableViewController

### ISSUE THREAD

**Issue by edwinruan** [layerhq/Atlas-iOS#1393]
How to reproduce?
Go to Conversation ->  tap AddContactsButton in Address bar 
 -> present ATLParticipantTableViewController.
 -> type in something in search bar and to see the result. 
 -> tap cancel button in search bar. 

Result:
The search bar won't stick to the top, there is some empty space in between. 

![img_0913](https://cloud.githubusercontent.com/assets/14810193/26513694/7ee1d7b0-4232-11e7-8820-fc1c0c28640a.PNG)

**Comment by daniel-maness** [comment]
@edwinruan I tested on our Atlas Messenger app and am not experiencing this behavior. Is this repeatable for you every time? Are you doing anything extra in your delegate method for `participantTableViewController:didSearchWithString` that might cause this?

**Comment by edwinruan** [comment]
@daniel-maness   Thanks! Yea,  it is repeatable every time. We did use the delegate method `participantTableViewController:didSearchWithString`. We just do a filtering to the participant datasource and pass it to the completion block.  There is UI involved. 
PS: The issue only happens when we embed the participantTableViewController in NavigationController, it works fine when the VC is presented directly.

**Comment by edwinruan** [comment]
Just found out that the issue is related to iOS.  The scroll view’s content insets is automatically adjusted when navigation bar is translucent.
`navigationController.navigationBar.isTranslucent = true`
`navigationController.automaticallyAdjustsScrollViewInsets = true`
