### ISSUE TITLE
ATLParticipantTableViewController not able to hide presenceStatus

### ISSUE THREAD

**Issue by edwinruan** [layerhq/Atlas-iOS#1394]
In Atlas v1.1.0,  it introduces `presenceStatusEnabled` with default ‘YES’.  We want  to disable presenseStatus since we have similar features in our app. 

It allows use to do so through `ATLAvatarView`. But in `ATLParticipantTableViewController`, there is not delegate/property.
 
Is there a way to hide presenceStatus in `ATLParticipantTableViewController`?

![partcipant](https://cloud.githubusercontent.com/assets/14810193/26641729/1a9797aa-45f1-11e7-84a4-0226ce7cc81f.png)

**Comment by sara-shokry** [comment]
I also have the same issue, I can't call the presenceStatusEnabled function

**Comment by sara-shokry** [comment]
@edwinruan i fixed it by adding this  line  [[ATLAvatarView appearance] setPresenceStatusEnabled:false]
while i'm intitalizing ATLParticipant

**Comment by edwinruan** [comment]
@sara-shokry  Thank you very much for your solution. It should fix that.

**Comment by daniel-maness** [comment]
@edwinruan thanks for pointing this out. I'll have a fix ready soon!

**Comment by daniel-maness** [comment]
PR for this is undergoing review and should be merged and released soon.
https://github.com/layerhq/Atlas-iOS/pull/1405
