### ISSUE TITLE
Incompatibility with the safe area layout guides on iOS 11

### ISSUE THREAD

**Issue by joshtheancraite** [layerhq/Atlas-iOS#1426]
This issue affects the iPhone X as the edges of the conversation view and possibly more, exceed the safe areas. 

- In landscape, the top notch covers part of the conversation on either side.
- In portrait, the bottom notch covers the message input bar.

**Comment by rvishal1991** [comment]
Yes, iPhone X has the issue while using conversation view.

In portrait mode, the bottom notch covers the message input bar, so we have issues while using conversion view from ATLAS/Layer.

**Comment by alekseevpg** [comment]
Any workarounds?

**Comment by joshtheancraite** [comment]
@alekseevpg not officially, what I've done is create the conversation view to interact directly with Layer :/

**Comment by tomburns** [comment]
Is there an ETA on iOS 11 support? we're just starting to integrate, and I'm not sure whether to wait or just go ahead and build out the custom pieces that work.

**Comment by rvishal1991** [comment]
Any update on this?

**Comment by joshtheancraite** [comment]
@tomburns that's what we've had to do as well... a week to go and still no word. @rvishal1991 unfortunately, no.
