### ISSUE TITLE
/apps/%/atlas_identities

### ISSUE THREAD

**Issue by francoismart** [layerhq/Atlas-iOS#182]
Hi
When user register with my custom backend it's ok then it asks for user details to the following uri
Could you please let us know a sample of what details needs to be returned as the online heroku is down ....
Have nice day
FM

**Comment by kmahal** [comment]
Hi Francois,

Please refer to our online documentation regarding authentication of the `LYRClient`: https://developer.layer.com/docs/guides/ios#authentication.  There are examples provided in different languages for your convenience.  Layer provides a sample backend just for testing purposes, and all production apps should use their own.

Let me know if I can help you further or if you have more questions.

Thanks,
Kabir
