### ISSUE TITLE
'LayerKit/LayerKit.h' file not found

### ISSUE THREAD

**Issue by danipralea** [layerhq/Atlas-iOS#285]
Hello !
I get this error by trying to build my project, with the newly added Atlas functionality in it, but I get this error. This appears when trying to integrate it manually, without the cocoapods.
Where can I find the actual LayerKit framework ?

Later edit : I eventually found it in the repository retrieved with CocoaPods. You might want to add this to the installation instructions, I personally do not use CocoaPods in any of my projects. It adds too much overhead for little to no advantages.

Thanks in advance,
Danut Pralea.

**Comment by kcoleman731** [comment]
@danipralea Atlas has LayerKit as a dependency in its Podspec so if you pull in Atlas via Cocoapods, you will automatically get LayerKit as well. 
 
If pulling in manually however, you'll have to do the same with LayerKit. We should definitely call this out in the readme so thank you for the suggestion. I'll go ahead and make the change.

**Comment by kcoleman731** [comment]
@danipralea Readme has been updated. Thanks!
