### ISSUE TITLE
README has invalid code for ATLConversationViewController

### ISSUE THREAD

**Issue by veddermatic** [layerhq/Atlas-iOS#408]
The __Initialization__ section of the __ATLConversationViewController__ part of the README says to do this:

     ATLConverationViewController *viewController = [ATLConversationViewController conversationViewControllerWithConversation:conversation layerClient:self.layerClient];

However, that method does not exist in `ATLConverationViewController`. Did you mean `conversationViewControllerWithLayerClient:`? If so, maybe document how one passes in the conversation to display as well.

**Comment by danipralea** [comment]
Noticed that too. It seems that is a total inconsistence between the LayerKit and Atlas, like it was developed without any link between them.

**Comment by kcoleman731** [comment]
Hi @veddermatic Thank you very much for the heads up on the error in the docs. This was a previous initializer for the ATLConversationViewController. We moved the conversation param to a setter on the controller as it can now be used with an empty conversation....ie starting a new one. 

I'll go ahead and update the docs. My apologies for any confusion.

**Comment by kcoleman731** [comment]
@veddermatic @danipralea docs have been updated. Thank you both.

**Comment by danipralea** [comment]
Thank you as well for all your great work

**Comment by kcoleman731** [comment]
No worries at all @danipralea. Thanks for the kind words.
