### ISSUE TITLE
Do not receive messages

### ISSUE THREAD

**Issue by danipralea** [layerhq/Atlas-iOS#735]
Is there any obvious reason why I do not receive messages ?
I have got to the point of implementing everything and actually send a message, but the other client fails to receive it.

I also registered for LYRClientObjectsDidChangeNotification, but it also notifies only the sender. For the creation of the message, and state changes.

Any lead on this ?
Thanks in advance,
Danut Pralea.

**Comment by kmahal** [comment]
Hi Danut,

I'd be happy to help.  Without going through the code I can't specify the exact reason, but here are a few possible reasons that could cause that to happen:

1. The layerClient isn't authenticated and connected for the sender or receiver.
2. The conversation participants aren't correct, and potentially don't include the correct userId that the receiver's layerClient is registered with.
3. Do the conversations not show up in the `ATLConversationListViewController` subclass, or do the messages not show up in the `ATLConversationViewController` subclass?  This will help diagnose potential issues.

Let me know if you have any further questions.

Thanks,
Kabir

**Comment by danipralea** [comment]
The layer client is connecting and authenticating as well.

I managed somehow to receive a message and this is the output in the didChange delegate method :
message created : <LYRMessage:0x174709870 identifier=layer:///messages/6a0d9412-a8c0-4c20-8bd4-2aae9d698466 databaseIdentifier=26 index=0 seq=2 version=0 isDeleted=NO parts=(
    "<LYRMessagePart:0x17034a240 identifier=layer:///messages/6a0d9412-a8c0-4c20-8bd4-2aae9d698466/parts/0 MIMEType=text/plain size=6 databaseIdentifier=26 version=0 transferStatus=LYRContentTransferComplete data=\"fthfth\">"
) conversation=<LYRConversation:0x1704f5680 identifier=layer:///conversations/58a816c2-50af-4b40-8745-d813da49449f databaseIdentifier=17 version=0 isDeleted=NO streamUUID=38BE3716-C137-11E4-974C-C3080D00303F participants={(
    0,
    45
)}>>

It seems that the participants array is not properly configured, because it displays 0 for the current user's id.

2. When I present my ```ATLConversationViewController``` subclas I am creating each time a new conversation with my participant id and the other one's id. Should I not do that and fetch if there is already an existing conversation between the two users ? If so, how do I do that ? By using queries ?

3. I do not need a subclass to the conversations list controller, because I want to chat directly with the in-app user being viewed, but I have created a direct ATLConversationListViewController instance. Should I subclass it necessarly ? If not, I cannot see any conversations there.

**Comment by kmahal** [comment]
The creator's `authenticatedUserId` is added to the `LYRConversation

**Comment by danipralea** [comment]
I have found the problem at the first level, at least. And that is the client is connecting, but when authenticating, I'm sending my current user id for authentication, which is different than 0, but the layer client seem to be already authenticated, but with user id 0.

So basically when doing
```objc
NSLog(@"authenticating with  userID : %@", userID);
[self authenticateLayerWithUserID:userID completion:^(BOOL success, NSError *error) {
            }];
```

it enters here :
```objc
- (void)authenticateLayerWithUserID:(NSString *)userID completion:(void (^)(BOOL success, NSError * error))completion
{
    // If the user is authenticated you don't need to re-authenticate.
    if (self.layerClient.authenticatedUserID) {
        NSLog(@"Layer Authenticated as User %@", self.layerClient.authenticatedUserID);
        if (completion) completion(YES, nil);
        return;
    }
}
```

so the output is :
```objc
2015-03-03 09:32:50.643 MyApp[1102:54737] authenticating with  userID : 53
2015-03-03 09:32:50.644 MyApp[1102:54737] Layer Authenticated as User 0
```

**Comment by danipralea** [comment]
I somehow surpassed this issue. Do not ask me how :laughing: 
I have basically got to the point where I am receiving the messages, but do not know how to handle them, as I have not seen dataSource methods for the actual messages.
Should I add them somewhere or the incoming messages should appear automatically on screen ? 
Thanks in advance.

**Comment by danipralea** [comment]
Nevermind, I finally got it working, and really good as well.
Just as a note (might be a bug or not), creating a new conversation need to have myself included as a participant to the conversation. Otherwise, it will create the conversation with only the other chat participant.

Thanks for all your hard and awesome work !
Danut Pralea.
