### ISSUE TITLE
Crash in ATLTypingIndicatorViewController

### ISSUE THREAD

**Issue by timgshi** [layerhq/Atlas-iOS#741]
Looks like it's written to grab arrays from `participants` but according to apple documentation it should return sets. A crash happens on line 101 (see crashlytics link). http://crashes.to/s/ab05c4880ea

```
- (NSString *)textWithParticipants:(NSOrderedSet *)participants
{
    NSUInteger participantsCount = participants.count;
    if (!participantsCount) {
        return nil;
    }
    
    NSMutableArray *fullNameComponents = [[participants valueForKey:@"fullName"] mutableCopy];
...
}
```

**Comment by kcoleman731** [comment]
Hi @timgshi  Thanks for this one. Will get a fix pushed shortly.

**Comment by kmahal** [comment]
Hi @timgshi, thanks again for point this out.  We've fixed the issue and updated master with the changes.
