### ISSUE TITLE
Pushing ATLMConversationViewController without animation

### ISSUE THREAD

**Issue by woutergoossens** [layerhq/Atlas-iOS#743]
Hi,

I am using Atlas as example for my application.
In the ATLMConversationListViewController I want to push ATLMConversationViewController without animation.

But when I do that the bubbles and bottom bar are showed with a weird animation.
Is there any way to disable that?

So in ATLMConversationListViewController 298
[self.navigationController pushViewController:conversationViewController animated:NO];

Thanks, 

Wouter

**Comment by kmahal** [comment]
Hi @woutergoossens we'll look into it and get back to you.  Thanks.

Kabir

**Comment by kcoleman731** [comment]
@woutergoossens This is fixed on master with the following PR

https://github.com/layerhq/Atlas-iOS/pull/753

Thank you!

**Comment by woutergoossens** [comment]
Hi,

I have updated that code but the issue exists.

When I push the conversation controller without animation, the text and other elements appear animated..

Wouter

**Comment by kcoleman731** [comment]
Hi @woutergoossens this fix is not tagged yet and is on master. Feel free to point your pod at master and you should be good to go!
