### ISSUE TITLE
Subclass ATLMessageInputToolbar

### ISSUE THREAD

**Issue by woutergoossens** [layerhq/Atlas-iOS#744]
Hi,

What is the best way to subclass ATLMessageInputToolbar?

In the documentation:
self.inputAccessoryView = [ATLMessageInputToolbar inputToolBarWithViewController:self];

but inputToolBarWithViewController does not exist.

Thanks

Wouter

**Comment by kmahal** [comment]
Thanks @woutergoossens for pointing that out about our documentation.  In `ATLBaseConversationViewController` we initialize the `ATLMessageInputToolbar` like this:

```objc
    self.messageInputToolbar = [ATLMessageInputToolbar new];
    // An apparent system bug causes a view controller to not be deallocated
    // if the view controller's own inputAccessoryView property is used.
    self.view.inputAccessoryView = self.messageInputToolbar;
```

We'll be sure to update our docs to reflect that accordingly.  You can subclass it as you see fit now.

Kabir

**Comment by woutergoossens** [comment]
HI @kmahal 

Thanks for the fast reply.
I am using cocoapods to implement Atlas in my application so I can not just change the code in ATLBaseConversationViewController.

What is the best way to do this?

Wouter

**Comment by kmahal** [comment]
Hey @woutergoossens, just import Atlas into your project and then you can subclass it.

```objc
#import <Atlas/Atlas.h>
```
Then you can create your own instance of `ATLMessageInputToolbar` and subclass it as you like.  Hope that helps!

Kabir

**Comment by petec029** [comment]
I am trying to do the same thing.  I get the explanation to subclass ATLMessageInputToolbar.  But I do not see an explanation for how to use my MessageInputToolbar in my ConversationViewController which is based on ATLConversationViewController if the ATLBaseConversationViewController has multiple places where it is using an ATLMessageInputToolbar

The .h files has 
`@property (nonatomic) ATLMessageInputToolbar *messageInputToolbar;`

viewdidload calls a method that create a new ATLMessageInputToolbar

`    self.messageInputToolbar = [self initializeMessageInputToolbar];`
 

The updateBottomCollectionViewInset method and a few others user self.messageInputToolbar 

`
- (void)updateBottomCollectionViewInset
{
    [self.messageInputToolbar layoutIfNeeded];
`
