### ISSUE TITLE
Push notification name is null

### ISSUE THREAD

**Issue by woutergoossens** [layerhq/Atlas-iOS#745]
Hi,

When I am sending a message from user Simulator or a user created with my name (wouter) to user Device the push message is showed as (null): test

Is this a normal use case?

Thanks

Wouter

![405ec25f-b928-4c6d-afda-aaa3f7683ea9](https://cloud.githubusercontent.com/assets/355048/6535008/f9691816-c441-11e4-8bc1-2677a464115f.png)

**Comment by kmahal** [comment]
The `ATLConversationViewController` that sends the message gets the sender's fullname from the `ATLConversationViewControllerDataSource` method:

```objc
- (id<ATLParticipant>)conversationViewController:(ATLConversationViewController *)conversationViewController participantForIdentifier:(NSString *)participantIdentifier
``
