### ISSUE TITLE
NSInvalidArgumentException when leaving a conversation

### ISSUE THREAD

**Issue by jamiefaye** [layerhq/Atlas-iOS#746]
Using Atlas Messenger, create a conversation with several participants. Then go into the detail view and click on "Leave Conversation". This causes the failure to occur most of the time.

The offending call is in -    - ATLUIConversationViewController.m configureControllerForChangedParticipants.

Here is the backtrace:
2015-03-09 11:57:54.476 Atlas Messenger[635:181238] -[__NSOrderedSetI minusSet:]: unrecognized selector sent to instance 0x17001d880
2015-03-09 11:57:54.476 Atlas Messenger[635:181238] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSOrderedSetI minusSet:]: unrecognized selector sent to instance 0x17001d880'
*** First throw call stack:
(0x18579e59c 0x195ee80e4 0x1857a5664 0x1857a2418 0x1856a6b6c 0x1000fa410 0x1000f9bec 0x185744ae4 0x185683220 0x186582c60 0x1001dc02c 0x100710e30 0x100710df0 0x10071575c 0x185755fa4 0x18575404c 0x1856810a4 0x18e81b5a4 0x189fb2aa4 0x1000cefa4 0x196556a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) bt
* thread #1: tid = 0x2c3f6, 0x000000019666f270 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x000000019666f270 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000019670d228 libsystem_pthread.dylib`pthread_kill + 112
    frame #2: 0x00000001965e6b18 libsystem_c.dylib`abort + 112
    frame #3: 0x00000001956b9418 libc++abi.dylib`abort_message + 116
    frame #4: 0x00000001956d8b8c libc++abi.dylib`default_terminate_handler() + 304
    frame #5: 0x0000000195ee83c0 libobjc.A.dylib`_objc_terminate() + 128
    frame #6: 0x00000001956d5bb4 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x00000001956d5478 libc++abi.dylib`__cxa_throw + 136
    frame #8: 0x0000000195ee8204 libobjc.A.dylib`objc_exception_throw + 348
    frame #9: 0x00000001857a5664 CoreFoundation`-[NSObject(NSObject) doesNotRecognizeSelector:] + 220
    frame #10: 0x00000001857a2418 CoreFoundation`___forwarding___ + 928
  * frame #11: 0x00000001856a6b6c CoreFoundation`_CF_forwarding_prep_0 + 92
    frame #12: 0x00000001000fa410 Atlas Messenger`-[ATLConversationViewController configureControllerForChangedParticipants](self=0x000000014e676250, _cmd=0x000000010037540d) + 420 at ATLConversationViewController.m:751
    frame #13: 0x00000001000f9bec Atlas Messenger`-[ATLConversationViewController layerClientObjectsDidChange:](self=0x000000014e676250, _cmd=0x0000000100375816, notification=0x0000000170259920) + 1164 at ATLConversationViewController.m:707
    frame #14: 0x0000000185744ae4 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
    frame #15: 0x0000000185683220 CoreFoundation`_CFXNotificationPost + 2060
    frame #16: 0x0000000186582c60 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 72
    frame #17: 0x00000001001dc02c Atlas Messenger`__25-[LYRClient postChanges:]_block_invoke964(.block_descriptor=0x0000000170258990) + 464 at LYRClient.m:1570
    frame #18: 0x0000000100710e30 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #19: 0x0000000100710df0 libdispatch.dylib`_dispatch_client_callout + 16
    frame #20: 0x000000010071575c libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1056
    frame #21: 0x0000000185755fa4 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #22: 0x000000018575404c CoreFoundation`__CFRunLoopRun + 1492
    frame #23: 0x00000001856810a4 CoreFoundation`CFRunLoopRunSpecific + 396
    frame #24: 0x000000018e81b5a4 GraphicsServices`GSEventRunModal + 168
    frame #25: 0x0000000189fb2aa4 UIKit`UIApplicationMain + 1488
    frame #26: 0x00000001000cefa4 Atlas Messenger`main(argc=1, argv=0x000000016fd57a48) + 180 at main.m:28
    frame #27: 0x0000000196556a08 libdyld.dylib`start + 4
(lldb)

**Comment by kmahal** [comment]
Thanks @jamiefaye, we're looking into it right now.

Kabir

**Comment by kcoleman731** [comment]
Hi @jamiefaye We have resolved this issue and the fix is on master. It will be included in our next release.
