### ISSUE TITLE
-[ATLConversationViewController queryControllerDidChangeContent:] crash

### ISSUE THREAD

**Issue by timgshi** [layerhq/Atlas-iOS#747]
I've been seeing lots of crashes like the one below:
```
Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (19) must be equal to the number of sections contained in the collection view before the update (18), plus or minus the number of sections inserted or deleted (2 inserted, 0 deleted).
```

http://crashes.to/s/a9d52f19697

**Comment by kcoleman731** [comment]
@timgshi Thanks for the heads up on this. we will have look and see what is going on. 

Best, 

Kev

**Comment by kcoleman731** [comment]
Hey @timgshi I'm have a tough time reproducing this one. Do you have steps or a test that can repro?

Thanks!

**Comment by kcoleman731** [comment]
Hey @timgshi please let me know if you are still seeing this crash? Otherwise, I'll go ahead and close. 

Thanks!

**Comment by christ776** [comment]
Hi, I'm having exactly the same issue.

**Comment by danielmhanover** [comment]
+1. I am on latest versions of Atlas and LayerKit
