### ISSUE TITLE
search crash

### ISSUE THREAD

**Issue by iOSRoad** [layerhq/Atlas-iOS#749]
search crash

**Comment by kcoleman731** [comment]
Hi @iOSRoad. Would you mind being a bit more descriptive on where the crash occurred?

**Comment by iOSRoad** [comment]
2015-03-12 13:00:33.264 Programmatic[2520:89794] LayerKit client v0.10.1 loaded
2015-03-12 13:01:06.498 Programmatic[2520:89794] -[ATLSampleConversationListViewController conversationListViewController:didSearchForText:completion:]: unrecognized selector sent to instance 0x7afd1050
2015-03-12 13:01:06.780 Programmatic[2520:89794] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ATLSampleConversationListViewController conversationListViewController:didSearchForText:completion:]: unrecognized selector sent to instance 0x7afd1050'
*** First throw call stack:
(
	0   CoreFoundation                      0x02716946 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x02371a97 objc_exception_throw + 44
	2   CoreFoundation                      0x0271e5c5 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
	3   libobjc.A.dylib                     0x023878ae -[NSObject forwardInvocation:] + 66
	4   CoreFoundation                      0x026671ae ___forwarding___ + 478
	5   CoreFoundation                      0x02666fae _CF_forwarding_prep_0 + 14
	6   Programmatic                        0x000475ec -[ATLConversationListViewController searchDisplayController:shouldReloadTableForSearchString:] + 300
	7   UIKit                               0x011b040a -[UISearchDisplayController searchBar:textDidChange:] + 127
	8   UIKit                               0x010ac257 -[UISearchBar(UISearchBarStatic) _searchFieldEditingChanged] + 178
	9   libobjc.A.dylib                     0x023877cd -[NSObject performSelector:withObject:withObject:] + 84
	10  UIKit                               0x00d4a23d -[UIApplication sendAction:to:from:forEvent:] + 99
	11  UIKit                               0x00d4a1cf -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	12  UIKit                               0x00e7de86 -[UIControl sendAction:to:forEvent:] + 69
	13  UIKit                               0x00e7e2a3 -[UIControl _sendActionsForEvents:withEvent:] + 598
	14  UIKit                               0x0159a9ff -[UITextField fieldEditorDidChange:] + 227
	15  UIKit                               0x00e85f30 -[UIFieldEditor textInputDidChange:] + 58
	16  UIKit                               0x015a3e1e -[UITextInputController _sendDelegateChangeNotificationsForText:selection:] + 129
	17  UIKit                               0x015a5e5a -[UITextInputController _insertText:fromKeyboard:] + 772
	18  UIKit                               0x015a6710 -[UITextInputController insertText:] + 371
	19  UIKit                               0x00e88d8c -[UIFieldEditor insertText:] + 1128
	20  UIKit                               0x0159e46a -[UITextField insertText:] + 60
	21  UIKit                               0x00f8f2ab -[UIKeyboardImpl insertText:] + 107
	22  UIKit                               0x00f8b61d -[UIKeyboardImpl performKeyboardOutput:] + 551
	23  UIKit                               0x00f8b27a __55-[UIKeyboardImpl handleKeyboardInput:executionContext:]_block_invoke_2 + 157
	24  UIKit                               0x015c30a2 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 404
	25  libobjc.A.dylib                     0x02387771 -[NSObject performSelector:withObject:] + 70
	26  Foundation                          0x01f73f20 __NSThreadPerformPerform + 330
	27  CoreFoundation                      0x0263a1df __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	28  CoreFoundation                      0x0262fced __CFRunLoopDoSources0 + 253
	29  CoreFoundation                      0x0262f248 __CFRunLoopRun + 952
	30  CoreFoundation                      0x0262ebcb CFRunLoopRunSpecific + 443
	31  CoreFoundation                      0x0262e9fb CFRunLoopRunInMode + 123
	32  GraphicsServices                    0x045b624f GSEventRunModal + 192
	33  GraphicsServices                    0x045b608c GSEventRun + 104
	34  UIKit                               0x00d488b6 UIApplicationMain + 1526
	35  Programmatic                        0x00023aed main + 141
	36  libdyld.dylib                       0x035caac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by iOSRoad** [comment]
Detailed enough of it😄

**Comment by kcoleman731** [comment]
@iOSRoad Thats what I needed! Will sort it out and push a fix.
