### ISSUE TITLE
Image empty after reinstall

### ISSUE THREAD

**Issue by woutergoossens** [layerhq/Atlas-iOS#750]
Hi,

When I upload an image in a chat conversation it is showed correctly.
But when I remove the app and install it again, the image does not load/show.

I checked the LYRMessage  and it contains multiple LYRMessageParts

`<LYRMessage:0x7ffccbc60620 identifier=layer:///messages/4b2a98d5-958d-48e5-b999-372a5119b87c databaseIdentifier=19 index=18 seq=73 version=0 isDeleted=NO parts=(
    "<LYRMessagePart:0x7ffccbc5f9a0 identifier=layer:///messages/4b2a98d5-958d-48e5-b999-372a5119b87c/parts/0 MIMEType=image/png size=435743 databaseIdentifier=19 version=0 transferStatus=LYRContentTransferReadyForDownload>",
    "<LYRMessagePart:0x7ffccbc5fe70 identifier=layer:///messages/4b2a98d5-958d-48e5-b999-372a5119b87c/parts/1 MIMEType=image/jpeg+preview size=108766 databaseIdentifier=20 version=0 transferStatus=LYRContentTransferReadyForDownload>",
    "<LYRMessagePart:0x7ffccbc60260 identifier=layer:///messages/4b2a98d5-958d-48e5-b999-372a5119b87c/parts/2 MIMEType=application/json+imageSize size=38 databaseIdentifier=21 version=0 transferStatus=LYRContentTransferComplete data=\"<7b0a2020 22776964 74682220 3a20...\">"
) conversation=<LYRConversation:0x7ffcc9dd9ed0 identifier=layer:///conversations/dbc7177b-e0b8-465b-aca8-254faecfbb7f databaseIdentifier=1 version=0 isDeleted=NO streamUUID=E94E43B4-C7D1-11E4-A90B-74AB55004532 participants={(
    41,
    49
)}>>`

But 

   ` if (previewImagePart.fileURL) {
        displayingImage = [UIImage imageWithContentsOfFile:previewImagePart.fileURL.path];
    } else {
        displayingImage = [UIImage imageWithData:previewImagePart.data];
    }
    `

is returning nil in both cases.

What could the issue be?

Thanks

**Comment by kcoleman731** [comment]
Hi @woutergoossens thanks for your note!

It looks like you need to specify `autodownloadMIMETypes` on your `LYRClient` instance. For reference, in the Atlas messenger sample app, we do the following....
```
layerClient.autodownloadMIMETypes = [NSSet setWithObjects:ATLMIMETypeImageJPEGPreview, ATLMIMETypeTextPlain, nil];
```
`LYRClient` only automatically downloads message parts with data under 2k in size. If you need it to auto-download larger parts, you must specify that it should via the `autodownloadMIMETypes` property. 

In your case, when you log out, the data is being purged from your device and not sync'd again upon login.

**Comment by woutergoossens** [comment]
Thanks!
