### ISSUE TITLE
iOS 8 - UITabBarViewController and Atlas Issue... + fix :)

### ISSUE THREAD

**Issue by sanvean** [layerhq/Atlas-iOS#754]
Hi - first of all thanks for providing such an awesome set of UIComponents :)

I had a small animation glitch in my iOS 8 app using Atlas that I just resolved so thought I'd share in case it helps others or makes sense to add to the readme or comments for ATLConversationViewController.

I'm using the following ViewController hierarchy:

UITabBarViewController -> UINavigationController -> ATLConversationListViewController -> ATLConversationViewController

I noticed when selecting a conversation and pushing the ATLConversationViewController onto the view controller stack that the ATLMessageInputToolBar at the bottom of the view was animating awkwardly. 

It was sliding in covering part of the underlying tab bar but leaving the top 10% visible, also  as the background of the toolbar is initially transparent it was resulting in an ugly animation when the final toolbar background popped in at animation completion.

To fix just add the line below before pushing the ATLConversationViewController:

    conversationViewController.hidesBottomBarWhenPushed = YES;
    [self.navigationController pushViewController:conversationViewController animated:YES];

**Comment by sanvean** [comment]
Actually the above causes another glitch when the conversation view controller is dismissed.

The Search Bar in the ATLConversationListViewController now pops awkwardly into view with no animation when it was previously hidden and not visible beforehand - could this be fixed?

**Comment by kcoleman731** [comment]
Hi @sanvean Thank you for your kind words and the heads up. I'll look into the strange issue with the keyboard right now. 

Also for reference, the message input tool bar is not meant to cover a tab bar. Your inclination to hide the tab bar is spot on. 

Will get back with some info for you.

**Comment by kcoleman731** [comment]
Hi @sanvean 

Apologies for the super delayed response here. I've tried reproducing and am unable to. Are you using storyboards?

**Comment by sanvean** [comment]
Hi Kevin,




Yes, however I've since replaced the Atlas ListView Controller with my own view controller as a conversation centric table view wasn't the best fit for my app, so this isn't actually an issue for me anymore.

**Comment by kcoleman731** [comment]
Sounds good. Thanks @sanvean!
