### ISSUE TITLE
Chat conversation does not update after going to background and foreground

### ISSUE THREAD

**Issue by woutergoossens** [layerhq/Atlas-iOS#756]
Hi,

I have a use case where to conversation screen does not update when you enter a new message.

Use case:
* Open the Atlas Messenger application 
* Open a conversation
* enter message, it appears as normal
* go to background (with that conversation open)
* go back to foreground
* enter a message (still appears as normal)
* go back to the conversation list
* select the same conversation
* enter a message, it does appear
* When you go back to the conversation list and open the same conversation, the message appears..

Could you take a look please? From then on, the messages do not appear and I have to quit the application to work as expected..

Thanks

Wouter

**Comment by kcoleman731** [comment]
Hi @woutergoossens can you tell me when you downloaded the Atlas Messenger application? I just downloaded the latest and cannot reproduce you issue. 

We had a small bug in the LayerKit SDK a few weeks ago which caused this type of behavior. It has since been fixed and Atlas has been updated. Would you mind downloading again and letting me know if the behavior persists?

**Comment by woutergoossens** [comment]
Hi,

Thanks for the reply.

I am using the latest Atlas Messenger. Just downloaded it again from GitHub and updated the latest pods.

I have uploaded a video screencast with my problem..
As Github does not support video - https://vid.me/lIKA

Wouter 

![ios simulator screen shot 16 mar 2015 21 01 06](https://cloud.githubusercontent.com/assets/355048/6675282/a65d7528-cc1f-11e4-82ee-0b4da9a6fcc2.png)
![screen shot 2015-03-16 at 21 01 47](https://cloud.githubusercontent.com/assets/355048/6675286/adc50c9a-cc1f-11e4-9da2-feee996ead3a.png)

**Comment by woutergoossens** [comment]
But when I download the app via getatlas.layer.com, it works, but not with the latest application when I download the Atlas Messenger source. Isn't that the same, can you verify that (based on my video)?

Thanks

**Comment by kmahal** [comment]
Hi @woutergoossens, master should have the fixes to that.  With the new fixes you shouldn't see the layerClient reauthenticate and connect when entering the foreground as you currently see in your video screencast.  Thanks for reaching out to us about that and let us know if you have further questions.

Thanks,
Kabir
