### ISSUE TITLE
'LayerKit.h' file not found.

### ISSUE THREAD

**Issue by danieljacobarcher** [layerhq/Atlas-iOS#762]
After updating to Atlas 1.0.2, I'm getting the error that 'LayerKit.h' file not found in Pods-LayerKit-umbrella.h

**Comment by blakewatters** [comment]
@danieljacobarcher Is this still an issue? You may want to try explicitly importing `LayerKit` and `Atlas` in your Podfile instead of relying on the implicit import (I assume you are using Swift since you reference the umbrella header)

**Comment by danieljacobarcher** [comment]
@blakewatters I'm not sure, no longer working with Atlas/LayerKit.
