### ISSUE TITLE
Using Atlas-iOS components with your own private XMPP Server

### ISSUE THREAD

**Issue by adil-appifytech** [layerhq/Atlas-iOS#767]
I was wondering if you guys are considering to make it available to be used with your own XMPP Server.

Thanks.

**Comment by blakewatters** [comment]
Atlas was designed to provide UI components directly on top of LayerKit, the iOS SDK for Layer’s messaging services. The components are tightly integrated with the feature set and model from LayerKit and enabling support for alternative backends would greatly complicate the APIs. We don’t have any plans to support any other messaging backends
