### ISSUE TITLE
ATLConversationListViewController does not show the search results

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#768]
This happens because it does not use the searchQueryController, when in search mode.

**Comment by blakewatters** [comment]
Thanks for the issue report. We’ll take a look and advise.

**Comment by oferRounds** [comment]
:+1:

**Comment by kcoleman731** [comment]
Hi @oferRounds Thanks for reporting this. Are you experiencing this in an actual application or just in the Atlas sample application with mock data?

**Comment by oferRounds** [comment]
I experience it in an actual application. And the reason for it is quite clear, I think: there are several methods, mainly the TableViewDelegate's ones, that does not take the search mode into account. 
For example:
```
tableView:numberOfRowsInSection:, which, maybe, should be changed to something like this:
return [[self contextedQueryController] numberOfObjectsInSection:section];

-(LYRQueryController *)contextedQueryController
{
    return self.searchDisplayController.isActive ? self.searchQueryController : self.queryController;
}
```

**Comment by kcoleman731** [comment]
Hi @oferRounds 

We actually manage two `LYRQueryController` objects internally. One manages the unfiltered list of conversations, the other manages the search results. Check out the following `queryController` getter method. It coordinates grabbing the appropriate controller depending on the `active` state of the `searchController`. 

```
- (LYRQueryController *)queryController
{
    if (self.searchController.isActive) {
        return _searchQueryController;
    } else {
        return _queryController;
    }
}
```

**Comment by oferRounds** [comment]
You're right, I haven't seen this getter. But still, in fact, it didn't work until I added this change.

The difference I see between the original implementation and mine, is that first checks against the searchController, and the second - again searchDisplayController.

**Comment by kcoleman731** [comment]
@oferRounds Interesting. Have a PR for your implementation?

**Comment by kcoleman731** [comment]
@oferRounds, I can't reproduce any of your issues. Are you still having issues with search? If not, I'll close the comment.

**Comment by oferRounds** [comment]
@kcoleman731 - I apologise, it was actually my mistake and now that I find it, everything works well.

The mistake was that in my class which inherits from ATLConversationListViewController, I added a property of type LYRQueryController with the same name of the one on the parent class. This prevented the getter that you mentioned above from being called, resulting in not choosing the searchQueryControler when searching.
