### ISSUE TITLE
ATLConversationListViewController: needs a method to check if search is active

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#769]
Possible solution would be to expose a readonly property of the searchController.

**Comment by kcoleman731** [comment]
Hi @oferRounds Would you be able to describe the use case that requires this addition?

**Comment by oferRounds** [comment]
Yes, I would like, when the user searches for a Conversation with a participant, and then finds it and selects the Conversation, to end the search mode, so when the user returns to the Conversation List screen, it will be shown in a normal mode. 
The rational behind it is that the user does not longer need the search mode to be active, as he had already got what he wanted.

So I would like to be able to do something like this:

```
if (self.searchController.isActive) {
        [self.searchController setActive:NO animated:NO];
}
```

**Comment by kcoleman731** [comment]
Fair enough. It seems that there is enough consensus that the searchController needs to be accessible to subclasses. I will make it so.

**Comment by oferRounds** [comment]
Thanks, sounds good :)

**Comment by kcoleman731** [comment]
@oferRounds This is done on master and will be in our next release.

**Comment by oferRounds** [comment]
Just a small typo: searchContorller -> searchController (...tor... -> ...tro...)

**Comment by danipralea** [comment]
+1 for the typo

**Comment by oferRounds** [comment]
:)
