### ISSUE TITLE
ATLConversationViewController: two issues with image sending

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#770]
1. Image does not appear in the other-user conversation. I mean, the other-user view does "understand" 
it has an image to present, but it only shows a "Grey" rectangular (on the sender, it does appear). 

2. Issue which happens from time to time: the image is sent, but it is not added dynamically to the view. Meaning, only if the user goes back-and-forth to his conversation-list, only then the image will show up.

**Comment by maju6406** [comment]
Try setting autodownloadMIMETypes to your image mimetypes.  The issue is that the images are larger than 2k, and we won't download them unless you set autodownloadMIMETypes or autodownloadMaximumContentSize. I think setting one those values could fix the issue you're seeing.  Here's more info about how we handle "rich content":
https://developer.layer.com/docs/guides#richcontent

**Comment by oferRounds** [comment]
Thanks! 
This fixed issue #1.

**Comment by kcoleman731** [comment]
Hi @oferRounds. Can you confirm that message is successfully sent? You can verify via the `ATLConversationViewController` delegate method.

**Comment by oferRounds** [comment]
Yes, the message is sent, the other participants gets it.

**Comment by kcoleman731** [comment]
Can you tell me what version of LayerKit you are using? In a previous  .10 series release, we had some database issues which would cause messages to not show up in the UI. They have since been remedied.

**Comment by oferRounds** [comment]
I use 0.11.2.

**Comment by kcoleman731** [comment]
Hi @oferRounds Your issue 

https://github.com/layerhq/Atlas-iOS/issues/784 

should be resolved with the following PR. 

https://github.com/layerhq/Atlas-iOS/pull/782

This assertion failure could cause content to not show up on screen. Could this have been your issue?

**Comment by oferRounds** [comment]
Everything is good now, thanks! Closing the issue.
