### ISSUE TITLE
ATLConversationListViewController: identify the unique 1-on-1 converstion

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#771]
I'm presenting my own Users list, which from it, the user can select a friend, and then the relevant Conversation is suppose to be opened.

Now, I use the query controller to fetch the relevant conversation, but the problem is that with the current design, I'm not sure if I have an option to identify this conversation. 

The problem is that if the logged in user has both 1-on-1 conversation with a user and also a "Group" conversation with the same user (and without anyone else) - how can one tell between the two (and identify the first one as the required result)?

**Comment by oferRounds** [comment]
Perhaps the way to handle it is by using the Conversation's MetaData to identify Group's conversation (by adding name, or group id, for example), and then if this MetaData does not exist, conclude that the Conversation is of 1-on-1 type?

**Comment by kcoleman731** [comment]
@oferRounds This is a LayerKit feature request. I will make sure it gets fed into our backlog. 

For now my suggestion would be to query for conversations containing your desired user and then iterate through those conversations to find your desired result.

**Comment by oferRounds** [comment]
Thanks @kcoleman731.

So do you think my suggestion above is the way to deal with this issue currently?
