### ISSUE TITLE
ATLMessageInputToolbar: allow the option to chage the rightAccessoryButton

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#772]
Meaning, prevent the the transition from the "Send" appearance/ behaviour to the "Share Location" when no text is entered.

**Comment by blakewatters** [comment]
This sounds like a pretty reasonable ask. We’ll take a look

**Comment by oferRounds** [comment]
Thanks!

**Comment by kcoleman731** [comment]
@oferRounds Are you looking for the icon to just display the `Send` text?

**Comment by oferRounds** [comment]
@kcoleman731 I guess that could be a workaround, but basically, I would like to have the option to control whether, when the input the is empty, the "Send" button gets replaced with a different action icon (I do have the option to change not only the icon itself, but the actual action, right? Lets say, for example, that I would like to allow a quick option to send a :+1:), or not.

**Comment by kcoleman731** [comment]
@oferRounds Fair enough. I'll add the customization hooks for you.

**Comment by oferRounds** [comment]
:+1:

**Comment by kcoleman731** [comment]
@oferRounds Done on master and will be in our next release.

**Comment by oferRounds** [comment]
Yay!
