### ISSUE TITLE
Image sending process - send image directly from the Photo/Library apps

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#773]
i.e., add the option to send the image without pasting it first to the input view (and then tap "Send").

**Comment by kcoleman731** [comment]
@oferRounds I'll go ahead and move the ` UIImagePickerControllerDelegate` declaration to the `ATLConversationViewController` header. You will then be able to implement the following image picker delegate method in a subclass. 

```
(void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info```

You can then grab the image an  send it directly into the conversation yourself. Make sure to use Atlas supported `MIMETypes` when you do.

**Comment by oferRounds** [comment]
@kcoleman731 Sounds good!

**Comment by oferRounds** [comment]
I do see now that the Kit applies some logic before insert the image to the inputToolBar. 
Wouldn't it be better to add a property which describes this feature instead of exposing the above mentioned method?
