### ISSUE TITLE
Sending image - the progress bar would sometimes fail to work

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#774]
It does not show the progress, and remains stack on its first state even when the image was finished to be uploaded and was already sent.

**Comment by kcoleman731** [comment]
Hi @oferRounds Can you give a bit more context as to how this happens? Wifi? 3G? Any more context would be helpful. Even better if you could capture it in a test.

**Comment by oferRounds** [comment]
I'm not sure. I tried to reproduce it now, but actually, things are acting a bit strange. From One device it does get send and everything - including the progress indicator - works very well. On the other hand, when I try to send the message from a different device, to the same other device - which runs the exact same code - the image does not get send at all. This happens although the conversationViewController:didSendMessage: does get called, and while the progress bar remains stuck on 0 value. 

Also, two issues which are a bit related:
1. I'm keep getting an assertion failure error (which the app does able to recover from) at the ATLConversationViewController's method reloadCellsForMessagesSentByParticipantWithIdentitifier:, on the last line of it: [self.collectionView reloadItemsAtIndexPaths:indexPaths];
2. Sometimes, when sending an image, the view does not get refresh, and the image is not shown. When going back to the Conversations list and then returns - then it appears.

**Comment by kcoleman731** [comment]
@oferRounds  Can you send me a Gist of how you are using `reloadCellsForMessagesSentByParticipantWithIdentitifier:,`?

**Comment by oferRounds** [comment]
Yes, see here: https://gist.github.com/oferRounds/afa18ab24df4dcfc43e0

**Comment by oferRounds** [comment]
@kcoleman731, I updated to the to the latest Master version, and the progress bar issue seems to be gone. 
If that's ok with you, I'll close this issue and open a different ones for the two others which are mentioned here.
