### ISSUE TITLE
Adding the option to attach a MetaData to a Message.

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#775]
One use case for this could be adding the option to "Like" a message, something that several messaging apps on the stores offer.

**Comment by kcoleman731** [comment]
@oferRounds This is a LayerKit feature request. I'll make sure this request gets fed into our backlog.

**Comment by oferRounds** [comment]
Thanks @kcoleman731 :)

**Comment by oferRounds** [comment]
Hi @kcoleman731,

Any chance this could be prioritised? Another use case, which I am in need in my app, is to attach a meta data to an Image, which gives more text info about it.
Or, other option: is there any workaround that can be made to achieve it?

**Comment by kartikthapar** [comment]
I don't think LayerKit needs an update for this. This is how I send messages in my app —

    - (void)sendTextMessage:(NSString *)text
    {
        LYRClient *client = [LYRClient client];
        
        // text message
        LYRMessagePart *textMessagePart = [self textMessagePart:text];
        NSString *pushMessage = [NSString stringWithFormat:@"%@ (%@): %@", [[NSUserDefaults standardUserDefaults] fullName], [self title], text];
        
        // metadata
        LYRMessagePart *metadataPart = [self metadataPart];
        
        // message
        LYRMessage *message = [client newMessageWithParts:@[textMessagePart, metadataPart]
                                                  options:@{LYRMessageOptionsPushNotificationAlertKey: pushMessage}
                                                    error:nil];
        
        // send message
        [self sendMessage:message error:nil];
    }

Metadata e.g.

    - (LYRMessagePart *)metadataPart
    {
        NSDictionary *info = @{<field>:<val>};
        NSData *data = [NSKeyedArchiver archivedDataWithRootObject:info];
        LYRMessagePart *part = [LYRMessagePart messagePartWithMIMEType:@"application/json" data:data];
        return part;
    }

**Comment by oferRounds** [comment]
Thanks, @kartikthapar.

Yes, I am aware of that field, and perhaps I did not explain my need well enough.
The problem with your suggestion is that I need to be able to update the message after it was created and sent, and then synchronise the update. As far as I understand, this field does not provide this abilities.

**Comment by oferRounds** [comment]
@kcoleman731, am I right?

**Comment by kartikthapar** [comment]
I am not sure I completely understand your use case here. But you are looking to update a message instance, i.e. modify it after you have created it? I am afraid that's not possible with layer and I don't think it should be either. Can you give an example as to why do you need this functionality?

**Comment by oferRounds** [comment]
I have mentioned it in the description of the issue: I would like to allow users to "Like" a message, while reflecting the people who like the message on a given moment.

**Comment by kartikthapar** [comment]
I see. Sorry about that. I still think this is very application specific but could be easily bundled using metadata. I would be implementing similar stuff in my application using the currently available tools.

Currently, modifications on messages are not available. So ideally, you could develop a custom message for liking a particular message. This `likeMessage` can be sent to all the participants in a conversation just like you send any other message. The metadata of the like message may look like:

    {
        by: <participantId>,
        timestamp: <ts>,
        original_msg: <message_id>,
    }

The `message_id` corresponds to the `identifier` of the original message that you liked.

I think this is way more flexible that having metadata modifications on messages.

**Comment by oferRounds** [comment]
@kartikthapar, this sounds like a great solution!

I'll try it and report. Thanks!!
