### ISSUE TITLE
Question/Bug: New Created Conversation is not added to the ConversationList

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#778]
After following these steps:
1. Users selects a contact;
2. Creating a new Conversation using LYRClient's method newConversationWithParticipants:options:error (after querying and verifying there is no existing Conversation which matches the participants);
3. User sends a Message;
4. User returns to the Conversations List.

The new Conversation does not appear.

Should I explicitly call a specific method to refresh the list, or does the framework is responsible for doing it?
If being asked, I think the framework should do it, if indeed the Conversation was started (i.e., the first message was sent).

**Comment by maju6406** [comment]
Ofer - The conversation list should automatically update.  Does the conversation not appear even after you quit the app and restart?  Are you able to reproduce this with the Layer+Parse or Atlas Messenger examples?

**Comment by oferRounds** [comment]
The conversation does appear when I quit the app and restart; I'll check later on today if it get reproduced on the Layer+Parse or Atlas Messenger.

**Comment by oferRounds** [comment]
Abir - I checked now, I was not able to reproduce in the Atlas project.

I suspect the issue laid in the fact that in my project, in oppose to the Messenger, the process of starting a new chat start is a bit different:
1. Presenting a controller with the user's contacts list;
2. Selecting a contact (by the user)
3. Querying for the relevant conversation, and in that case, not finding one;
4. Creating a new Conversation using the method: newConversationWithParticipants:options:error
5. Presenting the conversation.

Do you have an idea what, in this process, might cause this issue?

**Comment by kcoleman731** [comment]
@oferRounds  Are you creating the conversation with metadata? I've ran into an issue where my metadata is invalid. 

Do you have your `LYRClient` delegate set up? If so, have you implemented the following?

```
- (void)layerClient:(LYRClient *)client didFailOperationWithError:(NSError *)error;
```

Are you seeing any errors when trying to send a message?

**Comment by oferRounds** [comment]
This was my issue - caused by the same issue which I detailed about on the search results bug. So everything is good now :)
Sorry for that...
