### ISSUE TITLE
Image recipient: adding a progress indicator to reflect the download process

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#783]
Currently, the recipient would just see a grey empty rectangle for a while, until the image is finished to be downloaded.

**Comment by oferRounds** [comment]
Currently, the recipient would just see a grey empty rectangle for a while, until the image is finished to be downloaded.

**Comment by kcoleman731** [comment]
@oferRounds I'm not sure what you are asking here? Is this a feature request or an issue?

**Comment by oferRounds** [comment]
I think it's a feature.
In other words: in the current implementation, in the recipient side, when he receives an image - is there suppose to be a progress bar indicator, such as on the sender side? 
If there is - then there is a bug; otherwise, I think it would be good to add one, because sometimes it might take a while until the image finished downloading, and in the mean time, the recipient just sees a blank grey rectangle.

Actually, now that I think about it - I think the best would be to first download and present a preview/low resolution image.

**Comment by kcoleman731** [comment]
@oferRounds You last suggestion about having a preview image is actually how Atlas is implemented. When we send an image message, that message actually contains 3 parts...
1. A Low Res image
2. A high res image
3. A dimension image used to inflate the cell. 

If you include `ATLMIMETypeImageJPEGPreview` in your `autodownloadMIMETypes`, they will show up in the chat UI as a preview image.

**Comment by oferRounds** [comment]
I'm setting the autodownloadMIMETypes to nil, as it says that this will automatically download all content. But I don't see the low res image being download before the higher one.

Is nil support to include the ATLMIMETypeImageJPEGPreview?

**Comment by kmahal** [comment]
@oferRounds have you tried setting the `autoDownloadMIMEType` to include `ATLMIMETypeImageJPEGPreview` instead of nil?  Let us know how it works.

**Comment by mohammedDehairy** [comment]
image attachments are taking forever to show on the recipient side , most of them were never received , there is clearly some thing wrong , with image attachments.

**Comment by oferRounds** [comment]
@kmahal, sorry for the long delay on my side. 
Yes, I have tried it now: still the same results.

Also, I am experiencing the same issue @mohammedDehairy reported here above: it seems there is a new problem: some of the images do not get downloaded at all.

**Comment by kmahal** [comment]
@oferRounds is this still an ongoing issue for you?

**Comment by oferRounds** [comment]
@kmahal now it's me who apologise - sorry for not being available.
I didn't test lately, as I was occupied with some things, but I will do it over the weekend. I'll post the status.
Thanks!

**Comment by kmahal** [comment]
@oferRounds any update?

**Comment by oferRounds** [comment]
Ok, verified it now - now everything works very well! Thanks!
