### ISSUE TITLE
Assertion failure on ATLConversationViewController's reloadCellsForMessagesSentByParticipantWithIdentitifier:

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#784]
I'm keep getting an assertion failure error (which the app does able to recover from) at the ATLConversationViewController's method reloadCellsForMessagesSentByParticipantWithIdentitifier:, on the last line of it: [self.collectionView reloadItemsAtIndexPaths:indexPaths];

**Comment by oferRounds** [comment]
Gist of the way I'm using reloadCellsForMessagesSentByParticipantWithIdentitifier:
https://gist.github.com/oferRounds/afa18ab24df4dcfc43e0

**Comment by kcoleman731** [comment]
@oferRounds This should be fixed as of PR https://github.com/layerhq/Atlas-iOS/pull/782

Can you pull in the latest and let me know?

**Comment by oferRounds** [comment]
Looks this one is also solved, wasn't able to reproduce :)
