### ISSUE TITLE
After sending an image, the view does not get refresh, and the image is not shown

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#786]
This issue sometimes happens. I do see that after sending the image and going back to the Conversations list and then returning - then it appears.

**Comment by kcoleman731** [comment]
@oferRounds  Can you try to repro this on 1.0.5? This issue could be cause by the animation assertion...which has been resolved.

**Comment by oferRounds** [comment]
Thanks - looks like it's now solved, wasn't able to reproduce :)
