### ISSUE TITLE
Building on SDK 8.3 fails

### ISSUE THREAD

**Issue by danipralea** [layerhq/Atlas-iOS#787]
![screen shot 2015-04-16 at 14 02 10](https://cloud.githubusercontent.com/assets/768893/7179504/3fab17f6-e441-11e4-8901-4f92e7638be6.png)

Fixed it temporarily by disabling Run of Unit Tests target Edit Scheme > Build section

Reference :
http://stackoverflow.com/questions/26109851/code-signing-is-required-for-product-type-unit-test-bundle-in-sdk-ios-8-0

PS : There's an empty (red) reference to a .DS_Store file in Atlas > Examples > Programatic group.

**Comment by kcoleman731** [comment]
@danipralea Thank you much! Removed the reference 

https://github.com/layerhq/Atlas-iOS/tree/bugfix/issue-cleanup
