### ISSUE TITLE
Feature request : Asynchronous data loading

### ISSUE THREAD

**Issue by danipralea** [layerhq/Atlas-iOS#788]
Hello all,
Thank you again for your great work and continuing to develop the framework as well.

I was wondering if there will be support for asynchronous data loading for conversations list (avatar and conversation title), meaning that I would like to make a call to my API and asynchronously get the user from the database with that id and then supply it to Atlas.

**Comment by kmahal** [comment]
@danipralea we've implemented the following:
```objc
/**
 @abstract Reloads the cell for the given Conversation.
 @param conversation The Conversation object to reload the corresponding cell of. Cannot be `nil`.
 */
- (void)reloadCellForConversation:(LYRConversation *)conversation;
```
Which can be used with your own asynchronous calls to reload the conversation when you get the data.  This means you'll have to have a "default" case before the data is downloaded, but upon getting it can be updated.

**Comment by danipralea** [comment]
thank you Kabir !
