### ISSUE TITLE
Auto property synthesis warning with Xcode 6.3 for iOS 8.3 SDK

### ISSUE THREAD

**Issue by jwyld** [layerhq/Atlas-iOS#790]
Code/Controllers/ATLBaseConversationViewController.m:26:44: Auto property synthesis will not synthesize property 'view'; it will be implemented by its superclass, use @dynamic to acknowledge intention

Xcode 6.3 (6D570)
iOS 8.3 (Simulator)

I didn't try for device, but I'm sure it's the same.  If a standard build doesn't reproduce, a clang (Build & Analyze) build will.

**Comment by kcoleman731** [comment]
Thanks @jwyld Will take care of it.
