### ISSUE TITLE
Disable address bar view controller

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#796]
I believe that the address bar is very application specific. It definitely fits the iMessage model but it's not meant to be there for every sort of messaging application. I can fork the project and disable the address bar display but having an option to disable address bar display/logic when creating a new conversation view controller might be useful.

**Comment by kmahal** [comment]
@kartikthapar, you can choose to not display the address bar with the following property of the `ATLConversationViewController`:

```
/**
 @abstract IA boolean value to determine whether or not the receiver should display an `ATLAddressBarController`. If yes, applications should implement `ATLAddressBarControllerDelegate` and `ATLAddressBarControllerDataSource`. Default is no.
 */
@property (nonatomic) BOOL displaysAddressBar;
```
Set it to NO and it won't show when the controller is displayed on screen.

**Comment by kartikthapar** [comment]
Thanks @kmahal. I cannot believe I missed that. Probably overlooked some superclass properties. Thanks very much.
