### ISSUE TITLE
Allowed MIME types for ATLConversationViewController

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#797]
This is a feature request — restrict message query for only parts that contain specific MIME types. 

In some cases, I would only want to load text messages in a message view even if the participants have shared location or photo messages. Currently, I was achieving this by setting a compound predicate for the message query in `ATLConversationDataSource`.

I'm not sure if there are other hooks to achieving the above; so having an API to do this would be great. Thanks.

**Comment by maju6406** [comment]
I'm not sure I fully understand the use case.  So a sender can send a location or a photo, but you don't want the receiver to see it?

**Comment by kartikthapar** [comment]
There might be other views a developer might want to utilize in order to display certain types of messages. For example, a map of locations attributed with sender names rather than locations in the messaging view.

Also, developers might send custom messages with binary data (e.g. a basic JSON/NSDictionary for some specific task; e.g. an update alert). Currently, these messages are also displayed in the message view (albeit without any content in them).

— Kartik Thapar

**Comment by kmahal** [comment]
@kartikthapar you can already query based on MIMEType.  For example:
```objc
    LYRQuery *query = [LYRQuery queryWithQueryableClass:[LYRMessage class]];
    query.predicate = [LYRPredicate predicateWithProperty:@"parts.MIMEType" predicateOperator:LYRPredicateOperatorIsEqualTo value:@"text/plain"];
```
I'm going to close this issue out; let us know if you need anything else.

**Comment by kartikthapar** [comment]
I have already forked this and this issue is beyond me. But I still believe that this is not just a feature requires, the current implement is a bug as well.

Also, this wasn't about a simple query for messages; it was about ATLConversationViewController's query for messages. If however there was a public API to set a custom query, this issue wouldn't have existed.

As far as the bug is concerned — Layer expects developers to send metadata messages for sync, etc; for example an invite message to force sync at album creation. A developer would simply send these messages across as JSON serialized that would show up as a tiny dot in the message view. Clearly that is an issue.

However as I said, I have this forked so this is not an issue anymore but I believe there should be some changes. Thanks.
