### ISSUE TITLE
Add an option to move the typingIndicatorController to Conversation's navigationItem

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#800]

**Comment by kcoleman731** [comment]
@oferRounds Can you explain a bit more about what you are looking for here?

**Comment by oferRounds** [comment]
Hi @kcoleman731, I apologise for the long delay.

My model is WhatsApp: I would like the Typing Indicator to be presented on the inside the UITableView, but on the top of the screen: on navigationItem/Bar.

**Comment by kmahal** [comment]
@oferRounds feel free to submit a PR for this, or we can close out the issue as it's not a likely feature in our internal development roadmap.

**Comment by oferRounds** [comment]
@kmahal now it's me who apologise - sorry for not being available.
I understand, no problem. Thanks for the response.
