### ISSUE TITLE
No way to change the `title` of the `navigationItem` of `ATLConversationListViewController`

### ISSUE THREAD

**Issue by andrewcopp** [layerhq/Atlas-iOS#803]
The value is hardcoded to "Messages" and is set in `viewDidLoad`. We need a way to expose this through the API.

**Comment by kmahal** [comment]
@andrewcopp this can be overridden in your subclass of `ATLConversationListViewController` in your implementation of `viewDidLoad`.  If you call `[super viewDidLoad] at the start, it will initialize the title, but if you then set `self.title = @"Your title here"`, your title will override the default.

**Comment by andrewcopp** [comment]
Duh.
