### ISSUE TITLE
Attachment Text Defaults to Image

### ISSUE THREAD

**Issue by blakewatters** [layerhq/Atlas-iOS#806]
The `ATLConversationTableViewCell` cell has an annoying default behavior — it defaults unrecognized attachment types to being treated as images by applying the “Attachment: Image” text.

We should probably enable a hook to let you layer in additional MIME Types without needing to resort to subclassing.

**Comment by xuki** [comment]
This is what I'm asking in #805, I guess I should close it then?

**Comment by kmahal** [comment]
@xuki yes, we'll track the issue on this one.  thanks.

**Comment by kmahal** [comment]
fixed in merged PR: https://github.com/layerhq/Atlas-iOS/pull/813
