### ISSUE TITLE
SearchBar width

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#809]
This is a very minor annoyance (at least personally). The search bar width only adjusts to the table view cell width.

![ios](https://cloud.githubusercontent.com/assets/810861/7381075/295b30a8-edce-11e4-9ce5-2b91daef92f9.png)
![sample participants](https://cloud.githubusercontent.com/assets/810861/7381076/29671abc-edce-11e4-9f0a-6efc9e112c07.png)

I have uploaded screen shots for both iOS contacts app and the example app. I believe that the UISearchBar span across the entire width of the visible area.

**Comment by kcoleman731** [comment]
@kartikthapar This appears to be the default behavior os search bar now as we are using it. Have a PR to remedy?

**Comment by kartikthapar** [comment]
The idea is wrap the searchbar in a UIView like:

    self.searchBar = [[UISearchBar alloc] initWithFrame:CGRectZero];
    [self.searchBar sizeToFit];
    self.searchBar.translucent = NO;
    self.searchBar.accessibilityLabel = @"Search Bar";
    self.searchBar.delegate = self;
    self.searchBar.userInteractionEnabled = YES;
    
    UIView *searchView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, 44)];
    [searchView addSubview:self.searchBar];
    self.tableView.tableHeaderView = searchView;

But once you activate the search bar and cancel it, the searchbar goes back to it's original size. I am not sure how to fix that.

**Comment by kmahal** [comment]
@kartikthapar do you have a PR for this fix?  If not we'll close out the item.

**Comment by kartikthapar** [comment]
No I really don't have a PR for this. I haven't worked on this issue ever since.
