### ISSUE TITLE
Add buttons in conversation

### ISSUE THREAD

**Issue by marcelo-marqueti-movile** [layerhq/Atlas-iOS#814]
Hello,

His possible to add links formatted like buttons to conversations?

For example: one user send a link to pay something, but in the interface we show just a button to redirect to link.

Image example attached.

It's is possible? Which class I need to look? Or Docs to read?

Regards
Marcelo
![chat_button](https://cloud.githubusercontent.com/assets/4093760/7472792/76375436-f30c-11e4-979d-38b6ce9116f1.png)

**Comment by kmahal** [comment]
@marcelo-marqueti-movile you can accomplish that by creating a custom `UICollectionViewCell` and registering it with the ATLConversationViewController` via:
```objc
/**
 @abstract Register a class for use in creating message collection view cells.
 @param reuseIdentifier The string to be associated with the class.
 */
- (void)registerClass:(Class<ATLMessagePresenting>)cellClass forMessageCellWithReuseIdentifier:(NSString *)reuseIdentifier;
```
