### ISSUE TITLE
ATLMessageInputToolbar rightAccessoryButton titleLabel properties

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#816]
- (void)configureRightAccessoryButtonForText
    {
        self.rightAccessoryButton.accessibilityLabel = ATLMessageInputToolbarSendButton;
        [self.rightAccessoryButton setImage:nil forState:UIControlStateNormal];
        self.rightAccessoryButton.contentEdgeInsets = UIEdgeInsetsMake(2, 0, 0, 0);
        self.rightAccessoryButton.titleLabel.font = [UIFont boldSystemFontOfSize:17];
        [self.rightAccessoryButton setTitle:@"Send" forState:UIControlStateNormal];
        [self.rightAccessoryButton setTitleColor:ATLBlueColor() forState:UIControlStateNormal];
        [self.rightAccessoryButton setTitleColor:[UIColor grayColor] forState:UIControlStateDisabled];
    }

I believe that all properties involving the title label should be set in the common initializer method rather than this method that is called every time the text changes (or the subviews are laid out). This way I am unable to set my own defaults.

**Comment by kmahal** [comment]
@kartikthapar just merged a fix for this.  https://github.com/layerhq/Atlas-iOS/blob/f948d1839d1f6fb87be9c97745d21e5ff51f166d/Code/Views/ATLMessageInputToolbar.h#L104  We have added 2 `UI_Appearance` selectors for active and disabled state to provide customization.

**Comment by kartikthapar** [comment]
Thanks. I just want to point out however that some other properties could be transformed as UI_Appearance selectors as well. One of them being the title font. The title text is still static, i.e. "Send". If this could be set by the user too, that'd be great. I can submit a PR for the same though.

**Comment by kmahal** [comment]
@kartikthapar Opening up the `titleLabel.text` could allow for some breaking behavior if the user places a very long string there, so for now we've just allowed those two.  We'll discuss internally about font and text for the future.

**Comment by kartikthapar** [comment]
Okay, that’s cool. I have added it to my fork, nonetheless as I currently need it. Thanks

— Kartik Thapar
