### ISSUE TITLE
Question — changing composer text view font size

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#818]
Setting composer text view font size through either appearance proxy or via accessory methods is not correctly laying out text field contents. This is probably due to the use of dummy text view in for height calculations. Relayout inside `setFont:` doesn't seem to work.

Anyway to change the font for the text field instead of setting a custom value inside the `init` method in `ATLMessageComposeTextView`.

**Comment by kmahal** [comment]
@kartikthapar if you know a fix feel free to submit a PR. If not we'll look into it but I can't guarantee a timeline.  Please provide a screenshot of the problem as well if possible.

**Comment by kmahal** [comment]
Hey @kartikthapar any update?  If not we'll close this one out.

**Comment by kartikthapar** [comment]
I haven't looked at this in a long time but I will spend some time on this today in the evening. As far as I remember this, it was insanely hard to get it right without manually setting the font inside the initializer. Nonetheless, I will report by tomorrow. Thanks.

**Comment by kmahal** [comment]
I'll wait for your PR
