### ISSUE TITLE
ATLMediaAttachment class methods instantiate incorrectly

### ISSUE THREAD

**Issue by jwyld** [layerhq/Atlas-iOS#820]
All of the +[ATLMediaAttachment mediaAttachment...] methods, instantiate incorrectly.  They are all declared as returning an instancetype result.  All of them internally instantiate using [ATLImageMediaAttachment alloc].  They should instead [self alloc].

The only way to extend ATLMediaAttachment is via subclassing.  If I want to extend the capabilities, it's impossible for me to continue to use the convenience class methods for instantiation of the basic types, and still get my subclass capabilities.

**Comment by jwyld** [comment]
Ugh.  I didn't even notice it uses the internal, "hidden" subclasses which means it's entirely impossible to add functionality to the basic attachment types.

**Comment by kmahal** [comment]
@jwyld can you provide a few use cases of how you'd want to extend the current functionality?  We provide delegate methods for sending custom message types.

**Comment by jwyld** [comment]
In the case of the base types, we want to alter the look of the result of -image.  That's not easily possible since calling the factory instantiation method doesn't instantiate what I gave it.  At this point, I have to totally reimplement the base types.

**Comment by kmahal** [comment]
@jwyld do you specifically mean the dimensions of the image when it's sent and rendered in the collectionview?

**Comment by jwyld** [comment]
I think you're confusing attachments and messages.  I am specifically referring to the NSAttachment which is displayed in the message input toolbar.  These are not part of what is sent or rendered in the collection view.  These are only rendered in the message input toolbar during message creation.

**Comment by kmahal** [comment]
Understood.  The `ATLMediaAttachment` also creates the `LYRMessage` object and its parts' sizing information which is why I asked.  If you could explain what exactly is not rendering correctly when passing in your `UIImage` instance in the `ATLMessageInputToolbar` instance that would help.  Alternatively, feel free to make a fix and submit a pull request.

**Comment by kmahal** [comment]
Any update here @jwyld?  If not I'll close this one out.

**Comment by jwyld** [comment]
I'll find a way to solve what I need independently.
