### ISSUE TITLE
Declare ATLConversationViewController as ATLMessageInputToolbarDelegate in header file

### ISSUE THREAD

**Issue by dippigu** [layerhq/Atlas-iOS#824]
Can the ATLConversationViewController be declared as an ATLMessageInputToolbarDelegate in the public, rather than the private, interface?

I'm looking to override the <code>- (void)messageInputToolbar:(ATLMessageInputToolbar *)messageInputToolbar didTapRightAccessoryButton:(UIButton *)rightAccessoryButton</code> method, but call through to the superclass implementation in certain cases.

The method is not exposed on ATLConversationViewController due to the delegate membership being declared privately.

**Comment by kmahal** [comment]
@dippigu what's your use case?  You can insert toolbar attachments and use the `ATLConversationViewController` delegate method `- (NSOrderedSet *)conversationViewController:(ATLConversationViewController *)viewController messagesForMediaAttachments:(NSArray *)mediaAttachments` to override the method you listed.  Returning nil will default to native functionality, and you can check the media attachments for a custom `ATLMediaAttachment` you've added.

**Comment by dippigu** [comment]
@kmahal I'm looking to override the <code>sendLocationMessage</code> to send a sticker. I've replaced the location image with a sticker image, and if the user has not entered any text or media items into the input area, tapping on the sticker image will present a <code>UIActionSheet</code> containing sticker images to choose from. Tapping on a sticker will insert the sticker directly into the conversation.

Overriding the <code>- (NSOrderedSet *)conversationViewController:(ATLConversationViewController *)viewController messagesForMediaAttachments:(NSArray *)mediaAttachments</code> as you described doesn't seem to cover my use case as this method is only fired when the user has inserted media items into the input area.

I'm basically looking to leverage the existing functionality, but replace the call to <code>[self sendLocationMessage]</code>

**Comment by kmahal** [comment]
@dippigu We discussed this internally and have agreed there's no easy way to do this.  I'll be working on a PR for today and will update you accordingly when it's out.  Thanks for the feedback!  Always appreciated.

**Comment by dippigu** [comment]
@kmahal Just to clarify, is that a PR to move the <code>ATLMessageInputToolbarDelegate</code> declaration to the header file?
No problem on the feedback, thanks for looking at the issues so quickly.

**Comment by kmahal** [comment]
@dippigu We're going to expand the scope of the delegate method `conversationViewController:messagesForMediaAttachments:` to include an empty array of media attachments, so the delegate can override `sendLocationMessage` functionality.  We'll also add that method to our default message method that will then handle an empty array as well.

**Comment by kmahal** [comment]
@dippigu this PR is merged: https://github.com/layerhq/Atlas-iOS/pull/825

The delegate is now triggered even without media attachments.  This should fix your issue.
