### ISSUE TITLE
Why contain "source 'git@github.com:layerhq/cocoapods-specs.git'" in Podfile?

### ISSUE THREAD

**Issue by wonderffee** [layerhq/Atlas-iOS#826]
When I execute "pod install", it says:
Analyzing dependencies
Cloning spec repo `layerhq` from `git@github.com:layerhq/cocoapods-specs.git`
[!] Unable to add a source with url `git@github.com:layerhq/cocoapods-specs.git` named `layerhq`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

But https://github.com/layerhq/cocoapods-specs is not found.

**Comment by kmahal** [comment]
@wonderffee our apologies, its now removed from master.
