### ISSUE TITLE
Issues with avatars in ATLConversationViewcontroller

### ISSUE THREAD

**Issue by thomasgpeng** [layerhq/Atlas-iOS#830]
Hey guys, thanks for all the hard work on Atlas -- it's extremely flexible and already saving me a lot of time.

I noticed a couple of issues when using ATLConversationViewController:

1) It looks like private property `shouldDisplayAvatarItem` is being set according to how many `otherParticipantsID`s are in the conversation.  Any chance you guys could make this a public property so we can choose to set it ourselves in the event that we want to show avatars in conversations with only one other `ParticipantID`?  I've overridden both the property and private method `configureControllerForConversation` in my subclass and it works, but it's not best practice.

2) I can't figure out how to change the avatar size via `setAvatarImageDiameter` when I pass an `ATLAvatarImageView` to `[ATLIncomingMessageCollectionViewCell appearance]`.

Thanks!

**Comment by thomasgpeng** [comment]
Another oddity I'm seeing with `ATLConversationViewController`:

![img_2894](https://cloud.githubusercontent.com/assets/813291/7668953/0d4564b2-fc27-11e4-8588-212092f2aff0.PNG)

I'm getting this occasionally though I'm not sure what sequence of user actions causes it.  Has anyone else seen this before?

**Comment by kartikthapar** [comment]
As far as the second point is concerned, I have seen this once in app. I am not sure why this happens but restarting the app fixes this. Clearly, a big issue for production.

**Comment by kmahal** [comment]
@thomas-layer @kartikthapar The 2nd issue is a known bug in our most recent `LayerKit` release - try using 0.13.0 for now until we release the fix soon.

**Comment by kmahal** [comment]
@thomas-layer as for the property reference, that sounds reasonable.  Feel free to submit a PR with the fix if you'd like the functionality immediately.

**Comment by thomasgpeng** [comment]
@kmahal Any comment about the `setAvatarImageDiameter` issue I referenced above?

**Comment by kmahal** [comment]
@thomasgpeng it can be set via `UI_APPEARANCE_SELECTOR`.  `[ATLIncomingMessageCollectionViewCell appearance]` passes back a proxy, where you can set the diameter you want.

**Comment by JSeeley** [comment]
@kmahal Could you fill me in on the sequence of actions needed to reproduce the missing chat issue? Trying to decide if this is a blocker for our most recent submission. Thanks!

**Comment by kmahal** [comment]
@JSeeley we're still looking into it, but we recommend using 0.13.0 for now until 0.13.2 is released soon.

**Comment by kmahal** [comment]
@thomasgpeng merged https://github.com/layerhq/Atlas-iOS/pull/832.  Thanks.
