### ISSUE TITLE
Question: unable to create new file in a fork.

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#831]
So, I am trying to create a new protocol to work with conversation list controller but I see a simple 'file not found' issue.

This happens with any new file that I create. Is this by design? Nonetheless, is there a way to add new files to the project? I appreciate any help. Thanks.

**Comment by kmahal** [comment]
@kartikthapar with a fork you own the entire repository, so it's not an `Atlas` issue.  Have you made sure the files are added to the right target?

**Comment by kartikthapar** [comment]
@kmahal True that. And that's been the mystery for a while. :/ Can you please try creating a new file in the protocols folder and add it to the project in `Atlas.h`? I am just extremely confused as to why I cannot do it. Do I have to add it as a source for one of the targets (given that none of the other files were added as source)? I am also not sure if this is a search/header path issue of some sort.

**Comment by kmahal** [comment]
@kartikthapar I just forked it and everything seems to be working.  Atlas references itself from the development pod.  Try clicking the `Pods` section, going to `Development Pods` and adding the code there.  That should do it.

**Comment by kartikthapar** [comment]
Okay, I was doing it wrong. I didn't see that the Code folder was actually referenced from the Atlas Development Pod. Thanks.
