### ISSUE TITLE
Slack Integration!

### ISSUE THREAD

**Issue by EMidee66** [layerhq/Atlas-iOS#839]
Hi,

Is there a way to integrate the layer - atlas with slack?

Thank You!

**Comment by maju6406** [comment]
How are you thinking of integrating Atlas and Slack?  We'd love to hear more about your use case.

**Comment by EMidee66** [comment]
Well first case scenario: person - business chat. It would be easier for businesses if messages got delivered  at slack (easier to organize and reply). Maybe businesses want to integrate in their apps a live chat and you guys can make this more efficient. What do you think Abir?

**Comment by kmahal** [comment]
@EMidee66 this is less an `Atlas` implementation than it is a `LayerKit` implementation.  When we release webhooks it will allow for such integrations, as the native iOS SDK doesn't allow for such functionality.

**Comment by kmahal** [comment]
@EMidee66 I'll be closing this for the above reason, unless you have anything Atlas specific in mind.  Thanks for your feedback and input!

**Comment by EMidee66** [comment]
Yes, I think Layer Platform API solves the issue.
Thank You!
