### ISSUE TITLE
ATLConversationViewController.m:209 enables right accessory button

### ISSUE THREAD

**Issue by jwyld** [layerhq/Atlas-iOS#841]
Independently of how the message input toolbar is configured, ATLConversationViewController will always enable the button as long as there is a conversation.

In our case, the right button is set to not display the image.  This means it's always "Send," and we don't support sending the location via the location button.  When creating a new conversation, -[ATLConversationViewController configureControllerForConversation] will be called and enable the "Send" button which automatically sends the location if there is no text.  If the MessageInputToolbar were allowed to handle the configuration instead, it will properly enable and disable its buttons which would prevent the sending as intended.

ATLConversationViewController should really be calling something along the lines of -[ATLMessageInputToolbar configureRightAccessoryButtonState], but that's not 100% correct either, nor is it public.

**Comment by kmahal** [comment]
@jwyld If you want to make sure it does not send location, implement this delegate method of the `ATLConversationViewController`:
```objc
- (NSOrderedSet *)conversationViewController:(ATLConversationViewController *)viewController messagesForMediaAttachments:(NSArray *)mediaAttachments;
```
When pressing `send` with no attachments (location sharing), this method will be called with an empty array.  If you return an empty `NSOrderedSet` it will not send the location.  Returning `nil` will default it to default behavior which in this case would be sharing location.

**Comment by jwyld** [comment]
This was not resolved.

The bug is that the MessageInputToolbar controls the state incorrectly.  That isn't about overriding the ability to send.

**Comment by kmahal** [comment]
@jwyld What specific behavior does the current implementation prevent you from achieving that makes it a bug?  You referenced disabling location sharing which displays the `send` button by default which would share the location, but that can be overriden as shown.  If the specific issue is just with the implementation and that the `ATLMessageInputToolbar` should control its own state entirely then feel free to submit a pull request with an implementation change.  Thanks for your feedback!

**Comment by jwyld** [comment]
"In our case, the right button is set to not display the image. This means it's always "Send," and we don't support sending the location via the location button. When creating a new conversation, -[ATLConversationViewController configureControllerForConversation] will be called and enable the "Send" button which automatically sends the location if there is no text. If the MessageInputToolbar were allowed to handle the configuration instead, it will properly enable and disable its buttons which would prevent the sending as intended."

We don't support the location sending this way, but when the instantiation occurs, the "Send" button is enabled.  If a user hits that, the underlying, inherited code will send a location.  We can prevent sending the location, but the button shouldn't be enabled to start.

**Comment by kmahal** [comment]
@jwyld Understood.  While the above implementation resolves the effect, it's reasonable to want the `ATLMessageInputToolbar` to control it's own state.  I have a PR for this fix and another you suggested: https://github.com/layerhq/Atlas-iOS/pull/859.  If this fixes the bug please feel free to close this issue, thanks.
