### ISSUE TITLE
Is there an option to customize the appearance of ATLMessageInputToolbar?

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#848]
I would like to change its appearance in a way which the 2 properties, which support the UI Appearance, are not enough.
What kind of options would I have, if any?

**Comment by kmahal** [comment]
@oferRounds you could subclass the `ATLMessageInputToolbar` or create your own `inputAccessoryView`

**Comment by oferRounds** [comment]
Sounds good. But how do I instruct my class, which subclasses ATLConversationViewController, to use my subclass of ATLMessageInputToolbar (instead of ATLMessageInputToolbar itself)?

**Comment by kmahal** [comment]
`self.messageInputToolbar = self.myInputToolbar`
