### ISSUE TITLE
ATLMessageInputToolbar: persist text

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#849]
Is there an easy way do that?

That means - the user started typing on a conversation, did not send the message, and then:
a. Went back and forth between the conversation and his list of conversations.
or
b. Terminated the app, and restarted it again, and went back to the conversation.

I would like the user, when he goes back to the conversation, to see the text which he started to write.

**Comment by kmahal** [comment]
@oferRounds You can do this yourself by creating a shared cache.  Before the controller is deallocated you can save the media attachments in the cache.  When the controller is being loaded again you can check if your cache has any media attachments for the specified conversation and insert it into the message toolbar.

**Comment by oferRounds** [comment]
Thanks, sounds good!
