### ISSUE TITLE
Custom payload with image

### ISSUE THREAD

**Issue by dippigu** [layerhq/Atlas-iOS#851]
As a follow up to issue #823, I have created a custom cell and <code>MIMEType</code> to display the sticker images that we are sending.  Having followed the documentation guide for creating a custom payload, I cannot find any way to include an image.  Simply including an image in the <code>dataDictionary</code> falls over when serialising to JSON.

My use case is sending a small image as a sticker and displaying it in a custom cell so that I can control the size that the image is displayed in the message feed.

I have also tried sending as an <code>ATLMediaAttachment</code> but this doesn't allow me to assign a custom <code>MIMEType</code> and use my custom cell.

**Comment by maju6406** [comment]
I recommend adding another LYRMessagePart that contains the image.  Then you can use the built-in Rich Content handling to upload and download the message.  If you haven't seen this tutorial, check out:
https://developer.layer.com/docs/atlas#custom-payload
Also, it's worth checking out the Rich Content guide:

https://developer.layer.com/docs/guides#richcontent

**Comment by dippigu** [comment]
A simple <code>LYRMessagePart</code> with the image. Embarrassingly easy. Thanks.
I'll close this issue down.
