### ISSUE TITLE
Fatal crash in ATLConversationViewController.m

### ISSUE THREAD

**Issue by giaset** [layerhq/Atlas-iOS#853]
Hey guys,

Love with you're doing with Layer & Atlas! However, we're getting a fatal crash in our Conversation View Controller when we deep link to it from a remote notification with the app backgrounded.

Basically, we're getting a EXC_BAD_ACCESS KERN_INVALID_ADDRESS at line 1120:

**dispatch_suspend(self.animationQueue);**

Is anybody else experiencing this? Could it be that the animationQueue is nil at that point? Here's a link to a crash log, if it helps: http://crashes.to/s/d8a66c88df6

Cheers,

Gianni

**Comment by blakewatters** [comment]
@kmahal @kcoleman731 This looks like the `animationQueue` is `nil` at the time of the crash. Looking at the setup code path, we don’t configure the `animationQueue` until `viewDidLoad` (see https://github.com/layerhq/Atlas-iOS/blob/master/Code/Controllers/ATLConversationViewController.m#L133).

If you just move it to `lyr_commonInit` that should cover this case (https://github.com/layerhq/Atlas-iOS/blob/master/Code/Controllers/ATLConversationViewController.m#L92-L101)

**Comment by kmahal** [comment]
fixed in: https://github.com/layerhq/Atlas-iOS/pull/855
