### ISSUE TITLE
Atlas uses code deprecated in iOS 8.0 causing a lot of warnings 

### ISSUE THREAD

**Issue by eytanlevit** [layerhq/Atlas-iOS#854]
Hey,

Here's a screenshot of all the warnings

![image](https://cloud.githubusercontent.com/assets/229986/8227956/cbe82d82-15b3-11e5-9f83-823ca152694a.png)

**Comment by kmahal** [comment]
@eytanlevit iOS9 is still in pre-release, which we have not fully supported yet until closer to open release.  Feel free to submit a PR with fixes.

**Comment by ntnmrndn** [comment]
@kmahal  He is talking about iOS8, not iOS9 :)

**Comment by kmahal** [comment]
Ah fair point!  My apologies for the mix-up.  We'll have a fix out soon.

**Comment by kmahal** [comment]
@eytanlevit are you installing it directly or via cocoapods?  we use pods internally and the warnings are all suppressed.

**Comment by kmahal** [comment]
Fixed in https://github.com/layerhq/Atlas-iOS/pull/868 and https://github.com/layerhq/Atlas-Messenger-iOS/pull/189

**Comment by DanielsCode** [comment]
Hi,

I used Atlas 1.0.11 installed through cooapods. My development target is iOS 8.0 and I got similar warnings. How can I apply your fixes?

Attached my warnings:
![atlas_ios8warnings](https://cloud.githubusercontent.com/assets/10348190/10391577/1f6cd71c-6e80-11e5-8506-8631ef316429.png)

thanks for helping in advance
