### ISSUE TITLE
Display sender Avatar

### ISSUE THREAD

**Issue by ntnmrndn** [layerhq/Atlas-iOS#856]
Hi, 

We would like to add this feature.
We are willing to implement it and submit a pull request.

Would you accept such feature ?
Any thoughts on how to implement it ?

**Comment by kmahal** [comment]
Hi @ntnmrndn could you explain what you mean further?  Atlas already displays avatar items for conversations with more than 3 participants, and even a conversation with 2 participants if you set `@property (nonatomic) BOOL shouldDisplayAvatarItemForOneOtherParticipant`.  Do you mean for the authenticated user?

**Comment by ntnmrndn** [comment]
Yes, for the current authenticated user.

**Comment by kmahal** [comment]
@ntnmrndn got it.  If you wanted to submit a pull request, look at the layout functionality of the non-sender collection view cells that do display the avatar item.  That would be the best guideline to implementation.  In addition you would add a public property such as `shouldDisplayAuthenticatedUserAvatarItem` which would default to `NO` and have to be set to `YES` to display the avatar item.  Feel free to submit a PR for the feature as we would certainly accept it.  Thanks!

**Comment by kmahal** [comment]
merged in https://github.com/layerhq/Atlas-iOS/pull/894
