### ISSUE TITLE
Injecting atlas controller inside existing app.

### ISSUE THREAD

**Issue by KolyaProdeus** [layerhq/Atlas-iOS#858]
I am having hard time adding atlas UI to my app. I use translucent NavBar and custom TabBar, when I try to add ATLConversationViewController I have a problem with ATLMessageInputToolbar and ATLAddressBarView. Toolbar appears above my TabBar and AddressBar is below NavBar.
![screen shot 2015-06-22 at 8 51 25 pm](https://cloud.githubusercontent.com/assets/12733480/8289397/dc4a64fa-1924-11e5-9b8d-d469816280f1.png)
This green band you see is in fact big green [+] button totally covered by send-message box. Same thing is on top of the screen only I can’t show it on screenshot as atlas completely covers my UI.

I tried fixing this in ATLBaseConversationViewController by changing NSLayoutConstraint but this seems does not work. Any ideas how should I resolve this problem?

**Comment by kmahal** [comment]
@KolyaProdeus be sure to hide your `tabBar` when presenting the `ATLConversationViewController`.  That way it won't appear behind the `ATLMessageInputToolbar`

**Comment by KolyaProdeus** [comment]
I probably can convince customer that bottom bar is to be hidden but still must display some data on the top. And there I have the same problem. Any other ideas?

**Comment by kmahal** [comment]
@KolyaProdeus  The `ATLConversationViewController` and `ATLConversationListViewController` are designed to work even with translucent navigation bars.  If I'm reading what you are saying correctly, you want something that's displayed on the controller underneath it in the stack to be visible.  This is a custom use case which Atlas wouldn't support by default.  You can fork the repository and make any changes you see fit, however.

**Comment by chlebta** [comment]
@kmahal I got this strange behavior :
![sans titre](https://cloud.githubusercontent.com/assets/1204608/10425809/887c68d6-70d2-11e5-96ca-494f740fb931.png)
 
As you can see the `messageInputToolbar` is not sticked to bottom of view it look like pinned to top of the hidden tabBar.
NS : This issue appear only after displaying then dismissing keyboard.
