### ISSUE TITLE
ConversationTableViewCell and unread message indicator

### ISSUE THREAD

**Issue by vinzen** [layerhq/Atlas-iOS#867]
Hello,

Our team is currently working on push notification. 
We discovered if we open the conversation from the notification and go back to the conversation's list, the conversation is still unread sometimes.
I have been looking into it, the bug is when the conversation is loaded, its marked as read for the current message but the new one has not been loaded yet, so the conversation is unread.

We are currently working on a pull request.

Regards,
Vincent

**Comment by maju6406** [comment]
Thanks for the report. Looking forward to the PR.

**Comment by kmahal** [comment]
@vinzen do you have a forthcoming PR?

**Comment by vinzen** [comment]
@kmahal here you go

**Comment by kmahal** [comment]
@vinzen are you synchronizing the push notification with the layer client before pushing? Using ```- (BOOL)synchronizeWithRemoteNotification:(NSDictionary *)userInfo completion:(void(^)(NSArray *changes, NSError *error))completion;``` on the `LYRClient`.  If you don't synchronize then the new message won't appear if you push it immediately and then go back before the client can sync.

**Comment by vinzen** [comment]
@kmahal I don't think we need it here because the new message appear in the conversation.

**Comment by ntnmrndn** [comment]
Hi,
Any update on this PR? :)

**Comment by kmahal** [comment]
Hi @ntnmrndn apologies for the very late reply on this.  Are you still running into this issue?  A lot of `LayerKit` functionality has changed since this was first opened up.  Let us know and we can work through it.  Thanks!

**Comment by ntnmrndn** [comment]
Nope, we don't have this problem anymore.
