### ISSUE TITLE
Unknown User for server generated Message

### ISSUE THREAD

**Issue by candyss9185** [layerhq/Atlas-iOS#874]
Hi, 

I have been trying to get the name of the sender in the case of server-generated messages. However, using ATLConversationViewController, the name is retrieved using the userId, which in the case of server-generated messages is nil. Is there another way to do it?
Otherwise, can a fix be added to also send the message to the Data Source delegate to retrieve the name?

**Comment by maju6406** [comment]
This is a known issue with Atlas that we're about to merge.  You can see the PR here:
https://github.com/layerhq/Atlas-iOS/pull/875/files

**Comment by kmahal** [comment]
Hi @candyss9185 I've merged this fix here: https://github.com/layerhq/Atlas-iOS/pull/875.  Thanks.

**Comment by candyss9185** [comment]
Hi! Has the pod been updated?
