### ISSUE TITLE
Problem with insertMediaAttachment in ATLMessageInputToolbar.m

### ISSUE THREAD

**Issue by thomasgpeng** [layerhq/Atlas-iOS#876]
Hey guys, it's me again (sorry).  I'm seeing an issue when I try to send a photo message -- I'm getting a `NSInvalidArgumentException` in `insertMediaAttachment` on the line:

    [attributedString addAttribute:NSForegroundColorAttributeName value:textView.textColor range:NSMakeRange(0, attributedString.length)];

Anyone else having this issue as well?  If I comment this line out the problem goes away.

**Comment by KristopherGBaker** [comment]
I'm seeing the same issue with Atlas 1.0.9.  It works in 1.0.8.

**Comment by kmahal** [comment]
@thomasgpeng @KristopherGBaker this bug is merged: https://github.com/layerhq/Atlas-iOS/pull/879 and updated with `1.0.10`.  Apologies for the issue.
