### ISSUE TITLE
Sending video message support?

### ISSUE THREAD

**Issue by huyduc** [layerhq/Atlas-iOS#877]
Hi, 
We're trying to create a chat application with capability to send video file. We're currently experiencing this crash.

![screenshot 2015-07-01 12 48 07](https://cloud.githubusercontent.com/assets/721399/8450029/590a4aba-2009-11e5-87bc-161a9ff787d4.png)

We create the attachment using this ATLMediaAttachment class method

```objective-c
+ (instancetype)mediaAttachmentWithAssetURL:(NSURL *)assetURL thumbnailSize:(NSUInteger)thumbnailSize;
```

I suspect it's due to the way mediaInputStream was created (probably not support video or something)

```objective-c
self.mediaInputStream = [ATLMediaInputStream mediaInputStreamWithAssetURL:asset.defaultRepresentation.url];
```

If I create the message this way, it's sent successfully without crashing

```objective-c
        ALAssetRepresentation *rep = [asset defaultRepresentation];
        Byte *buffer = (Byte*)malloc(rep.size);
        NSUInteger buffered = [rep getBytes:buffer fromOffset:0.0 length:rep.size error:&error];
        NSData *theData = [NSData dataWithBytesNoCopy:buffer length:buffered freeWhenDone:YES];
        LYRMessagePart *messagePart = [LYRMessagePart messagePartWithMIMEType:@"video/quicktime" stream:[NSInputStream inputStreamWithData:theData]];
        NSError *theError;
        LYRMessage *message = [self.layerClient newMessageWithParts:@[messagePart] options:nil error:&theError];
        BOOL success = [self.conversation sendMessage:message error:&theError];
```

Could somebody point me to the direction on how to send video message using ATLMediaInputStream?
Thanks !

**Comment by kmahal** [comment]
Hi @huyduc Atlas does not currently natively support sending videos through `ATLMediaAttachment`.  Your current implementation is the best way.  Feel free to submit a pull request to introduce video taking/sending, and in the meantime we'll close this issue out.
