### ISSUE TITLE
Question:Atlas with own data source

### ISSUE THREAD

**Issue by danipralea** [layerhq/Atlas-iOS#881]
Is it possible to have Atlas configured with my own data source, coming from my own API and if yes, how ? 

Thanks in advance,
Dan.

**Comment by kmahal** [comment]
@danipralea It's not possible.  Atlas is designed to be tightly used with LayerKit.  There are other open sourced projects that can give more generic UIs that can be used for any data source.  Atlas does give delegate methods to customize the specific `LYRQuery`s for each controller, which gives added flexibility.
