### ISSUE TITLE
Avatar images flicker when loading

### ISSUE THREAD

**Issue by mnshah** [layerhq/Atlas-iOS#884]
In a conversation window, the avatar images flicker when loading. Also in subsequent messages sent by the same participant, the image is re-downloaded from the network even though the image has been downloaded by previous message cells.

**Comment by kmahal** [comment]
@mnshah This is a feature inside Atlas:
```objc
dispatch_async(dispatch_get_main_queue(), ^{
            // Try to avoid race conditions
            if ([self.avatarItem avatarImageURL] && [[self.avatarItem avatarImageURL] isEqual:imageURL]) {
                [UIView animateWithDuration:0.2 animations:^{
                    self.alpha = 0.0;
                } completion:^(BOOL finished) {
                    [UIView animateWithDuration:0.5 animations:^{
                        self.image = image;
                        self.alpha = 1.0;
                    }];
                }];
            }
        });
```
We set the alpha to 0 before fading on the image, since transitioning from the letters to the image directly was an unpleasant user experience.  We have caching logic as well, so please check that the images are being cached in your instance correctly.

**Comment by kmahal** [comment]
Hey @mnshah any update on the caching issue?

**Comment by mnshah** [comment]
I was trading messages with Kevin on a support ticket about this. The running theory was that images were being evicted from the cache to free up memory. I wasnt sure this was the case since the number of messages in the conversation were in the low hundreds. Doing some testing just now and it looks to be resolved.
