### ISSUE TITLE
Crash in ATLConversationViewController

### ISSUE THREAD

**Issue by mnshah** [layerhq/Atlas-iOS#891]
I'm getting the following crash consistently in our app: 

Error: NSInternalInconsistencyException

Reason: Invalid update: invalid number of sections. The number of sections contained in the collection view after the update (24) must be equal to the number of sections contained in the collection view before the update (24), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).

Offending line: [ATLConversationViewController queryControllerDidChangeContent:] (ATLConversationViewController.m:1130)

Pod Version: Using Atlas (1.0.10), Using LayerKit (0.14.3)

**Comment by kmahal** [comment]
@mnshah can you paste the entire call stack?  Is this occurring during initialization of the `ATLConversationViewController`, or after it's running?

**Comment by mnshah** [comment]
Does this help: https://gist.github.com/mnshah/691687b40ac85f80d4ff

**Comment by mnshah** [comment]
It seems to happen mostly when the app re-opens and on the first message sent.

**Comment by kmahal** [comment]
what line does the exception throw on `ATLConversationViewController`?

**Comment by mnshah** [comment]
(ATLConversationViewController.m:1130)

**Comment by mnshah** [comment]
Also, if i run in the simulator i get other errors but using the same steps to reproduce. I run the simulator from Xcode, go to group chat, type a message, press send. This causes a crash:

2015-07-13 16:41:26.777 PeerWell[95247:8773422] *** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /SourceCache/UIKit_Sim/UIKit-3347.44.2/UICollectionView.m:4056
PeerWell(95247,0x114081000) malloc: *** error for object 0x7fe29e8754c0: incorrect checksum for freed object - object was probably modified after being freed.

**Comment by kmahal** [comment]
can you confirm that `self.collectionView` is not nil?

**Comment by mnshah** [comment]
I added a simple log statement to print self.collectionView. Its not nil. When i added a breakpoint it also showed as not nil.

**Comment by mnshah** [comment]
I think we figured out the issue. We were calling collectionView reloadData in a subclass of ATLConversationView. This caused inconsistencies in the data source.
