### ISSUE TITLE
How can we customize ATLConversationListViewController for first cell?

### ISSUE THREAD

**Issue by khanhvu161188** [layerhq/Atlas-iOS#892]
Can we custom ATLConversationListViewController so that it can display 2 buttons like Whatsapp for first cell? My mean is create first cell contain  button "Broadcast Lists" and button New Group as first cell. and its always on top. 
Please give me an advice.
Thanks

**Comment by maju6406** [comment]
You can add custom cells to a Conversation List Controller.  However, the custom cell can't have custom functionality like buttons at the moment without some refactoring.

**Comment by khanhvu161188** [comment]
hi @maju6406 can u explain further on your idea? i want my custom cell has 2 buttons, so this button cannot work normally if i put it on this cell?

**Comment by maju6406** [comment]
This is correct. This is because the current implementation only allows a tap on the cell to select a conversation.

**Comment by maxfriedman** [comment]
I was able to hack around this by implementing buttons with custom selectors in my subclassed collection view cell.

**Comment by kmahal** [comment]
The `ATLConversationListViewController` populates its tableview from a `LYRQueryController` that's standard `LYRQuery` displays conversations the authenticated user is a part of, sorted by `conversation.lastMessage.receivedAt` (the time of the last sent message in the convo, like any messaging app).  The `ATLConversationListViewController` only allows the registering of 1 cell, and all cells must be the same height.  To keep a cell on top would be possible but not the experience that you want.  We can move towards allowing several cell types and varying heights like we do in the `ATLConversationViewController`, which would solve the aesthetic issue, but would not solve the problems of keeping a cell anchored to the top, and not being a conversation populated from the query controller.

**Comment by astanton** [comment]
Can someone explain in a little bit of depth or give an example of how you can use a custom cell in a class derived from ATLConversationListViewController? 

I tried creating a new class that extended ATLConversationTableViewCell as the cell, and creating a .xib file with it in it, then setting that as the cellClass to use, but I ran into some funkiness.

I'm trying to make my own looking cells, that do have the information in the default ATLConversationTableViewCell with additional information and in a different layout.

Would the best way to do this maybe be to just clone Atlas and then modify the actual classes to have the look I want it to have?  I still want it to have all of the information like if it has unread messages, it's ordered by the last message date, etc, just with a little bit more information.

**Comment by Vaberer** [comment]
Does anyone know how to achieve it? I have the same problem
