### ISSUE TITLE
ATLConversationViewController display read receipts should be optional

### ISSUE THREAD

**Issue by kartikthapar** [layerhq/Atlas-iOS#897]
^

Probably provide a boolean flag like — `shouldDisplayReadReceiptIfPossible`.

**Comment by kartikthapar** [comment]
I understand that one could return an `NSAttributedString` with a value of `@""` but it doesn't seem very clean.

**Comment by kmahal** [comment]
@kartikthapar feel free to submit a pull request with this feature fix.  Be sure to add tests as well for this logic.
