### ISSUE TITLE
Feature Request: support multiple sections

### ISSUE THREAD

**Issue by cashmash** [layerhq/Atlas-iOS#898]
Feature Request: support multiple sections to group chats 
When i put section > 1, i get an error with following reason: "reason: 'The `LYRQueryController` currently only supports a single section.'

**Comment by kmahal** [comment]
@cashmash the `LYRQueryController` only supports a single section.  The `ATLConversationDataSource` takes the query controller and creates several sections based on appropriate message grouping.  Since Atlas handles the data source there shouldn't be a reason to manually manipulate it.  If you could describe your use case then perhaps we can see the viability of a feature request.

**Comment by ramdanesennoun** [comment]
ah ok understood, thx, so all i need to do is to group the messages (via Layer API? platform api? how?)

**Comment by cashmash** [comment]
ah ok thx, how can i group the messages (layer side) or can i run a custom layerquery?

**Comment by kmahal** [comment]
@cashmash The `ATLConversationDataSource` groups the messages together for you into sections.  That is not currently customizable beyond just that.

**Comment by cashmash** [comment]
all i get is one section, how can i group the messages server side to the controller gets multiple sections (based on the groups)

**Comment by cashmash** [comment]
Use Case:
- User can be a in group chats (> 2 people) and/or in a single (1v1) chats and/or  in chats with attribute X
- I would like to see the ConversationListView showing me multiple tableview sections based on the attribute
- i would like to set the order of the section

**Comment by kmahal** [comment]
Ah you are referring to the `ATLConversationListViewController`.  The `ATLConversationDataSource` is only found in the `ATLConversationViewController`.  The list view controller only has 1 section, and it is not possible to customize it in that fashion currently.  Feel free to submit a pull request to let users customize that, or you'll have to create your own non-Atlas controller to manage that state for your application.
