### ISSUE TITLE
Inaccurate Message Cell Heights

### ISSUE THREAD

**Issue by andrewcopp** [layerhq/Atlas-iOS#902]
If you create custom ATLMessageCollectionViewCells with a different font, Atlas will not accurately size for it.

ATLConversationViewController's defaultCellHeightForItemAtIndexPath: will make a call against ATLOutgoingMessageCollectionViewCell's cellHeightForMessage:inView which is a class method. 

As a result, it will reference the appearance of a ATLOutgoingMessageCollectionViewCell instead of whatever alternative a developer has provided.

**Comment by kmahal** [comment]
@andrewcopp `defaultCellHeightForItemAtIndexPath:` is only called if `- (CGFloat)conversationViewController:(ATLConversationViewController *)viewController heightForMessage:(LYRMessage *)message withCellWidth:(CGFloat)cellWidth` is not implemented.  By implementing the delegate you can define your own custom logic to calculate the exact height for your custom cell, even for default `MIMEType`s.  Atlas can't know the default height required for rendering a custom cell so the developer must provide it.

**Comment by kmahal** [comment]
@andrewcopp  any update on this?  If not we can close it out.  LMK if my above explanation made sense.

**Comment by andrewcopp** [comment]
Ah, hmmm. I suppose we can close this. Seems convoluted that a developer would have to rework all the height calculation logic when you just need to swap out the font. I was able to get it to work though so no hold up on my end.

:+1:

**Comment by Ashif22khan** [comment]
Its not working for me even though I have implemented (CGFloat)conversationViewController:(ATLConversationViewController *)viewController heightForMessage:(LYRMessage *)message withCellWidth:(CGFloat)cellWidth.
I am using systemFont of size 17...
 what should I do? any suggestions?

**Comment by Ashif22khan** [comment]
@andrewcopp Hi Andrew, can you please suggest me how did you resolve this?
Thanks
