### ISSUE TITLE
Feature Request: Tap image to expand fullscreen + Save image in Camera Roll

### ISSUE THREAD

**Issue by imkevinxu** [layerhq/Atlas-iOS#906]
Similar to iMessage, tapping an image to open it fullscreen and also the ability to save the image into your camera roll

**Comment by maju6406** [comment]
Atlas notifies you when someone taps on the message in a conversation, but then leaves it up to you what to do next.  Atlas Messenger does what you're looking for.  Check out the code here:
https://github.com/layerhq/Atlas-Messenger-iOS/blob/master/Code/Controllers/ATLMConversationViewController.m#L206

**Comment by kmahal** [comment]
@imkevinxu as Abir mentioned, the first part is shown in Atlas messenger.  For saving to the camera roll, a developer can subclass the image picker delegate method in their `ATLConversationViewController` subclass:
```objc
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
  [super imagePickerController:picker didFinishPickingMediaWithInfo:info];
// save the picture if you so choose.
}
```
