### ISSUE TITLE
Different metadata to differentiate taking a live picture from picking an album picture

### ISSUE THREAD

**Issue by rafbgarcia** [layerhq/Atlas-iOS#907]
Hello there!

Not sure if that's possible as of now, I've just started using Atlas (which is pretty awesome btw!) and would like to know if the user sent an image from his Photo Album or if he just took that Picture from this camera.

As far as I've read in `ATLConversationViewController` I couldn't see a way of natively doing it, am I mistaken?

Appreciate the help! :)

**Comment by maju6406** [comment]
Not sure if there's an easy way to tell where a picture came from.  You could keep track of whether they pressed the"Take Photo or Video", "Last Photo", "Photo/Video Library" buttons as a proxy.

**Comment by kmahal** [comment]
@rafbgarcia you can add your own `LYRMessagePart` to each image sent. 

In your `ATLConversationViewController` subclass, you can check the image type:
```objc
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
    [super imagePickerController:picker didFinishPickingMediaWithInfo:info];
    NSURL *assetURL = (NSURL *)info[UIImagePickerControllerReferenceURL];
    if (assetURL) {
        // from camera roll.  set your property here
    } else {
        // taken from live camera.  set your property here.
    }
}
```
 The `ATLConversationViewController` delegate method: `conversationViewController:messagesForMediaAttachments:` is called before Atlas sends each of your messages.  For images we send over 3 parts, the full size image, a thumbnail, and sizing data.  You can add a 4th message part when it sends images:
```objc
- (NSOrderedSet *)conversationViewController:(ATLConversationViewController *)viewController messagesForMediaAttachments:(NSArray *)mediaAttachments
{
	NSMutableOrderedSet *set = [NSMutableOrderedSet new];
	for (ATLMediaAttachment *mediaAttachement in mediaAttachments) {
		if ([mediAttachment.MIMEtype isEqualToString:ATLMIMETypeImageJPEG]) {
			NSArray *array = ATLMessagePartsWithMediaAttachment(mediaAttachment);
			LYRMessagePart *part = [LYRMessagePart messagePartWithMIMEType:@"<YOUR-MIME-HERE" data:<MAKE YOUR PROPERTY SET ABOVE INTO A DATA OBJECT>];
			array = [array arrayByAddingObject:part];
		    NSError *error;
		    LYRMessage *message = [self.layerClient newMessageWithParts:array options:pushOptions error:&error];
		    if (error) {
		        return nil;
		    }
		    [set addObject:message];
    	} else {
    		[set addObject:[self.layerClient newMessageWithParts:ATLMessagePartsWithMediaAttachment:mediaAttachment options:pushOptions error:nil];
    	}
	}
	return set;
}
```
Now you can just search for your new MIME type defined and have that info on the `LYRMessage` object as a part.

**Comment by rafbgarcia** [comment]
@maju6406 Thank you for your help!

@kmahal That sounds a very nice solution, thank you! I'm gonna try that out tomorrow!

Thank you both again :)
