### ISSUE TITLE
Not able to modify ATLMessageInputToolbar's right accessory button font

### ISSUE THREAD

**Issue by damirstuhec** [layerhq/Atlas-iOS#909]
One cannot modify `rightAccessoryButton`'s title label font in `ATLMessageInputToolbar`.

The reason for that is the font value being restored back to the default value when the `- (void)configureRightAccessoryButtonForText` method is called. This also happens to be in `- (void)textViewDidChange:(UITextView *)textView`, which will restore font value every time the message text changes.

It would be nice to have an appearance proxy like you have for active color (`rightAccessoryButtonActiveColor`) and disabled color (`rightAccessoryButtonDisabledColor`), or simply don't restore the font value after setup since it doesn't make any sense.

**Comment by kmahal** [comment]
HI @damirstuhec this has been merged here: https://github.com/layerhq/Atlas-iOS/pull/930

**Comment by damirstuhec** [comment]
:+1:
