### ISSUE TITLE
Improve appearance on wider displays

### ISSUE THREAD

**Issue by varkor** [layerhq/Atlas-iOS#910]
At the moment the conversations do not take advantage of the iPad screen's full width, and are just confined to the regions at the same, making it unsuited to use on such devices. The function `ATLMaxCellWidth()` should probably take the parent view's bounds into account, rather than simply returning a constant.

**Comment by maju6406** [comment]
As you mentioned, Atlas does not currently support iPads.  However, if you know how to fix it so that the iPad could be supported I recommend that you make the changes and submit a PR. Thanks!

**Comment by kradenkov** [comment]
Kindly ask you confirm that Atlas still suport iPhone only. I've received geometry warnings while executing Layer-Parse_Sample in Universal device mode.
