### ISSUE TITLE
Text truncated when using a custom font/fontsize

### ISSUE THREAD

**Issue by ntnmrndn** [layerhq/Atlas-iOS#913]
I just found this bug while customizing layer:

<img width="473" alt="capture d ecran 2015-08-05 a 17 00 18" src="https://cloud.githubusercontent.com/assets/1104823/9089049/8ce8d7f2-3b93-11e5-9e74-a2c053b41a41.png">

The sentence should end in iDisk, not iDi...
The text label should never be allowed to truncate text, as there is no way for the user to display it fully.

**Comment by kmahal** [comment]
Hi @ntnmrndn what customizations were you doing?  I see the bubbleview width is smaller than our default amount.  Let us know and we can look into it.

**Comment by ntnmrndn** [comment]
The bubble view width is left unchanged (we'll work on an increase very soon), but the image is only at 75% size (I need the whole simulator to fit on my screen).
Here are the modifications:

        outgoingAppearance.bubbleViewColor = UIColor.palerGreenColor
        outgoingAppearance.messageTextFont = UIFont(name: "Roboto-Light", size: 25)
        outgoingAppearance.messageTextColor = UIColor.deepBlue
        let incomingAppearance = ATLIncomingMessageCollectionViewCell.appearance()
        incomingAppearance.bubbleViewColor = UIColor.palerRedColor
        incomingAppearance.messageTextFont = UIFont(name: "Roboto-Light", size: 25)
        incomingAppearance.messageTextColor = UIColor.deepBlue

We call it from appDidFinishLaunchingWithOptions

**Comment by kmahal** [comment]
Hi @ntnmrndn is this still an issue?  Reviewing older tickets and came across this.  Please let me know, thanks.

**Comment by ntnmrndn** [comment]
I'm not sure about it. We subclassed everything so this is not an issue for us anymore.
