### ISSUE TITLE
ATLConversationListViewController SearchController/Searchbar should be optional

### ISSUE THREAD

**Issue by cashmash** [layerhq/Atlas-iOS#917]
Probably provide a boolean flag like — shouldDisplaySearchBarController or shouldEnableSearch.

**Comment by kmahal** [comment]
HI @cashmash.  As Atlas is an open sourced project, please feel free to submit a pull request.  This feature is not an internal high priority, though we have logged it.  Thanks.

**Comment by stasix** [comment]
would also like that.

**Comment by jhaville** [comment]
+1

**Comment by kmahal** [comment]
@cashmash @stasix @jhaville if you immediately want this functionality removed you can override the view, by setting

```
    self.tableView.tableHeaderView = nil;
```
in your `ATLConversationListViewController` subclass's `viewDidLoad`.

**Comment by jhaville** [comment]
That doesn't quite work - you have to play around with the offset and whether you've displayed the view already if I remember correctly.

**Comment by cashmash** [comment]
should be reopened?
