### ISSUE TITLE
How to show avatar only for first message in consecutive messages from same user

### ISSUE THREAD

**Issue by oscarvgg** [layerhq/Atlas-iOS#922]
I wanted to know if it is posible to show the avatar only for the first message when a user sends many messages one after another without the interruption of other participants

Example:
```
Oscar --------------------------------------
 |Avatar| message
          message 2
          message 3
------------------------------------- Amanda
                                 my messages
                               my messages 2
                               my messages 3
Oscar ----------------------------------------
 |Avatar| message
          message 2
          message 3
```
If there is no way to accomplish this with the current version of the code. I think it could be done if the conversationDataSource was public. So I could check if the previous message was from the same user.

Thanks in advance.

**Comment by chipxsd** [comment]
This is already built in Atlas, clustering messages from the same sender with a single occurrence of the avatar (in that cluster).

Play around with the `avatarItemDisplayFrequency` property on the `ATLConversationViewController` instance. These are the options it gives you:
```objective-c
typedef NS_ENUM(NSUInteger, ATLAvatarItemDisplayFrequency) {
    ATLAvatarItemDisplayFrequencySection,
    ATLAvatarItemDisplayFrequencyCluster,
    ATLAvatarItemDisplayFrequencyAll
};
```

[Atlas-messenger](https://github.com/layerhq/Atlas-Messenger-iOS) demonstrates that in group conversations:
![11_group](https://cloud.githubusercontent.com/assets/1230138/9209996/6f792e52-402e-11e5-8763-183cfc00646e.gif)

**Comment by oscarvgg** [comment]
@chipxsd my ATLConversationViewController doesn't have that property... I'm using version 1.0.10 installed with cocoa pods

**Comment by chipxsd** [comment]
You're correct, it's in the pipeline for the next release, sorry about that. Until then, you can experiment with the development branch, just point the pod to this git repo (it's on the master branch).

**Comment by oscarvgg** [comment]
Thanks! I tried with the new feature but it's not as customisable as I need it to be. I'll make the changes I need and submit a pull request soon.

**Comment by chipxsd** [comment]
Thank you, and I'm looking forward to your pull request.

**Comment by kmahal** [comment]
@oscarvgg any update on this PR?  If not we'll close this out.
