### ISSUE TITLE
transparent image message bubble background

### ISSUE THREAD

**Issue by mohammedDehairy** [layerhq/Atlas-iOS#926]
i want to make the image message bubble background color transparent , instead no matter what i do the image message bubble background is white , i have tried sub classing ATLIncomingMessageCollectionViewCell and then do this inside its implementation (after detecting its an image message) :

        self.bubbleViewColor = [UIColor clearColor];
        self.bubbleView.backgroundColor = [UIColor clearColor];

but doesn't seem to work .

**Comment by kmahal** [comment]
@mohammedDehairy are you trying to make the cell transparent when an image is loaded?  If so you'll have to set the cell's `alpha`, not the background color.  Setting the color to `clearColor` just means the cell's background is clear, which is shown when downloading an image.

**Comment by kmahal** [comment]
the cell's alpha is not a configurable property via `UIAppearance`, but you can customize it yourself by implementing `conversationViewController:configureCell:forMessage`

**Comment by mohammedDehairy** [comment]
you see in this screen shot the "out the door" image has a white background , i can't get rid of it , and its not part of the image itself .


![ios simulator screen shot aug 19 2015 10 40 59 am](https://cloud.githubusercontent.com/assets/2619933/9352096/d22d856c-465e-11e5-8806-791157c89115.png)

**Comment by kmahal** [comment]
@mohammedDehairy the default bubble view color is `ATLBlueColor`.  The bubble view also expands the image to fit the dimensions of the cell, so this indicates that the image itself does have that white padding around it.  Does changing the background color change that white padding?

**Comment by mohammedDehairy** [comment]
No, changing the background color doesn't change the white padding , and the image doesn't seem to have a white padding when i open it in mac Preview app .

<img width="554" alt="screen shot 2015-08-19 at 7 02 01 pm" src="https://cloud.githubusercontent.com/assets/2619933/9363127/d57f6352-46a4-11e5-84fc-e70eb2157fbf.png">

**Comment by kmahal** [comment]
HI @mohammedDehairy apologies for the late follow up.  Is this still an issue for you currently?

**Comment by mohammedDehairy** [comment]
Hi , its kind of a problem yes , but we decided to work around it by using
images with no transparent background , but it would be nice though if the
white background disappeared .

**Comment by kmahal** [comment]
@mohammedDehairy I was able to get a transparent background working correctly with:
```objc
    [[ATLIncomingMessageCollectionViewCell appearance] setBubbleViewColor:[UIColor clearColor]];
```
I'm going to close this ticket out.  We can re-open it if there are further Atlas specific issues.
