### ISSUE TITLE
Prevent right accessory button default behaviour (sendLocationMessage)

### ISSUE THREAD

**Issue by daninfpj** [layerhq/Atlas-iOS#928]
In https://github.com/layerhq/Atlas-iOS/issues/841 you mention that returning an empty `NSOrderedSet` will prevent `ATLConversationViewController` from sending the location. However that's not the case because of line 586:

`if (messages.count == 0 && self.messageInputToolbar.textInputView.text.length == 0) {`
`  [self sendLocationMessage];`

So, it doesn't matter if I return `nil` or an empty `NSOrderedSet` from my `messagesForMediaAttachments`, it will always send the location.

What I've had to do is change the input to contain some arbitrary text, but either an empty set or some configuration should disable that behaviour.

**Comment by kmahal** [comment]
Hi @daninfpj what use case do you not want to send a message?

It is correct, that the above code should actually be
`if (messages && messages.count == 0 && self.messageInputToolbar.textInputView.text.length == 0) {`
as a `nil` messages ordered set (which is set by returning an empty `NSOrderedSet` in the delegate) still evaluates `messages.count == 0` as `YES`.  This would only occur if pressing the right accessory button without typing any text, and with the right accessory image being displayed in it's default state.

Regardless, we'll get a fix out for this in our next release.

**Comment by kmahal** [comment]
Fixed in https://github.com/layerhq/Atlas-iOS/pull/929.

**Comment by daninfpj** [comment]
Hey @kmahal, awesome, thanks for the PR.

The use case was this: when the right accessory button is tapped I present a modal view controller, in which the message is created. So the message is not created right away but after some user interaction, that's why initially I do not want to send any message.

**Comment by kmahal** [comment]
Got it.  Thanks for the feedback @daninfpj!
