### ISSUE TITLE
dictation just only record 1 word when we try to send message

### ISSUE THREAD

**Issue by khanhvu161188** [layerhq/Atlas-iOS#939]
When you press on microphone on keyboard:
- On list of conversation, it works normally
- On conversation view, it just only record 1 first word. I try to not use Typing indicator feature and it can work 

What can i do for make dictation work with Typing Indicator?

**Comment by kmahal** [comment]
@khanhvu161188 can you explain further what it means that it works on the conversation list?  Do you mean in the search bar?  And how are you disabling the typing indicator?

**Comment by khanhvu161188** [comment]
No sir, i'm trying on Conversation page not Conversation List!when i enable dictitation instead of typying on input textbox,i cannot get more than 3 words! And i try to turn off sending typing to another in this conversation,it will work with dictation

Sent from Outlook




On Mon, Aug 31, 2015 at 4:39 PM -0700, "Kabir Mahal" <notifications@github.com> wrote:
@khanhvu161188 can you explain further what it means that it works on the conversation list?  Do you mean in the search bar?  And how are you disabling the typing indicator?

---

**Comment by kmahal** [comment]
@khanhvu161188 this is working on the master build currently.  More importantly, this would be an Apple OS related issue.  The developer has no control over the input there, as the textivew is simply the first responder of the view, and not an Atlas issue.
