### ISSUE TITLE
ATLMessageInputToolbar: Persist text (again)

### ISSUE THREAD

**Issue by thomasgpeng** [layerhq/Atlas-iOS#941]
This is a reference to issue #849.

I'm trying to implement unsent message caching.  Storing `messageInputToolbar.mediaAttachments` in a cache is working fine, but when I try to insert them using `[messageInputToolbar insertMediaAttachment:]`, I'm seeing some odd toolbar behavior.  I've only tried this with text, but the text content does not show up in the `textInputView`, and when I type new text, the `textInputView` height shrinks and appears to have multiple lines in it.

Can anybody point me to what I'm doing wrong?  Thanks!

**Comment by kmahal** [comment]
@thomasgpeng this has been implemented here: https://github.com/layerhq/Atlas-iOS/pull/883.  Its currently on master, and will be out in `1.0.11` this week.

**Comment by thomasgpeng** [comment]
Great, thanks @kmahal
