### ISSUE TITLE
Localized/Customized send button text truncated

### ISSUE THREAD

**Issue by garhiggins** [layerhq/Atlas-iOS#942]
The fixed width on the send button (static CGFloat const ATLRightAccessoryButtonWidth = 46.0f;) causes longer strings to get truncated. I'll try to create a fix tomorrow.
![send](https://cloud.githubusercontent.com/assets/9663880/9456982/2797c584-4a93-11e5-865d-501f01acfd0a.jpg)

**Comment by kmahal** [comment]
@garhiggins commented on your PR.

**Comment by kmahal** [comment]
merged a feature: https://github.com/layerhq/Atlas-iOS/pull/1022
