### ISSUE TITLE
Atlas no longer compiles with LayerKit 0.15.1

### ISSUE THREAD

**Issue by dreese** [layerhq/Atlas-iOS#948]
The LayerKit pod was updated today and has breaking changes for Atlas. Specifically,
```
- (LYRQueryController *)queryControllerWithQuery:(LYRQuery *)query;
```
is now this:
```
- (LYRQueryController *)queryControllerWithQuery:(LYRQuery *)query error:(NSError **)error;
```

**Comment by kmahal** [comment]
Fixed and merged in https://github.com/layerhq/Atlas-iOS/pull/950.  Atlas `1.0.11` is now out.
