### ISSUE TITLE
Extending ATLConversationListViewController 

### ISSUE THREAD

**Issue by koptan** [layerhq/Atlas-iOS#954]
Hi , 

I am trying to extend ATLConversationListViewController , but i getting the following error :

'NSInternalInconsistencyException', reason: '-[UITableViewController loadView] loaded the "8v3-DW-LRI-view-PN4-4X-G1S" nib but didn't get a UITableView.'

Please Help .

**Comment by kmahal** [comment]
Hi @koptan are you extending or subclassing?  Storyboard or code?

**Comment by kmahal** [comment]
@koptan is this still an issue?  If not I will close this ticket.

**Comment by koptan** [comment]
No it's may bad , so thank you for closing this ticket .

**Comment by jyounus** [comment]
What did you do differently to fix the issue @koptan? I'm having the same issue.

**Comment by jyounus** [comment]
I managed to fix my problem. For anyone that has the same issue in the future:

Make sure you drag out a UITableViewController in storyboard and NOT a UIViewController. Then just set the "Custom Class" via Interface Builder to your custom subclass. That should do the trick.
