### ISSUE TITLE
 load list of conversation by another predicate

### ISSUE THREAD

**Issue by khanhvu161188** [layerhq/Atlas-iOS#956]
Currently we load list conversations by participants contain current authenticated userId
So if i want to have 2 pages, 1 for list conversations from 'work' and 1 for list conversations from 'home'. How can i do it?

**Comment by dippigu** [comment]
Hi @khanhvu161188, you could do this by adding a value to the metadata when creating the conversation and then using tis to retrieve the different types of conversation.

<code>[conversation setValue:@"work" forMetadataAtKeyPath:@"conversationType"];</code>

When loading your conversations, you would then use a predicate to fetch only conversations where the metadata key "conversationType" contained "work" or "home"

**Comment by khanhvu161188** [comment]
hi sir,i've added metadata but i couldnot retrieve list by predicate!can u give me example on ios for query by metadata?

Sent from Outlook




On Tue, Sep 8, 2015 at 4:52 AM -0700, "Alan Morris" <notifications@github.com> wrote:
Hi @khanhvu161188, you could do this by adding a value to the metadata when creating the conversation and then using tis to retrieve the different types of conversation.

<code>[conversation setValue:@"work" forMetadataAtKeyPath:@"conversationType"];</code>

When loading your conversations, you would then use a predicate to fetch only conversations where the metadata key "conversationType" contained "work" or "home"

---

**Comment by khanhvu161188** [comment]
Hi @dippigu,
I've added value for metadata 
```
{
type: "home"
}
```
but when i execute this query, it returns nothing
```
    LYRQuery *testQuery =[LYRQuery queryWithQueryableClass:[LYRConversation class]];
    LYRPredicate *homePredicate = [LYRPredicate predicateWithProperty:@"metadata.type" predicateOperator:LYRPredicateOperatorIsEqualTo value:@"home"];
    testQuery.predicate = homePredicate;
    NSError *error=nil;
   
    int countForHome = (int)[ [theAppDelegate layerClient] countForQuery:testQuery error:&error];

```

**Comment by kmahal** [comment]
@khanhvu161188 is the conversation already persisted?  If you haven't sent a message then it's not queryable.

**Comment by khanhvu161188** [comment]
@kmahal  Its supported now by new version of Layer.

LayerKit Change Log
0.16.0
Public API Changes

    LYRQueryController initialization on the LYRClient changes from queryControllerWithQuery: to queryControllerWithQuery:error: to return an error when the client isn't authenticated and a controller can't be created.
    LYRQuery now supports LYRConversation querying on property metadata in dictionary and key path forms.
    LayerKit client now tries to resolve message parts' MIMEType and uses an appropriate filename extension for the rich content (LYRMessagePart *)part.fileURL
