### ISSUE TITLE
Image is not showing in chat 

### ISSUE THREAD

**Issue by kumararun540** [layerhq/Atlas-iOS#957]
Hi, 

Incoming cell is not showing image, its only showing white area in the place of image. 
Any extra code need to add for image or what i am missing ?

**Comment by kmahal** [comment]
Hi @kumararun540 you must specify `autoDownloadMIMETypes` on the `LYRClient` to be `ATLMIMETypeTextPlain` and `ATLMIMETypeImageJPEGPreview` so that way it will autodownload that content.
