### ISSUE TITLE
Conversation created with MIME type "invitation/sent" shows for all users

### ISSUE THREAD

**Issue by dippigu** [layerhq/Atlas-iOS#958]
In the online help files, at: https://support.layer.com/hc/en-us/articles/204193200-Why-can-t-participants-query-a-newly-created-conversation-, it is suggested that it is possible to create a conversation with the MIME type "invitation/sent" which will create a conversation, but not alert any of the other participants until a message has been sent.

> To get around this limitation, you can create an "Invitation" message using the Message Parts MIME type that will force the creation of the conversation, but should not actually be displayed to users.

When I create a conversation using this MIME type, I actually see the conversation appear in the conversation list of all participants, and also see an empty message bubble appear in the conversation window for all participants.

![ios simulator screen shot 8 sep 2015 17 23 10](https://cloud.githubusercontent.com/assets/2050883/9740760/4e3ea902-564e-11e5-91f2-9f8ff7f5643e.png)

**Comment by kmahal** [comment]
Hi @dippigu We'll be sure to update that article with the most relevant information, as most importantly it was written before Atlas was released, and not meant to be used for Atlas as is.  It is still not best practice to have hidden messages, but if it a must then to do so with Atlas you must register a custom cell with reuse identifier using the method:
```objc
- (void)registerClass:(Class<ATLMessagePresenting>)cellClass forMessageCellWithReuseIdentifier:(NSString *)reuseIdentifier;
```
As well as the data source method:
```objc
- (NSString *)conversationViewController:(ATLConversationViewController *)viewController reuseIdentifierForMessage:(LYRMessage *)message;
```
and:
```objc
- (CGFloat)conversationViewController:(ATLConversationViewController *)viewController heightForMessage:(LYRMessage *)message withCellWidth:(CGFloat)cellWidth;
```
