### ISSUE TITLE
Subclassing ATLMessageInputToolbar in Swift

### ISSUE THREAD

**Issue by dfinzer** [layerhq/Atlas-iOS#959]
I'm attempting to subclass ATLMessageInputToolbar using Swift. I've made my own subclass but when I attempt to override self.view.inputAccessoryView, I am getting "Cannot assign to the result of this expression"

```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.messageInputToolbar = MessageInputToolbar()
        self.view.inputAccessoryView = self.messageInputToolbar
```

I think this has to do with how optionals work in Swift vs. Objective-C, but I'm not entirely sure. Any workarounds?

**Comment by kmahal** [comment]
@dfinzer `inputAccessoryView` is a `readonly` property of the view.  We can work on a PR to open it up, but for now you can add this to your `ATLConversationViewController` subclass:

```objc
@interface ATLBaseConversationViewController ()

@property (nonatomic) ATLConversationView *view;

@end
```
Then your code should work, as we set the input accessory view privately in that controller.

**Comment by dfinzer** [comment]
Thanks @kmahal , do you know how would I do this in Swift?

**Comment by dfinzer** [comment]
@kmahal still having a bit of trouble understanding how this would work in Swift, any ideas?
