### ISSUE TITLE
Warnings in all header files.

### ISSUE THREAD

**Issue by iamchenchen** [layerhq/Atlas-iOS#962]
I got 150 warnings with similar warning like this:
/Libraries/Atlas/Code/Views/ATLAvatarImageView.h:36:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed

I'm using XCode 6.4.  

Is there anyway I can ignore all these warnings?

**Comment by blakewatters** [comment]
Couple of options:

1. If you are using super aggressive warning settings, then turn them off.
2. If you are using CocoaPods, then use the suppression config to suppress them.
3. If you really care, then submit a PR that fixes them.

**Comment by iamchenchen** [comment]
@blakewatters I really want to turn it off, but I don't know which one to turn off, could you point me to the right setting?  PS: I tried google myself for a while already.  Thanks!
https://www.dropbox.com/s/vqnmc9shli1lt1w/Screenshot%202015-09-12%2003.24.57.png?dl=0
