### ISSUE TITLE
Atlas-iOS pod is causing my App to crash

### ISSUE THREAD

**Issue by imroopesh** [layerhq/Atlas-iOS#963]
Here's my Pod file

source 'https://github.com/CocoaPods/Specs.git'
pod 'Atlas'
pod 'FMDB'
pod 'FMDBMigrationManager'
xcodeproj 'MyProject.xcodeproj'

http://stackoverflow.com/questions/32570314/fmdbmigrationmanager-crash

Integrating 'Atlas' into my project is causing my app to crash.  I removed the pod and the app works like magic. Is Layer using FMDBMigrationManager internally ? 

I need to use Custom Chat controller for my project to implement messaging in my application.

**Comment by kmahal** [comment]
@imroopesh `FMDBMigrationManager` was created by Layer https://github.com/layerhq/FMDBMigrationManager#credits.  We use it internally in `LayerKit`.
