### ISSUE TITLE
Preventing ATLConversationViewController from marking messages as read

### ISSUE THREAD

**Issue by dfinzer** [layerhq/Atlas-iOS#964]
Hi there,

I'm subclassing ATLConversationViewController and was wondering if there's any easy way to prevent messages from automatically getting marked as read. (I only want to mark certain messages as read when a user performs a particular action)

**Comment by kmahal** [comment]
@dfinzer Currently there is no way to do so.  The `ATLConversationViewController` privately calls `configureControllerForConversation` which marks all messages as read, and the `ATLMessageCollectionViewCell` also mark it's individual message as read when it is rendered on screen.  Feel free to submit a pull request and to use your own cells to create this behavior.

**Comment by dfinzer** [comment]
Sounds good, will do. I'm seeing a ```marksMessagesAsRead``` property on ```ATLConversationViewController``` added a while back but it looks like it isn't being checked, is that correct or am I just looking in the wrong place?

**Comment by kmahal** [comment]
@dfinzer commented on your branch.  Thanks!
