### ISSUE TITLE
Black Message Input Toolbar on iOS 9

### ISSUE THREAD

**Issue by andrewchae** [layerhq/Atlas-iOS#966]
On iOS 9 the message input toolbar is black while the view is animating in. 

![img_0031](https://cloud.githubusercontent.com/assets/5205000/9895021/6e9fdfc2-5bdf-11e5-9e0f-8f956c463da2.PNG)

Video here: https://youtu.be/DnsgICX_hKw

**Comment by dippigu** [comment]
I'm seeing this same issue. I seem to recall seeing it a while back, possibly when pushing over the top of a tab bar controller.

**Comment by nmeyer** [comment]
Yup. We've got the same issue. And we are pushing on top of a tab bar controller.

**Comment by kmahal** [comment]
@nmeyer you should hide the tab bar when pushing a controller with an input accessory view.

**Comment by kmahal** [comment]
Been testing this out - not seeing this issue on the Atlas repo.  @andrewchae can you still reproduce this issue on the latest Xcode version?

**Comment by khanhvu161188** [comment]
@kmahal, we fade same issue on ios 9 too.

**Comment by andrewchae** [comment]
Hi @kmahal, I'm still seeing this issue. Is it possible that you are building to the simulator? I only see this issue building to an actual device.

**Comment by neil477** [comment]
Have you guys tried setting self.messageInputToolbar.translucent = NO? I saw this a few days ago and that seemed to solve it for me

**Comment by kmahal** [comment]
PR for fix: https://github.com/layerhq/Atlas-iOS/pull/977.  Should be merged in soon.

**Comment by andrewchae** [comment]
Thanks @kmahal!

**Comment by kmahal** [comment]
merged. https://github.com/layerhq/Atlas-iOS/pull/977

**Comment by lkraider** [comment]
Now it is always white, which breaks black customized layouts.
