### ISSUE TITLE
Prefill ATLAddressBarViewController

### ISSUE THREAD

**Issue by dfinzer** [layerhq/Atlas-iOS#968]
Hi there, I was wondering if there was any way to prefill an ATLAddressBarViewController with contacts when the user taps on the text field in a conversation view controller. I'd like to show some contacts *before* the user starts searching (this is similar to what Facebook Messenger does). Thanks!

**Comment by kmahal** [comment]
@dfinzer Currently, there isn't a way through Atlas.  The data source method is called on the `UITextView` delegate `textViewDidChange:`.  Feel free to submit a PR for this feature, where an optional boolean flag can have the controller fire that data source method with the appropriate set up.

**Comment by MatthewAnthonyBordas** [comment]
I able to prefill the address bar controller with this line of code in my ConversationViewController:
self.addressBarController.selectedParticipants = [NSOrderedSet orderedSetWithObject: _personObject];

Where _personObject is a property declared as: @property (strong, nonatomic) PFUser *personObject;

**Comment by kmahal** [comment]
@dfinzer I'm going to close this issue out and comment on the PR directly.
