### ISSUE TITLE
Message view recipient bar overlapping first text bubble

### ISSUE THREAD

**Issue by jantos** [layerhq/Atlas-iOS#970]
I am using xcode 7.0 and iOS 9 sdk running on iPhone6s simulator. There is also the following error / warning in the console:
----------------------------------------------------------------------------------
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-09-18 09:37:40.967 Layer-Parse-iOS-Example[50078:1309072] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property 
```translatesAutoresizingMaskIntoConstraints) 
(
    "<_UILayoutSupportConstraint:0x7ff1a0dce640 V:[_UILayoutSpacer:0x7ff1a0dcfb30'UIVC-topLayoutGuide'(0)]>",
    "<_UILayoutSupportConstraint:0x7ff1a0dce5f0 V:|-(0)-[_UILayoutSpacer:0x7ff1a0dcfb30'UIVC-topLayoutGuide']   (Names: '|':ATLConversationView:0x7ff19bdb6890 )>",
    "<NSLayoutConstraint:0x7ff1a0dca9b0 V:|-(4)-[ATLAddressBarTextView:0x7ff19d0d9e00]   (Names: '|':ATLAddressBarView:0x7ff1a0dc2090 )>",
    "<NSLayoutConstraint:0x7ff1a0dcaa00 ATLAddressBarTextView:0x7ff19d0d9e00.bottom == ATLAddressBarView:0x7ff1a0dc2090.bottom - 4>",
    "<NSLayoutConstraint:0x7ff1a0dcd930 V:|-(0)-[ATLAddressBarView:0x7ff1a0dc2090]   (Names: '|':ATLAddressBarContainerView:0x7ff1a0dc1e60 )>",
    "<NSLayoutConstraint:0x7ff1a0dcda40 UITableView:0x7ff19d03b400.bottom == ATLAddressBarContainerView:0x7ff1a0dc1e60.bottom>",
    "<NSLayoutConstraint:0x7ff1a0dcdac0 V:[ATLAddressBarView:0x7ff1a0dc2090]-(0)-[UITableView:0x7ff19d03b400]>",
    "<NSLayoutConstraint:0x7ff1a0dcffd0 V:[_UILayoutSpacer:0x7ff1a0dcfb30'UIVC-topLayoutGuide']-(0)-[ATLAddressBarContainerView:0x7ff1a0dc1e60]>",
    "<NSLayoutConstraint:0x7ff1a0dd0120 ATLAddressBarContainerView:0x7ff1a0dc1e60.bottom == ATLConversationView:0x7ff19bdb6890.bottom>",
    "<NSLayoutConstraint:0x7ff1a0dd2cf0 'UIView-Encapsulated-Layout-Height' V:[ATLConversationView:0x7ff19bdb6890(0)]>"
)
```
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7ff1a0dcaa00 ATLAddressBarTextView:0x7ff19d0d9e00.bottom == ATLAddressBarView:0x7ff1a0dc2090.bottom - 4>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
----------------------------------------------------------------------------------

And here is a screenshot how it looks.
![overlapping](https://cloud.githubusercontent.com/assets/7196879/9960430/8cac42e8-5de8-11e5-8e87-5b2a379c71fe.jpg)

**Comment by kmahal** [comment]
@jantos Feel free to submit a pull request with the fix. We'll try to have a look at it soon.

**Comment by charlespsdowd** [comment]
On iPhone 5s, this result sin the message input toolbar going black while the constraints are "resolved".

**Comment by kmahal** [comment]
@charlespsdowd this issue was fixed in: https://github.com/layerhq/Atlas-iOS/pull/999.
