### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by tomco** [layerhq/Atlas-iOS#971]
Seems like integrating Atlas using [Carthage](carthage) does not work.

Would be great if you could add support for it.

**Comment by kmahal** [comment]
@tomco we're looking into it, I'll update you here once we get more information.

**Comment by blakewatters** [comment]
Carthage support is now available in v1.0.16

**Comment by blakewatters** [comment]
See https://github.com/layerhq/Atlas-iOS#carthage-installation
