### ISSUE TITLE
ATLConversationTableViewCell cannot be subclassed in Swift 2 because of ATLConversationPresenting protocol

### ISSUE THREAD

**Issue by charlespsdowd** [layerhq/Atlas-iOS#980]
Objective-C:
ATLConversationTableViewCell.h
`@interface ATLConversationTableViewCell : UITableViewCell <ATLConversationPresenting>`

In Swift 2, I implement my Cell class:
`class MyConversationTableViewCell: ATLConversationTableViewCell, ATLConversationPresenting {
}`

To make this work: 
Move the ObjC protocol definition to the ".m"
Add in the protocol method definitions in the ".h"

The .h now looks like:

`@interface ATLConversationTableViewCell : UITableViewCell`

and the interface definitions are in the .h too:

`- (void)presentConversation:(LYRConversation *)conversation;`
`- (void)updateWithConversationTitle:(NSString *)conversationTitle;`
`- (void)updateWithAvatarItem:(id<ATLAvatarItem>)avatarItem;`
`- (void)updateWithLastMessageText:(NSString *)lastMessageText;`

and the .m file changes this line:
`@interface ATLConversationTableViewCell ()  <ATLConversationPresenting>`

Now I can subclass ATLConversationTableViewCell in Swift 2!!!

**Comment by kmahal** [comment]
@charlespsdowd It is bad practice to have code duplication, putting a protocol's methods in a header with a private protocol implementation.  This also makes it seem like optional methods, and not within the customizable design Atlas is intended for.  What use case are you trying to support that you require a subclass?  Feel free to submit a PR with configurable changes, or instead create and register your own custom cell.

**Comment by charlespsdowd** [comment]
Use case: I want to control the shape of the AvatarItem image based on the type of the Avatar. When a plain user, the image is a circle, when it's not a plan user the image is a rounded square. (I also want to add overlays to show different connections, sources of users: like a fb logo, a twitter logo, a snapchat logo, etc. depending on how you normally interact with this person - ATLParticipant).

To achieve this, I subclass the ATLConversationTableViewCell and make my own implementation that modifies the image based on my custom Avatar Type.

It works fine in Swift 1.2 but when I upgrade to Swift 2, the ATLConversationPresenting protocol cannot be applied to my subclass, and therefore I cannot use my subclass as the customer cellClass.

To "fix" (work-around), I tried many different approaches, all of which ended up with me re-implementing your ATLConversationTableViewCell class in full to overcome the public protocol in the .h so I moved things around as above and got it to work...

I did not create a PR as I think this is not the right solution but a way to reproduce the problem -- a change in architecture is needed in the ATLAvatarItem to allow the customisation of the avatar image.

Thanks for your response.

**Comment by kmahal** [comment]
In the ATLConversationViewController we have a delegate method 'conversationViewController:configureCell:forMessage'. We could have the same in the ATLConversationListViewController. Feel free to submit a PR for this. This would let you configure the cell how you see fit without bad code practice or subclassing.

**Comment by charlespsdowd** [comment]
OK -- I'll update that and add a PR. Thanks

**Comment by kmahal** [comment]
@charlespsdowd any update on this?

**Comment by charlespsdowd** [comment]
I did work out a solution for this. Just had to ship some stuff before getting the PR done. 

Sent from my iPhone

> On 15 Oct 2015, at 7:21 p.m., Kabir Mahal <notifications@github.com> wrote:
> 
> Closed #980.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


This e-mail and any attachments are confidential and intended solely for 
the addressee and may also be privileged or exempt from disclosure under 
applicable law and the whims of any reigning monarch and associated 
minions. If you are not the addressee, or the NSA, or CIA, or MIA, and have 
received this e-mail in error, please notify the sender immediately, and 
batten down all hatches. Then delete it from your system and reinstall 
windows and throw the computer out the window. Then buy a Mac. Do not copy, 
disclose or take a selfie with any part of this e-mail or its attachments 
without express blessing.

Internet communications are not guaranteed to be secure, virus-free or 
dragon-free. Bynk does not accept responsibility for any loss arising from 
unauthorised access to, or interference with, dragons. Replies to this 
e-mail may not be monitored or even opened by anyone ever - why aren't you 
on Slack anyway.

Any opinion or other information in this e-mail or its attachments is 
personal to the sender and should not be tweeted, posted on reddit or 
quoted in maritime law unless endorsed by the Public Relations committee of 
Bynk Group PLC and good luck with that.

Bynk is not a bank and is not registered as such but that didn't keep the 
actual banks out of trouble now did it. Bynk will soon by regulated by the 
Central Bank of Ireland and that's when you'll be wanting to lock up your 
daughters and your dragons.

**Comment by charlespsdowd** [comment]
https://github.com/layerhq/Atlas-iOS/pull/1033
