### ISSUE TITLE
Tabbar pop up on Conversation View 

### ISSUE THREAD

**Issue by vikmeup** [layerhq/Atlas-iOS#981]
Above growing text you you could see tabbar view. Tried many things to hide it, but it does not seem to work.

I have TabBar->SplitView->Master->Details (Conversation View)

![simulator screen shot sep 23 2015 11 32 01 pm](https://cloud.githubusercontent.com/assets/1641795/10066796/5312ddbe-624b-11e5-8b6b-8566a46bc82b.png)

**Comment by vikmeup** [comment]
Looks pretty bad in TabBar -> Split View Controller 

![simulator screen shot sep 24 2015 12 32 35 am](https://cloud.githubusercontent.com/assets/1641795/10067760/cfef373a-6253-11e5-9cab-4aa0d0f8a15a.png)

**Comment by kmahal** [comment]
@vikmeup this is an implementation detail of your application, and not one Atlas handles.  When presenting the controller on screen you should hide the tab bar.  The input accessory view (the input field) is managed by the keyboard's window, and thus has no notion of underlying views.  A recent PR changes the width to work well with split view controllers (as seen above the input accessory view is just the controller width, not the screen width as it would be by default).  Feel free to submit a pull request to handle this logic.
