### ISSUE TITLE
Build Issue: XCode7, static use of Atlas Lib 

### ISSUE THREAD

**Issue by cashmash** [layerhq/Atlas-iOS#982]
Getting this error, when building with XCode7 (Atlas-iOS Lib as static lib):

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ATLPlayView", referenced from:
      objc-class-ref in ATLMessageBubbleView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kmahal** [comment]
@cashmash we just released `1.0.12` so this issue should be resolved.
