### ISSUE TITLE
adding images/location doesn't work in iOS 9

### ISSUE THREAD

**Issue by haemi** [layerhq/Atlas-iOS#984]
when I tap the camera or location button with the keyboard open, the area gets grey but nothing happens. It seems as if the Action Buttons (Take Photo, Last Photo Taken, ...) appear behind the keyboard.

If I swipe the keyboard down and press the button again, it works.

**Comment by neil477** [comment]
#979 should be merged soon and will fix that

**Comment by kmahal** [comment]
merged in: https://github.com/layerhq/Atlas-iOS/pull/979
