### ISSUE TITLE
Overriding messageInputToolbar results in conversation view not appropriately scrolling to bottom

### ISSUE THREAD

**Issue by dfinzer** [layerhq/Atlas-iOS#985]
If you override the messageInputToolbar with a custom toolbar, the appropriate notifications don't get observed for that instance of messageInputToolbar, as these notifications are registered for in viewDidLoad(). This results in scrolling to bottom not occurring.

**Comment by kmahal** [comment]
@dfinzer can you extrapolate further?  How are you overriding it?  And what options in `viewDidLoad` aren't being called?  Is there a pull request for this issue?

**Comment by dfinzer** [comment]
I override the toolbar as follows:

```
func viewDidLoad() {
  super.viewDidLoad()
  let toolbar = MessageInputToolbar()
  self.messageInputToolbar = toolbar
```

This was the suggested in https://github.com/layerhq/Atlas-iOS/issues/959. However I now see that this feature isn't really supported yet, so I will close this issue.

In case your curious, the problem is that in super.viewDidLoad(), notifications are set on self.messageInputToolbar:

```
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(textViewTextDidBeginEditing:) name:UITextViewTextDidBeginEditingNotification object:self.messageInputToolbar.textInputView];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(messageInputToolbarDidChangeHeight:) name:ATLMessageInputToolbarDidChangeHeightNotification object:self.messageInputToolbar];
```

But I am setting that property to a new messageInputToolbar so the notifications no longer apply.
