### ISSUE TITLE
Customize conversationListViewController

### ISSUE THREAD

**Issue by chlebta** [layerhq/Atlas-iOS#994]
Hello,
Is there any SIMPLE, clear , way to create custom cell for conversationListView ?

In my opinion the current ListViewController dons't give you much possibility to customize it and it's too complicated. Also documentation is very poor.

**Comment by kmahal** [comment]
@chlebta in `ATLConversationListViewController.h`:
```objc
/**
 @abstract The `UITableViewCell` subclass for customizing the display of the conversations.
 @discussion If you wish to provide your own custom class, your class must conform to the `ATLConversationPresenting` protocol.
 @default `ATLConversationTableViewCell`
 @raises NSInternalInconsistencyException Raised if the value is mutated after the receiver has been presented.
 */
@property (nonatomic) Class<ATLConversationPresenting> cellClass;

/**
 @abstract Sets the height for cells within the receiver.
 @default `76.0`
 @raises NSInternalInconsistencyException Raised if the value is mutated after the receiver has been presented.
 */
@property (nonatomic, assign) CGFloat rowHeight;
```
Create a custom `UITableViewCell` class that conforms to the `ATLConversationPresenting` protocol as show in the documentation.  The `rowHeight` is specified and can be changed if your custom cell requires a different height.

**Comment by chlebta** [comment]
I've created `UITableViewCell` conform to `ATLConversationPresenting` after That I've created subclass of `ATLConversationListViewController` now could you tell me what are required method to re-implements and how do I pass my custom cell to `ATLConversationListViewController` class
