### ISSUE TITLE
Show Participant initial until Avatar loads

### ISSUE THREAD

**Issue by alexmaie** [layerhq/Atlas-iOS#995]
Hey,

I have changed the code from ATLAvatarImageView to show the initials of the participant until the avatar loads.

    - (void)setAvatarItem:(id<ATLAvatarItem>)avatarItem
    {
        if ([avatarItem avatarImageURL]) {
            self.initialsLabel.text = avatarItem.avatarInitials; //show initials for participant
           [self loadAvatarImageWithURL:[avatarItem avatarImageURL]];
      } else if (avatarItem.avatarImage) {
           self.initialsLabel.text = nil;
         self.image = avatarItem.avatarImage;
       } else if (avatarItem.avatarInitials) {
           self.image = nil;
           self.initialsLabel.text = avatarItem.avatarInitials;
       }
       _avatarItem = avatarItem;
     }

And also here, I added an else after trying to load the image from the network. If there is no image, then just return in order to avoid the flicker caused by the animation

      - (void)loadAvatarImageWithURL:(NSURL *)imageURL
     {
    if (![imageURL isKindOfClass:[NSURL class]] || imageURL.absoluteString.length == 0) {
        NSLog(@"Cannot fetch image without URL");
        return;
    }
    
    // Check if image is in cache
    __block NSString *stringURL = imageURL.absoluteString;
    UIImage *image = [[[self class] sharedImageCache] objectForKey:stringURL];
    if (image) {
        self.image = image;
        return;
    }
    
    // If not, fetch the image and add to the cache
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
        UIImage *image = [UIImage imageWithData:[NSData dataWithContentsOfURL:imageURL]];
        if (image) {
            [[[self class] sharedImageCache] setObject:image forKey:stringURL cost:0];
       }else{
            //if no image was loaded from the network then just return
            return;
        }
        dispatch_async(dispatch_get_main_queue(), ^{
            // Try to avoid race conditions
            if ([self.avatarItem avatarImageURL] && [[self.avatarItem avatarImageURL] isEqual:imageURL]) {
                [UIView animateWithDuration:0.2 animations:^{
                    self.alpha = 0.0;
                } completion:^(BOOL finished) {
                    [UIView animateWithDuration:0.5 animations:^{
                        self.image = image;
                        self.alpha = 1.0;
                    }];
                }];
            }
        });
    });
    }

Can this be implemented in the repository? Is there another way to achieve this?

**Comment by kmahal** [comment]
@alexmaie Feel free to submit a pull request with the feature you'd like to see added.

**Comment by alexmaie** [comment]
Hey,

I cloned the repository, added the code and wanted to push the code to a new branch in this repository in order to create the pull request.Is this the right way? Im getting permission error

**Comment by kmahal** [comment]
@alexmaie you have to fork the repository to your own Github account.  Then on your branch you can submit a pull request to this repository.

**Comment by alexmaie** [comment]
Hey,

I haved created the pull request. https://github.com/layerhq/Atlas-iOS/pull/997
I tried to run the tests locally, but the code is causing an exc_bad error. Also I see that all the latest builds have failed.
